import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

/**
 * Wire test for the operator provenance surface (plan R2-8, AC-022 /
 * PR01-03): the import run detail page renders the per-workbook source
 * evidence persisted on ImportArtifact.provenance — coordinates, raw value,
 * date system, parser version, and the normalized result, with the raw
 * evidence kept separate from the interpreted value. Source-text assertions
 * only (no render tests).
 */

const panelPath = resolve(
  __dirname,
  "../../../src/features/admin/import/ImportProvenancePanel.tsx",
);
const panel = readFileSync(panelPath, "utf8");
const pagePath = resolve(
  __dirname,
  "../../../src/features/admin/import/ImportRunDetailPage.tsx",
);
const page = readFileSync(pagePath, "utf8");

describe("import run detail: source provenance panel", () => {
  it("operator panel renders coordinates, raw value, date system, parser version, and normalized result", () => {
    // The panel reads the artifact rows through the generated by-run query —
    // the same read path the runtime proof walks.
    expect(panel).toContain("api.queries.listImportArtifactByImportRunId");

    // Raw stored evidence is a separate column from the interpreted value.
    expect(panel).toContain("Raw value");
    expect(panel).toContain("Normalized value");

    // Parser identity, date system and the timezone convention are stated,
    // not implied.
    expect(panel).toContain("workbook.parserVersion");
    expect(panel).toContain("workbook.dateSystem");
    expect(panel).toContain("workbook.timezoneAssumption");

    // The preserved original is identified by checksum and sizes.
    expect(panel).toContain("artifact.checksum");
    expect(panel).toContain("artifact.byteSize");

    // Coordinates are sheet!ref.
    expect(panel).toContain("{sheet.name}!{cell.ref}");

    // Absent and unreadable provenance are explicit states, never blanks.
    expect(panel).toMatch(/Provenance not recorded yet/);
    expect(panel).toMatch(/Workbook unreadable/);

    // The detail page mounts the panel.
    expect(page).toContain(
      "<ImportProvenancePanel importRunId={importRun._id} />",
    );

    // DESIGN.md (review R2-14): the sheet is the only rounded surface —
    // workbooks are ruled sections, never nested rounded cards.
    expect(panel).not.toContain("rounded-xs border");
    expect(panel).toContain("divide-y divide-line");

    // Wide evidence tables scroll inside the card instead of clipping the
    // page (DESIGN.md collapsing strategy; the repo's table idiom).
    expect(panel).toContain("overflow-x-auto");

    // The serialized byte budget is stated where truncation is reported.
    expect(panel).toContain("workbook.byteBudget");
  });
});
