/** Generated by Manifest convex.react — do not edit by hand. */
import { useQuery, useMutation } from "convex/react";
import { api } from "../../convex/_generated/api";

/** Reactive list for AvailabilityWindow. */
export function useListAvailabilityWindow() {
  return useQuery(api.queries.listAvailabilityWindow);
}

/** Reactive get-by-id for AvailabilityWindow. Pass "skip" to suspend. */
export function useGetAvailabilityWindow(id: string | "skip") {
  return useQuery(api.queries.getAvailabilityWindow, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for AvailabilityWindow.declare. */
export function useAvailabilityWindowDeclare() {
  return useMutation(api.mutations.AvailabilityWindow_declare);
}

/** Mutation hook for AvailabilityWindow.withdraw. */
export function useAvailabilityWindowWithdraw() {
  return useMutation(api.mutations.AvailabilityWindow_withdraw);
}

/** Governed creation hook for AvailabilityWindow.declare. */
export function useCreateAvailabilityWindow() {
  return useMutation(api.mutations.AvailabilityWindow_createViaDeclare);
}

/** Reactive list for Client. */
export function useListClient() {
  return useQuery(api.queries.listClient);
}

/** Reactive get-by-id for Client. Pass "skip" to suspend. */
export function useGetClient(id: string | "skip") {
  return useQuery(api.queries.getClient, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for Client.archive. */
export function useClientArchive() {
  return useMutation(api.mutations.Client_archive);
}

/** Mutation hook for Client.assignOwner. */
export function useClientAssignOwner() {
  return useMutation(api.mutations.Client_assignOwner);
}

/** Mutation hook for Client.changeBillingProfile. */
export function useClientChangeBillingProfile() {
  return useMutation(api.mutations.Client_changeBillingProfile);
}

/** Mutation hook for Client.changeContact. */
export function useClientChangeContact() {
  return useMutation(api.mutations.Client_changeContact);
}

/** Mutation hook for Client.reactivate. */
export function useClientReactivate() {
  return useMutation(api.mutations.Client_reactivate);
}

/** Mutation hook for Client.register. */
export function useClientRegister() {
  return useMutation(api.mutations.Client_register);
}

/** Governed creation hook for Client.register. */
export function useCreateClient() {
  return useMutation(api.mutations.Client_createViaRegister);
}

/** Reactive list for ClientContact. */
export function useListClientContact() {
  return useQuery(api.queries.listClientContact);
}

/** Reactive get-by-id for ClientContact. Pass "skip" to suspend. */
export function useGetClientContact(id: string | "skip") {
  return useQuery(api.queries.getClientContact, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for ClientContact.add. */
export function useClientContactAdd() {
  return useMutation(api.mutations.ClientContact_add);
}

/** Mutation hook for ClientContact.remove. */
export function useClientContactRemove() {
  return useMutation(api.mutations.ClientContact_remove);
}

/** Mutation hook for ClientContact.setPrimary. */
export function useClientContactSetPrimary() {
  return useMutation(api.mutations.ClientContact_setPrimary);
}

/** Mutation hook for ClientContact.updateDetails. */
export function useClientContactUpdateDetails() {
  return useMutation(api.mutations.ClientContact_updateDetails);
}

/** Governed creation hook for ClientContact.add. */
export function useCreateClientContact() {
  return useMutation(api.mutations.ClientContact_createViaAdd);
}

/** Reactive list for Contract. */
export function useListContract() {
  return useQuery(api.queries.listContract);
}

/** Reactive get-by-id for Contract. Pass "skip" to suspend. */
export function useGetContract(id: string | "skip") {
  return useQuery(api.queries.getContract, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for Contract.draft. */
export function useContractDraft() {
  return useMutation(api.mutations.Contract_draft);
}

/** Mutation hook for Contract.expire. */
export function useContractExpire() {
  return useMutation(api.mutations.Contract_expire);
}

/** Mutation hook for Contract.markViewed. */
export function useContractMarkViewed() {
  return useMutation(api.mutations.Contract_markViewed);
}

/** Mutation hook for Contract.markVoided. */
export function useContractMarkVoided() {
  return useMutation(api.mutations.Contract_markVoided);
}

/** Mutation hook for Contract.send. */
export function useContractSend() {
  return useMutation(api.mutations.Contract_send);
}

/** Mutation hook for Contract.sign. */
export function useContractSign() {
  return useMutation(api.mutations.Contract_sign);
}

/** Governed creation hook for Contract.draft. */
export function useCreateContract() {
  return useMutation(api.mutations.Contract_createViaDraft);
}

/** Reactive list for Delivery. */
export function useListDelivery() {
  return useQuery(api.queries.listDelivery);
}

/** Reactive get-by-id for Delivery. Pass "skip" to suspend. */
export function useGetDelivery(id: string | "skip") {
  return useQuery(api.queries.getDelivery, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for Delivery.cancel. */
export function useDeliveryCancel() {
  return useMutation(api.mutations.Delivery_cancel);
}

/** Mutation hook for Delivery.confirmDelivery. */
export function useDeliveryConfirmDelivery() {
  return useMutation(api.mutations.Delivery_confirmDelivery);
}

/** Mutation hook for Delivery.markFailed. */
export function useDeliveryMarkFailed() {
  return useMutation(api.mutations.Delivery_markFailed);
}

/** Mutation hook for Delivery.schedule. */
export function useDeliverySchedule() {
  return useMutation(api.mutations.Delivery_schedule);
}

/** Mutation hook for Delivery.startTransit. */
export function useDeliveryStartTransit() {
  return useMutation(api.mutations.Delivery_startTransit);
}

/** Governed creation hook for Delivery.schedule. */
export function useCreateDelivery() {
  return useMutation(api.mutations.Delivery_createViaSchedule);
}

/** Reactive list for Dish. */
export function useListDish() {
  return useQuery(api.queries.listDish);
}

/** Reactive get-by-id for Dish. Pass "skip" to suspend. */
export function useGetDish(id: string | "skip") {
  return useQuery(api.queries.getDish, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for Dish.changeRecipe. */
export function useDishChangeRecipe() {
  return useMutation(api.mutations.Dish_changeRecipe);
}

/** Mutation hook for Dish.classifyAllergens. */
export function useDishClassifyAllergens() {
  return useMutation(api.mutations.Dish_classifyAllergens);
}

/** Mutation hook for Dish.introduce. */
export function useDishIntroduce() {
  return useMutation(api.mutations.Dish_introduce);
}

/** Mutation hook for Dish.reinstate. */
export function useDishReinstate() {
  return useMutation(api.mutations.Dish_reinstate);
}

/** Mutation hook for Dish.retire. */
export function useDishRetire() {
  return useMutation(api.mutations.Dish_retire);
}

/** Mutation hook for Dish.reviseDetails. */
export function useDishReviseDetails() {
  return useMutation(api.mutations.Dish_reviseDetails);
}

/** Mutation hook for Dish.updatePortioning. */
export function useDishUpdatePortioning() {
  return useMutation(api.mutations.Dish_updatePortioning);
}

/** Governed creation hook for Dish.introduce. */
export function useCreateDish() {
  return useMutation(api.mutations.Dish_createViaIntroduce);
}

/** Reactive list for Event. */
export function useListEvent() {
  return useQuery(api.queries.listEvent);
}

/** Reactive get-by-id for Event. Pass "skip" to suspend. */
export function useGetEvent(id: string | "skip") {
  return useQuery(api.queries.getEvent, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for Event.approve. */
export function useEventApprove() {
  return useMutation(api.mutations.Event_approve);
}

/** Mutation hook for Event.assignOwner. */
export function useEventAssignOwner() {
  return useMutation(api.mutations.Event_assignOwner);
}

/** Mutation hook for Event.beginExecution. */
export function useEventBeginExecution() {
  return useMutation(api.mutations.Event_beginExecution);
}

/** Mutation hook for Event.cancel. */
export function useEventCancel() {
  return useMutation(api.mutations.Event_cancel);
}

/** Mutation hook for Event.changeHeadcount. */
export function useEventChangeHeadcount() {
  return useMutation(api.mutations.Event_changeHeadcount);
}

/** Mutation hook for Event.changePricing. */
export function useEventChangePricing() {
  return useMutation(api.mutations.Event_changePricing);
}

/** Mutation hook for Event.changePrimaryContact. */
export function useEventChangePrimaryContact() {
  return useMutation(api.mutations.Event_changePrimaryContact);
}

/** Mutation hook for Event.changeRequirements. */
export function useEventChangeRequirements() {
  return useMutation(api.mutations.Event_changeRequirements);
}

/** Mutation hook for Event.changeVenue. */
export function useEventChangeVenue() {
  return useMutation(api.mutations.Event_changeVenue);
}

/** Mutation hook for Event.closeOut. */
export function useEventCloseOut() {
  return useMutation(api.mutations.Event_closeOut);
}

/** Mutation hook for Event.complete. */
export function useEventComplete() {
  return useMutation(api.mutations.Event_complete);
}

/** Mutation hook for Event.planEngagement. */
export function useEventPlanEngagement() {
  return useMutation(api.mutations.Event_planEngagement);
}

/** Mutation hook for Event.reschedule. */
export function useEventReschedule() {
  return useMutation(api.mutations.Event_reschedule);
}

/** Mutation hook for Event.returnToPlanning. */
export function useEventReturnToPlanning() {
  return useMutation(api.mutations.Event_returnToPlanning);
}

/** Mutation hook for Event.submitForApproval. */
export function useEventSubmitForApproval() {
  return useMutation(api.mutations.Event_submitForApproval);
}

/** Governed creation hook for Event.planEngagement. */
export function useCreateEvent() {
  return useMutation(api.mutations.Event_createViaPlanEngagement);
}

/** Reactive list for EventAllergenCheck. */
export function useListEventAllergenCheck() {
  return useQuery(api.queries.listEventAllergenCheck);
}

/** Reactive get-by-id for EventAllergenCheck. Pass "skip" to suspend. */
export function useGetEventAllergenCheck(id: string | "skip") {
  return useQuery(api.queries.getEventAllergenCheck, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for EventAllergenCheck.record. */
export function useEventAllergenCheckRecord() {
  return useMutation(api.mutations.EventAllergenCheck_record);
}

/** Governed creation hook for EventAllergenCheck.record. */
export function useCreateEventAllergenCheck() {
  return useMutation(api.mutations.EventAllergenCheck_createViaRecord);
}

/** Reactive list for EventAssignment. */
export function useListEventAssignment() {
  return useQuery(api.queries.listEventAssignment);
}

/** Reactive get-by-id for EventAssignment. Pass "skip" to suspend. */
export function useGetEventAssignment(id: string | "skip") {
  return useQuery(api.queries.getEventAssignment, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for EventAssignment.assign. */
export function useEventAssignmentAssign() {
  return useMutation(api.mutations.EventAssignment_assign);
}

/** Mutation hook for EventAssignment.checkIn. */
export function useEventAssignmentCheckIn() {
  return useMutation(api.mutations.EventAssignment_checkIn);
}

/** Mutation hook for EventAssignment.checkOut. */
export function useEventAssignmentCheckOut() {
  return useMutation(api.mutations.EventAssignment_checkOut);
}

/** Mutation hook for EventAssignment.confirm. */
export function useEventAssignmentConfirm() {
  return useMutation(api.mutations.EventAssignment_confirm);
}

/** Mutation hook for EventAssignment.markNoShow. */
export function useEventAssignmentMarkNoShow() {
  return useMutation(api.mutations.EventAssignment_markNoShow);
}

/** Mutation hook for EventAssignment.unassign. */
export function useEventAssignmentUnassign() {
  return useMutation(api.mutations.EventAssignment_unassign);
}

/** Governed creation hook for EventAssignment.assign. */
export function useCreateEventAssignment() {
  return useMutation(api.mutations.EventAssignment_createViaAssign);
}

/** Reactive list for EventCloseout. */
export function useListEventCloseout() {
  return useQuery(api.queries.listEventCloseout);
}

/** Reactive get-by-id for EventCloseout. Pass "skip" to suspend. */
export function useGetEventCloseout(id: string | "skip") {
  return useQuery(api.queries.getEventCloseout, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for EventCloseout.capture. */
export function useEventCloseoutCapture() {
  return useMutation(api.mutations.EventCloseout_capture);
}

/** Mutation hook for EventCloseout.finalize. */
export function useEventCloseoutFinalize() {
  return useMutation(api.mutations.EventCloseout_finalize);
}

/** Governed creation hook for EventCloseout.capture. */
export function useCreateEventCloseout() {
  return useMutation(api.mutations.EventCloseout_createViaCapture);
}

/** Reactive list for EventDish. */
export function useListEventDish() {
  return useQuery(api.queries.listEventDish);
}

/** Reactive get-by-id for EventDish. Pass "skip" to suspend. */
export function useGetEventDish(id: string | "skip") {
  return useQuery(api.queries.getEventDish, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for EventDish.adjustServings. */
export function useEventDishAdjustServings() {
  return useMutation(api.mutations.EventDish_adjustServings);
}

/** Mutation hook for EventDish.changeCourse. */
export function useEventDishChangeCourse() {
  return useMutation(api.mutations.EventDish_changeCourse);
}

/** Mutation hook for EventDish.remove. */
export function useEventDishRemove() {
  return useMutation(api.mutations.EventDish_remove);
}

/** Mutation hook for EventDish.select. */
export function useEventDishSelect() {
  return useMutation(api.mutations.EventDish_select);
}

/** Mutation hook for EventDish.updateInstructions. */
export function useEventDishUpdateInstructions() {
  return useMutation(api.mutations.EventDish_updateInstructions);
}

/** Governed creation hook for EventDish.select. */
export function useCreateEventDish() {
  return useMutation(api.mutations.EventDish_createViaSelect);
}

/** Reactive list for EventGuest. */
export function useListEventGuest() {
  return useQuery(api.queries.listEventGuest);
}

/** Reactive get-by-id for EventGuest. Pass "skip" to suspend. */
export function useGetEventGuest(id: string | "skip") {
  return useQuery(api.queries.getEventGuest, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for EventGuest.assignTable. */
export function useEventGuestAssignTable() {
  return useMutation(api.mutations.EventGuest_assignTable);
}

/** Mutation hook for EventGuest.checkIn. */
export function useEventGuestCheckIn() {
  return useMutation(api.mutations.EventGuest_checkIn);
}

/** Mutation hook for EventGuest.invite. */
export function useEventGuestInvite() {
  return useMutation(api.mutations.EventGuest_invite);
}

/** Mutation hook for EventGuest.rsvpConfirm. */
export function useEventGuestRsvpConfirm() {
  return useMutation(api.mutations.EventGuest_rsvpConfirm);
}

/** Mutation hook for EventGuest.rsvpDecline. */
export function useEventGuestRsvpDecline() {
  return useMutation(api.mutations.EventGuest_rsvpDecline);
}

/** Mutation hook for EventGuest.withdraw. */
export function useEventGuestWithdraw() {
  return useMutation(api.mutations.EventGuest_withdraw);
}

/** Governed creation hook for EventGuest.invite. */
export function useCreateEventGuest() {
  return useMutation(api.mutations.EventGuest_createViaInvite);
}

/** Reactive list for Incident. */
export function useListIncident() {
  return useQuery(api.queries.listIncident);
}

/** Reactive get-by-id for Incident. Pass "skip" to suspend. */
export function useGetIncident(id: string | "skip") {
  return useQuery(api.queries.getIncident, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for Incident.beginInvestigation. */
export function useIncidentBeginInvestigation() {
  return useMutation(api.mutations.Incident_beginInvestigation);
}

/** Mutation hook for Incident.dismiss. */
export function useIncidentDismiss() {
  return useMutation(api.mutations.Incident_dismiss);
}

/** Mutation hook for Incident.markResolved. */
export function useIncidentMarkResolved() {
  return useMutation(api.mutations.Incident_markResolved);
}

/** Mutation hook for Incident.report. */
export function useIncidentReport() {
  return useMutation(api.mutations.Incident_report);
}

/** Governed creation hook for Incident.report. */
export function useCreateIncident() {
  return useMutation(api.mutations.Incident_createViaReport);
}

/** Reactive list for Ingredient. */
export function useListIngredient() {
  return useQuery(api.queries.listIngredient);
}

/** Reactive get-by-id for Ingredient. Pass "skip" to suspend. */
export function useGetIngredient(id: string | "skip") {
  return useQuery(api.queries.getIngredient, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for Ingredient.classifyAllergens. */
export function useIngredientClassifyAllergens() {
  return useMutation(api.mutations.Ingredient_classifyAllergens);
}

/** Mutation hook for Ingredient.discontinue. */
export function useIngredientDiscontinue() {
  return useMutation(api.mutations.Ingredient_discontinue);
}

/** Mutation hook for Ingredient.introduce. */
export function useIngredientIntroduce() {
  return useMutation(api.mutations.Ingredient_introduce);
}

/** Mutation hook for Ingredient.reinstate. */
export function useIngredientReinstate() {
  return useMutation(api.mutations.Ingredient_reinstate);
}

/** Mutation hook for Ingredient.updateCosting. */
export function useIngredientUpdateCosting() {
  return useMutation(api.mutations.Ingredient_updateCosting);
}

/** Mutation hook for Ingredient.updateDetails. */
export function useIngredientUpdateDetails() {
  return useMutation(api.mutations.Ingredient_updateDetails);
}

/** Governed creation hook for Ingredient.introduce. */
export function useCreateIngredient() {
  return useMutation(api.mutations.Ingredient_createViaIntroduce);
}

/** Reactive list for IngredientDemand. */
export function useListIngredientDemand() {
  return useQuery(api.queries.listIngredientDemand);
}

/** Reactive get-by-id for IngredientDemand. Pass "skip" to suspend. */
export function useGetIngredientDemand(id: string | "skip") {
  return useQuery(api.queries.getIngredientDemand, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for IngredientDemand.calculate. */
export function useIngredientDemandCalculate() {
  return useMutation(api.mutations.IngredientDemand_calculate);
}

/** Mutation hook for IngredientDemand.confirm. */
export function useIngredientDemandConfirm() {
  return useMutation(api.mutations.IngredientDemand_confirm);
}

/** Mutation hook for IngredientDemand.fulfill. */
export function useIngredientDemandFulfill() {
  return useMutation(api.mutations.IngredientDemand_fulfill);
}

/** Mutation hook for IngredientDemand.recalculate. */
export function useIngredientDemandRecalculate() {
  return useMutation(api.mutations.IngredientDemand_recalculate);
}

/** Mutation hook for IngredientDemand.supersede. */
export function useIngredientDemandSupersede() {
  return useMutation(api.mutations.IngredientDemand_supersede);
}

/** Governed creation hook for IngredientDemand.calculate. */
export function useCreateIngredientDemand() {
  return useMutation(api.mutations.IngredientDemand_createViaCalculate);
}

/** Reactive list for InventoryItem. */
export function useListInventoryItem() {
  return useQuery(api.queries.listInventoryItem);
}

/** Reactive get-by-id for InventoryItem. Pass "skip" to suspend. */
export function useGetInventoryItem(id: string | "skip") {
  return useQuery(api.queries.getInventoryItem, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for InventoryItem.adjustQuantity. */
export function useInventoryItemAdjustQuantity() {
  return useMutation(api.mutations.InventoryItem_adjustQuantity);
}

/** Mutation hook for InventoryItem.open. */
export function useInventoryItemOpen() {
  return useMutation(api.mutations.InventoryItem_open);
}

/** Mutation hook for InventoryItem.receiveStock. */
export function useInventoryItemReceiveStock() {
  return useMutation(api.mutations.InventoryItem_receiveStock);
}

/** Mutation hook for InventoryItem.recount. */
export function useInventoryItemRecount() {
  return useMutation(api.mutations.InventoryItem_recount);
}

/** Mutation hook for InventoryItem.remove. */
export function useInventoryItemRemove() {
  return useMutation(api.mutations.InventoryItem_remove);
}

/** Mutation hook for InventoryItem.transferIn. */
export function useInventoryItemTransferIn() {
  return useMutation(api.mutations.InventoryItem_transferIn);
}

/** Mutation hook for InventoryItem.transferOut. */
export function useInventoryItemTransferOut() {
  return useMutation(api.mutations.InventoryItem_transferOut);
}

/** Mutation hook for InventoryItem.updateLevels. */
export function useInventoryItemUpdateLevels() {
  return useMutation(api.mutations.InventoryItem_updateLevels);
}

/** Governed creation hook for InventoryItem.open. */
export function useCreateInventoryItem() {
  return useMutation(api.mutations.InventoryItem_createViaOpen);
}

/** Reactive list for InventoryReservation. */
export function useListInventoryReservation() {
  return useQuery(api.queries.listInventoryReservation);
}

/** Reactive get-by-id for InventoryReservation. Pass "skip" to suspend. */
export function useGetInventoryReservation(id: string | "skip") {
  return useQuery(api.queries.getInventoryReservation, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for InventoryReservation.consume. */
export function useInventoryReservationConsume() {
  return useMutation(api.mutations.InventoryReservation_consume);
}

/** Mutation hook for InventoryReservation.release. */
export function useInventoryReservationRelease() {
  return useMutation(api.mutations.InventoryReservation_release);
}

/** Mutation hook for InventoryReservation.reserve. */
export function useInventoryReservationReserve() {
  return useMutation(api.mutations.InventoryReservation_reserve);
}

/** Governed creation hook for InventoryReservation.reserve. */
export function useCreateInventoryReservation() {
  return useMutation(api.mutations.InventoryReservation_createViaReserve);
}

/** Reactive list for Invoice. */
export function useListInvoice() {
  return useQuery(api.queries.listInvoice);
}

/** Reactive get-by-id for Invoice. Pass "skip" to suspend. */
export function useGetInvoice(id: string | "skip") {
  return useQuery(api.queries.getInvoice, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for Invoice.applyPayment. */
export function useInvoiceApplyPayment() {
  return useMutation(api.mutations.Invoice_applyPayment);
}

/** Mutation hook for Invoice.issue. */
export function useInvoiceIssue() {
  return useMutation(api.mutations.Invoice_issue);
}

/** Mutation hook for Invoice.markOverdue. */
export function useInvoiceMarkOverdue() {
  return useMutation(api.mutations.Invoice_markOverdue);
}

/** Mutation hook for Invoice.markViewed. */
export function useInvoiceMarkViewed() {
  return useMutation(api.mutations.Invoice_markViewed);
}

/** Mutation hook for Invoice.markVoided. */
export function useInvoiceMarkVoided() {
  return useMutation(api.mutations.Invoice_markVoided);
}

/** Mutation hook for Invoice.recordRefund. */
export function useInvoiceRecordRefund() {
  return useMutation(api.mutations.Invoice_recordRefund);
}

/** Mutation hook for Invoice.send. */
export function useInvoiceSend() {
  return useMutation(api.mutations.Invoice_send);
}

/** Mutation hook for Invoice.writeOff. */
export function useInvoiceWriteOff() {
  return useMutation(api.mutations.Invoice_writeOff);
}

/** Governed creation hook for Invoice.issue. */
export function useCreateInvoice() {
  return useMutation(api.mutations.Invoice_createViaIssue);
}

/** Reactive list for Menu. */
export function useListMenu() {
  return useQuery(api.queries.listMenu);
}

/** Reactive get-by-id for Menu. Pass "skip" to suspend. */
export function useGetMenu(id: string | "skip") {
  return useQuery(api.queries.getMenu, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for Menu.archive. */
export function useMenuArchive() {
  return useMutation(api.mutations.Menu_archive);
}

/** Mutation hook for Menu.draft. */
export function useMenuDraft() {
  return useMutation(api.mutations.Menu_draft);
}

/** Mutation hook for Menu.markPublished. */
export function useMenuMarkPublished() {
  return useMutation(api.mutations.Menu_markPublished);
}

/** Mutation hook for Menu.restore. */
export function useMenuRestore() {
  return useMutation(api.mutations.Menu_restore);
}

/** Mutation hook for Menu.reviseDetails. */
export function useMenuReviseDetails() {
  return useMutation(api.mutations.Menu_reviseDetails);
}

/** Mutation hook for Menu.unpublish. */
export function useMenuUnpublish() {
  return useMutation(api.mutations.Menu_unpublish);
}

/** Mutation hook for Menu.updatePricing. */
export function useMenuUpdatePricing() {
  return useMutation(api.mutations.Menu_updatePricing);
}

/** Governed creation hook for Menu.draft. */
export function useCreateMenu() {
  return useMutation(api.mutations.Menu_createViaDraft);
}

/** Reactive list for Organization. */
export function useListOrganization() {
  return useQuery(api.queries.listOrganization);
}

/** Reactive get-by-id for Organization. Pass "skip" to suspend. */
export function useGetOrganization(id: string | "skip") {
  return useQuery(api.queries.getOrganization, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for Organization.deactivate. */
export function useOrganizationDeactivate() {
  return useMutation(api.mutations.Organization_deactivate);
}

/** Mutation hook for Organization.reactivate. */
export function useOrganizationReactivate() {
  return useMutation(api.mutations.Organization_reactivate);
}

/** Mutation hook for Organization.register. */
export function useOrganizationRegister() {
  return useMutation(api.mutations.Organization_register);
}

/** Mutation hook for Organization.rename. */
export function useOrganizationRename() {
  return useMutation(api.mutations.Organization_rename);
}

/** Mutation hook for Organization.suspend. */
export function useOrganizationSuspend() {
  return useMutation(api.mutations.Organization_suspend);
}

/** Governed creation hook for Organization.register. */
export function useCreateOrganization() {
  return useMutation(api.mutations.Organization_createViaRegister);
}

/** Reactive list for PackList. */
export function useListPackList() {
  return useQuery(api.queries.listPackList);
}

/** Reactive get-by-id for PackList. Pass "skip" to suspend. */
export function useGetPackList(id: string | "skip") {
  return useQuery(api.queries.getPackList, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for PackList.cancel. */
export function usePackListCancel() {
  return useMutation(api.mutations.PackList_cancel);
}

/** Mutation hook for PackList.dispatch. */
export function usePackListDispatch() {
  return useMutation(api.mutations.PackList_dispatch);
}

/** Mutation hook for PackList.markLoaded. */
export function usePackListMarkLoaded() {
  return useMutation(api.mutations.PackList_markLoaded);
}

/** Mutation hook for PackList.markPacked. */
export function usePackListMarkPacked() {
  return useMutation(api.mutations.PackList_markPacked);
}

/** Mutation hook for PackList.open. */
export function usePackListOpen() {
  return useMutation(api.mutations.PackList_open);
}

/** Mutation hook for PackList.startPacking. */
export function usePackListStartPacking() {
  return useMutation(api.mutations.PackList_startPacking);
}

/** Governed creation hook for PackList.open. */
export function useCreatePackList() {
  return useMutation(api.mutations.PackList_createViaOpen);
}

/** Reactive list for PackListItem. */
export function useListPackListItem() {
  return useQuery(api.queries.listPackListItem);
}

/** Reactive get-by-id for PackListItem. Pass "skip" to suspend. */
export function useGetPackListItem(id: string | "skip") {
  return useQuery(api.queries.getPackListItem, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for PackListItem.addItem. */
export function usePackListItemAddItem() {
  return useMutation(api.mutations.PackListItem_addItem);
}

/** Mutation hook for PackListItem.adjustQuantity. */
export function usePackListItemAdjustQuantity() {
  return useMutation(api.mutations.PackListItem_adjustQuantity);
}

/** Mutation hook for PackListItem.markMissing. */
export function usePackListItemMarkMissing() {
  return useMutation(api.mutations.PackListItem_markMissing);
}

/** Mutation hook for PackListItem.markPacked. */
export function usePackListItemMarkPacked() {
  return useMutation(api.mutations.PackListItem_markPacked);
}

/** Governed creation hook for PackListItem.addItem. */
export function useCreatePackListItem() {
  return useMutation(api.mutations.PackListItem_createViaAddItem);
}

/** Reactive list for Payment. */
export function useListPayment() {
  return useQuery(api.queries.listPayment);
}

/** Reactive get-by-id for Payment. Pass "skip" to suspend. */
export function useGetPayment(id: string | "skip") {
  return useQuery(api.queries.getPayment, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for Payment.beginProcessing. */
export function usePaymentBeginProcessing() {
  return useMutation(api.mutations.Payment_beginProcessing);
}

/** Mutation hook for Payment.fail. */
export function usePaymentFail() {
  return useMutation(api.mutations.Payment_fail);
}

/** Mutation hook for Payment.record. */
export function usePaymentRecord() {
  return useMutation(api.mutations.Payment_record);
}

/** Mutation hook for Payment.refund. */
export function usePaymentRefund() {
  return useMutation(api.mutations.Payment_refund);
}

/** Mutation hook for Payment.settle. */
export function usePaymentSettle() {
  return useMutation(api.mutations.Payment_settle);
}

/** Governed creation hook for Payment.record. */
export function useCreatePayment() {
  return useMutation(api.mutations.Payment_createViaRecord);
}

/** Reactive list for PaymentMethod. */
export function useListPaymentMethod() {
  return useQuery(api.queries.listPaymentMethod);
}

/** Reactive get-by-id for PaymentMethod. Pass "skip" to suspend. */
export function useGetPaymentMethod(id: string | "skip") {
  return useQuery(api.queries.getPaymentMethod, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for PaymentMethod.clearDefault. */
export function usePaymentMethodClearDefault() {
  return useMutation(api.mutations.PaymentMethod_clearDefault);
}

/** Mutation hook for PaymentMethod.expire. */
export function usePaymentMethodExpire() {
  return useMutation(api.mutations.PaymentMethod_expire);
}

/** Mutation hook for PaymentMethod.invalidate. */
export function usePaymentMethodInvalidate() {
  return useMutation(api.mutations.PaymentMethod_invalidate);
}

/** Mutation hook for PaymentMethod.makeDefault. */
export function usePaymentMethodMakeDefault() {
  return useMutation(api.mutations.PaymentMethod_makeDefault);
}

/** Mutation hook for PaymentMethod.reactivate. */
export function usePaymentMethodReactivate() {
  return useMutation(api.mutations.PaymentMethod_reactivate);
}

/** Mutation hook for PaymentMethod.register. */
export function usePaymentMethodRegister() {
  return useMutation(api.mutations.PaymentMethod_register);
}

/** Mutation hook for PaymentMethod.remove. */
export function usePaymentMethodRemove() {
  return useMutation(api.mutations.PaymentMethod_remove);
}

/** Governed creation hook for PaymentMethod.register. */
export function useCreatePaymentMethod() {
  return useMutation(api.mutations.PaymentMethod_createViaRegister);
}

/** Reactive list for PayrollInput. */
export function useListPayrollInput() {
  return useQuery(api.queries.listPayrollInput);
}

/** Reactive get-by-id for PayrollInput. Pass "skip" to suspend. */
export function useGetPayrollInput(id: string | "skip") {
  return useQuery(api.queries.getPayrollInput, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for PayrollInput.finalize. */
export function usePayrollInputFinalize() {
  return useMutation(api.mutations.PayrollInput_finalize);
}

/** Mutation hook for PayrollInput.markVoided. */
export function usePayrollInputMarkVoided() {
  return useMutation(api.mutations.PayrollInput_markVoided);
}

/** Mutation hook for PayrollInput.prepare. */
export function usePayrollInputPrepare() {
  return useMutation(api.mutations.PayrollInput_prepare);
}

/** Governed creation hook for PayrollInput.prepare. */
export function useCreatePayrollInput() {
  return useMutation(api.mutations.PayrollInput_createViaPrepare);
}

/** Reactive list for Person. */
export function useListPerson() {
  return useQuery(api.queries.listPerson);
}

/** Reactive get-by-id for Person. Pass "skip" to suspend. */
export function useGetPerson(id: string | "skip") {
  return useQuery(api.queries.getPerson, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for Person.assignRole. */
export function usePersonAssignRole() {
  return useMutation(api.mutations.Person_assignRole);
}

/** Mutation hook for Person.correctIdentity. */
export function usePersonCorrectIdentity() {
  return useMutation(api.mutations.Person_correctIdentity);
}

/** Mutation hook for Person.deactivate. */
export function usePersonDeactivate() {
  return useMutation(api.mutations.Person_deactivate);
}

/** Mutation hook for Person.hire. */
export function usePersonHire() {
  return useMutation(api.mutations.Person_hire);
}

/** Mutation hook for Person.reactivate. */
export function usePersonReactivate() {
  return useMutation(api.mutations.Person_reactivate);
}

/** Mutation hook for Person.terminate. */
export function usePersonTerminate() {
  return useMutation(api.mutations.Person_terminate);
}

/** Governed creation hook for Person.hire. */
export function useCreatePerson() {
  return useMutation(api.mutations.Person_createViaHire);
}

/** Reactive list for PrepTask. */
export function useListPrepTask() {
  return useQuery(api.queries.listPrepTask);
}

/** Reactive get-by-id for PrepTask. Pass "skip" to suspend. */
export function useGetPrepTask(id: string | "skip") {
  return useQuery(api.queries.getPrepTask, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for PrepTask.cancel. */
export function usePrepTaskCancel() {
  return useMutation(api.mutations.PrepTask_cancel);
}

/** Mutation hook for PrepTask.claim. */
export function usePrepTaskClaim() {
  return useMutation(api.mutations.PrepTask_claim);
}

/** Mutation hook for PrepTask.complete. */
export function usePrepTaskComplete() {
  return useMutation(api.mutations.PrepTask_complete);
}

/** Mutation hook for PrepTask.markBlocked. */
export function usePrepTaskMarkBlocked() {
  return useMutation(api.mutations.PrepTask_markBlocked);
}

/** Mutation hook for PrepTask.open. */
export function usePrepTaskOpen() {
  return useMutation(api.mutations.PrepTask_open);
}

/** Mutation hook for PrepTask.release. */
export function usePrepTaskRelease() {
  return useMutation(api.mutations.PrepTask_release);
}

/** Mutation hook for PrepTask.start. */
export function usePrepTaskStart() {
  return useMutation(api.mutations.PrepTask_start);
}

/** Mutation hook for PrepTask.unblock. */
export function usePrepTaskUnblock() {
  return useMutation(api.mutations.PrepTask_unblock);
}

/** Governed creation hook for PrepTask.open. */
export function useCreatePrepTask() {
  return useMutation(api.mutations.PrepTask_createViaOpen);
}

/** Reactive list for ProductionBatch. */
export function useListProductionBatch() {
  return useQuery(api.queries.listProductionBatch);
}

/** Reactive get-by-id for ProductionBatch. Pass "skip" to suspend. */
export function useGetProductionBatch(id: string | "skip") {
  return useQuery(api.queries.getProductionBatch, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for ProductionBatch.cancel. */
export function useProductionBatchCancel() {
  return useMutation(api.mutations.ProductionBatch_cancel);
}

/** Mutation hook for ProductionBatch.complete. */
export function useProductionBatchComplete() {
  return useMutation(api.mutations.ProductionBatch_complete);
}

/** Mutation hook for ProductionBatch.plan. */
export function useProductionBatchPlan() {
  return useMutation(api.mutations.ProductionBatch_plan);
}

/** Mutation hook for ProductionBatch.start. */
export function useProductionBatchStart() {
  return useMutation(api.mutations.ProductionBatch_start);
}

/** Governed creation hook for ProductionBatch.plan. */
export function useCreateProductionBatch() {
  return useMutation(api.mutations.ProductionBatch_createViaPlan);
}

/** Reactive list for Proposal. */
export function useListProposal() {
  return useQuery(api.queries.listProposal);
}

/** Reactive get-by-id for Proposal. Pass "skip" to suspend. */
export function useGetProposal(id: string | "skip") {
  return useQuery(api.queries.getProposal, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for Proposal.accept. */
export function useProposalAccept() {
  return useMutation(api.mutations.Proposal_accept);
}

/** Mutation hook for Proposal.decline. */
export function useProposalDecline() {
  return useMutation(api.mutations.Proposal_decline);
}

/** Mutation hook for Proposal.draft. */
export function useProposalDraft() {
  return useMutation(api.mutations.Proposal_draft);
}

/** Mutation hook for Proposal.expire. */
export function useProposalExpire() {
  return useMutation(api.mutations.Proposal_expire);
}

/** Mutation hook for Proposal.markViewed. */
export function useProposalMarkViewed() {
  return useMutation(api.mutations.Proposal_markViewed);
}

/** Mutation hook for Proposal.send. */
export function useProposalSend() {
  return useMutation(api.mutations.Proposal_send);
}

/** Governed creation hook for Proposal.draft. */
export function useCreateProposal() {
  return useMutation(api.mutations.Proposal_createViaDraft);
}

/** Reactive list for PurchaseNeed. */
export function useListPurchaseNeed() {
  return useQuery(api.queries.listPurchaseNeed);
}

/** Reactive get-by-id for PurchaseNeed. Pass "skip" to suspend. */
export function useGetPurchaseNeed(id: string | "skip") {
  return useQuery(api.queries.getPurchaseNeed, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for PurchaseNeed.cancel. */
export function usePurchaseNeedCancel() {
  return useMutation(api.mutations.PurchaseNeed_cancel);
}

/** Mutation hook for PurchaseNeed.create. */
export function usePurchaseNeedCreate() {
  return useMutation(api.mutations.PurchaseNeed_create);
}

/** Mutation hook for PurchaseNeed.markFulfilled. */
export function usePurchaseNeedMarkFulfilled() {
  return useMutation(api.mutations.PurchaseNeed_markFulfilled);
}

/** Mutation hook for PurchaseNeed.markOrdered. */
export function usePurchaseNeedMarkOrdered() {
  return useMutation(api.mutations.PurchaseNeed_markOrdered);
}

/** Reactive list for Qualification. */
export function useListQualification() {
  return useQuery(api.queries.listQualification);
}

/** Reactive get-by-id for Qualification. Pass "skip" to suspend. */
export function useGetQualification(id: string | "skip") {
  return useQuery(api.queries.getQualification, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for Qualification.expire. */
export function useQualificationExpire() {
  return useMutation(api.mutations.Qualification_expire);
}

/** Mutation hook for Qualification.grant. */
export function useQualificationGrant() {
  return useMutation(api.mutations.Qualification_grant);
}

/** Mutation hook for Qualification.revoke. */
export function useQualificationRevoke() {
  return useMutation(api.mutations.Qualification_revoke);
}

/** Governed creation hook for Qualification.grant. */
export function useCreateQualification() {
  return useMutation(api.mutations.Qualification_createViaGrant);
}

/** Reactive list for QualityCheck. */
export function useListQualityCheck() {
  return useQuery(api.queries.listQualityCheck);
}

/** Reactive get-by-id for QualityCheck. Pass "skip" to suspend. */
export function useGetQualityCheck(id: string | "skip") {
  return useQuery(api.queries.getQualityCheck, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for QualityCheck.fail. */
export function useQualityCheckFail() {
  return useMutation(api.mutations.QualityCheck_fail);
}

/** Mutation hook for QualityCheck.open. */
export function useQualityCheckOpen() {
  return useMutation(api.mutations.QualityCheck_open);
}

/** Mutation hook for QualityCheck.pass. */
export function useQualityCheckPass() {
  return useMutation(api.mutations.QualityCheck_pass);
}

/** Mutation hook for QualityCheck.reinspect. */
export function useQualityCheckReinspect() {
  return useMutation(api.mutations.QualityCheck_reinspect);
}

/** Governed creation hook for QualityCheck.open. */
export function useCreateQualityCheck() {
  return useMutation(api.mutations.QualityCheck_createViaOpen);
}

/** Reactive list for Recipe. */
export function useListRecipe() {
  return useQuery(api.queries.listRecipe);
}

/** Reactive get-by-id for Recipe. Pass "skip" to suspend. */
export function useGetRecipe(id: string | "skip") {
  return useQuery(api.queries.getRecipe, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for Recipe.draft. */
export function useRecipeDraft() {
  return useMutation(api.mutations.Recipe_draft);
}

/** Mutation hook for Recipe.publishVersion. */
export function useRecipePublishVersion() {
  return useMutation(api.mutations.Recipe_publishVersion);
}

/** Mutation hook for Recipe.retire. */
export function useRecipeRetire() {
  return useMutation(api.mutations.Recipe_retire);
}

/** Mutation hook for Recipe.retract. */
export function useRecipeRetract() {
  return useMutation(api.mutations.Recipe_retract);
}

/** Mutation hook for Recipe.reviseDraft. */
export function useRecipeReviseDraft() {
  return useMutation(api.mutations.Recipe_reviseDraft);
}

/** Governed creation hook for Recipe.draft. */
export function useCreateRecipe() {
  return useMutation(api.mutations.Recipe_createViaDraft);
}

/** Reactive list for RecipeImport. */
export function useListRecipeImport() {
  return useQuery(api.queries.listRecipeImport);
}

/** Reactive get-by-id for RecipeImport. Pass "skip" to suspend. */
export function useGetRecipeImport(id: string | "skip") {
  return useQuery(api.queries.getRecipeImport, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for RecipeImport.approveReview. */
export function useRecipeImportApproveReview() {
  return useMutation(api.mutations.RecipeImport_approveReview);
}

/** Mutation hook for RecipeImport.beginFinalization. */
export function useRecipeImportBeginFinalization() {
  return useMutation(api.mutations.RecipeImport_beginFinalization);
}

/** Mutation hook for RecipeImport.beginReview. */
export function useRecipeImportBeginReview() {
  return useMutation(api.mutations.RecipeImport_beginReview);
}

/** Mutation hook for RecipeImport.cancel. */
export function useRecipeImportCancel() {
  return useMutation(api.mutations.RecipeImport_cancel);
}

/** Mutation hook for RecipeImport.complete. */
export function useRecipeImportComplete() {
  return useMutation(api.mutations.RecipeImport_complete);
}

/** Mutation hook for RecipeImport.markFailed. */
export function useRecipeImportMarkFailed() {
  return useMutation(api.mutations.RecipeImport_markFailed);
}

/** Mutation hook for RecipeImport.recordParse. */
export function useRecipeImportRecordParse() {
  return useMutation(api.mutations.RecipeImport_recordParse);
}

/** Mutation hook for RecipeImport.recordRecipe. */
export function useRecipeImportRecordRecipe() {
  return useMutation(api.mutations.RecipeImport_recordRecipe);
}

/** Mutation hook for RecipeImport.recordResolutionProgress. */
export function useRecipeImportRecordResolutionProgress() {
  return useMutation(api.mutations.RecipeImport_recordResolutionProgress);
}

/** Mutation hook for RecipeImport.resumeReview. */
export function useRecipeImportResumeReview() {
  return useMutation(api.mutations.RecipeImport_resumeReview);
}

/** Mutation hook for RecipeImport.upload. */
export function useRecipeImportUpload() {
  return useMutation(api.mutations.RecipeImport_upload);
}

/** Governed creation hook for RecipeImport.upload. */
export function useCreateRecipeImport() {
  return useMutation(api.mutations.RecipeImport_createViaUpload);
}

/** Reactive list for RecipeImportLine. */
export function useListRecipeImportLine() {
  return useQuery(api.queries.listRecipeImportLine);
}

/** Reactive get-by-id for RecipeImportLine. Pass "skip" to suspend. */
export function useGetRecipeImportLine(id: string | "skip") {
  return useQuery(api.queries.getRecipeImportLine, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for RecipeImportLine.attachCreatedIngredient. */
export function useRecipeImportLineAttachCreatedIngredient() {
  return useMutation(api.mutations.RecipeImportLine_attachCreatedIngredient);
}

/** Mutation hook for RecipeImportLine.confirmExisting. */
export function useRecipeImportLineConfirmExisting() {
  return useMutation(api.mutations.RecipeImportLine_confirmExisting);
}

/** Mutation hook for RecipeImportLine.confirmNew. */
export function useRecipeImportLineConfirmNew() {
  return useMutation(api.mutations.RecipeImportLine_confirmNew);
}

/** Mutation hook for RecipeImportLine.discard. */
export function useRecipeImportLineDiscard() {
  return useMutation(api.mutations.RecipeImportLine_discard);
}

/** Mutation hook for RecipeImportLine.markNew. */
export function useRecipeImportLineMarkNew() {
  return useMutation(api.mutations.RecipeImportLine_markNew);
}

/** Mutation hook for RecipeImportLine.resetResolution. */
export function useRecipeImportLineResetResolution() {
  return useMutation(api.mutations.RecipeImportLine_resetResolution);
}

/** Mutation hook for RecipeImportLine.stage. */
export function useRecipeImportLineStage() {
  return useMutation(api.mutations.RecipeImportLine_stage);
}

/** Mutation hook for RecipeImportLine.suggestExactMatch. */
export function useRecipeImportLineSuggestExactMatch() {
  return useMutation(api.mutations.RecipeImportLine_suggestExactMatch);
}

/** Mutation hook for RecipeImportLine.suggestPossibleMatches. */
export function useRecipeImportLineSuggestPossibleMatches() {
  return useMutation(api.mutations.RecipeImportLine_suggestPossibleMatches);
}

/** Governed creation hook for RecipeImportLine.stage. */
export function useCreateRecipeImportLine() {
  return useMutation(api.mutations.RecipeImportLine_createViaStage);
}

/** Reactive list for RecipeIngredient. */
export function useListRecipeIngredient() {
  return useQuery(api.queries.listRecipeIngredient);
}

/** Reactive get-by-id for RecipeIngredient. Pass "skip" to suspend. */
export function useGetRecipeIngredient(id: string | "skip") {
  return useQuery(api.queries.getRecipeIngredient, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for RecipeIngredient.add. */
export function useRecipeIngredientAdd() {
  return useMutation(api.mutations.RecipeIngredient_add);
}

/** Mutation hook for RecipeIngredient.adjustQuantity. */
export function useRecipeIngredientAdjustQuantity() {
  return useMutation(api.mutations.RecipeIngredient_adjustQuantity);
}

/** Mutation hook for RecipeIngredient.remove. */
export function useRecipeIngredientRemove() {
  return useMutation(api.mutations.RecipeIngredient_remove);
}

/** Governed creation hook for RecipeIngredient.add. */
export function useCreateRecipeIngredient() {
  return useMutation(api.mutations.RecipeIngredient_createViaAdd);
}

/** Reactive list for SavedReportDefinition. */
export function useListSavedReportDefinition() {
  return useQuery(api.queries.listSavedReportDefinition);
}

/** Reactive get-by-id for SavedReportDefinition. Pass "skip" to suspend. */
export function useGetSavedReportDefinition(id: string | "skip") {
  return useQuery(api.queries.getSavedReportDefinition, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for SavedReportDefinition.archive. */
export function useSavedReportDefinitionArchive() {
  return useMutation(api.mutations.SavedReportDefinition_archive);
}

/** Mutation hook for SavedReportDefinition.changeSharing. */
export function useSavedReportDefinitionChangeSharing() {
  return useMutation(api.mutations.SavedReportDefinition_changeSharing);
}

/** Mutation hook for SavedReportDefinition.createDefinition. */
export function useSavedReportDefinitionCreateDefinition() {
  return useMutation(api.mutations.SavedReportDefinition_createDefinition);
}

/** Mutation hook for SavedReportDefinition.rename. */
export function useSavedReportDefinitionRename() {
  return useMutation(api.mutations.SavedReportDefinition_rename);
}

/** Mutation hook for SavedReportDefinition.restore. */
export function useSavedReportDefinitionRestore() {
  return useMutation(api.mutations.SavedReportDefinition_restore);
}

/** Mutation hook for SavedReportDefinition.updateDefinition. */
export function useSavedReportDefinitionUpdateDefinition() {
  return useMutation(api.mutations.SavedReportDefinition_updateDefinition);
}

/** Governed creation hook for SavedReportDefinition.createDefinition. */
export function useCreateSavedReportDefinition() {
  return useMutation(api.mutations.SavedReportDefinition_createViaCreateDefinition);
}

/** Reactive list for Shift. */
export function useListShift() {
  return useQuery(api.queries.listShift);
}

/** Reactive get-by-id for Shift. Pass "skip" to suspend. */
export function useGetShift(id: string | "skip") {
  return useQuery(api.queries.getShift, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for Shift.cancel. */
export function useShiftCancel() {
  return useMutation(api.mutations.Shift_cancel);
}

/** Mutation hook for Shift.complete. */
export function useShiftComplete() {
  return useMutation(api.mutations.Shift_complete);
}

/** Mutation hook for Shift.markNoShow. */
export function useShiftMarkNoShow() {
  return useMutation(api.mutations.Shift_markNoShow);
}

/** Mutation hook for Shift.schedule. */
export function useShiftSchedule() {
  return useMutation(api.mutations.Shift_schedule);
}

/** Mutation hook for Shift.start. */
export function useShiftStart() {
  return useMutation(api.mutations.Shift_start);
}

/** Governed creation hook for Shift.schedule. */
export function useCreateShift() {
  return useMutation(api.mutations.Shift_createViaSchedule);
}

/** Reactive list for StorageLocation. */
export function useListStorageLocation() {
  return useQuery(api.queries.listStorageLocation);
}

/** Reactive get-by-id for StorageLocation. Pass "skip" to suspend. */
export function useGetStorageLocation(id: string | "skip") {
  return useQuery(api.queries.getStorageLocation, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for StorageLocation.activate. */
export function useStorageLocationActivate() {
  return useMutation(api.mutations.StorageLocation_activate);
}

/** Mutation hook for StorageLocation.deactivate. */
export function useStorageLocationDeactivate() {
  return useMutation(api.mutations.StorageLocation_deactivate);
}

/** Mutation hook for StorageLocation.register. */
export function useStorageLocationRegister() {
  return useMutation(api.mutations.StorageLocation_register);
}

/** Mutation hook for StorageLocation.reviseDetails. */
export function useStorageLocationReviseDetails() {
  return useMutation(api.mutations.StorageLocation_reviseDetails);
}

/** Governed creation hook for StorageLocation.register. */
export function useCreateStorageLocation() {
  return useMutation(api.mutations.StorageLocation_createViaRegister);
}

/** Reactive list for TimeRecord. */
export function useListTimeRecord() {
  return useQuery(api.queries.listTimeRecord);
}

/** Reactive get-by-id for TimeRecord. Pass "skip" to suspend. */
export function useGetTimeRecord(id: string | "skip") {
  return useQuery(api.queries.getTimeRecord, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for TimeRecord.clockIn. */
export function useTimeRecordClockIn() {
  return useMutation(api.mutations.TimeRecord_clockIn);
}

/** Mutation hook for TimeRecord.clockOut. */
export function useTimeRecordClockOut() {
  return useMutation(api.mutations.TimeRecord_clockOut);
}

/** Mutation hook for TimeRecord.correct. */
export function useTimeRecordCorrect() {
  return useMutation(api.mutations.TimeRecord_correct);
}

/** Governed creation hook for TimeRecord.clockIn. */
export function useCreateTimeRecord() {
  return useMutation(api.mutations.TimeRecord_createViaClockIn);
}

/** Reactive list for Vendor. */
export function useListVendor() {
  return useQuery(api.queries.listVendor);
}

/** Reactive get-by-id for Vendor. Pass "skip" to suspend. */
export function useGetVendor(id: string | "skip") {
  return useQuery(api.queries.getVendor, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for Vendor.onboard. */
export function useVendorOnboard() {
  return useMutation(api.mutations.Vendor_onboard);
}

/** Mutation hook for Vendor.reinstate. */
export function useVendorReinstate() {
  return useMutation(api.mutations.Vendor_reinstate);
}

/** Mutation hook for Vendor.suspend. */
export function useVendorSuspend() {
  return useMutation(api.mutations.Vendor_suspend);
}

/** Mutation hook for Vendor.terminate. */
export function useVendorTerminate() {
  return useMutation(api.mutations.Vendor_terminate);
}

/** Mutation hook for Vendor.updateDetails. */
export function useVendorUpdateDetails() {
  return useMutation(api.mutations.Vendor_updateDetails);
}

/** Governed creation hook for Vendor.onboard. */
export function useCreateVendor() {
  return useMutation(api.mutations.Vendor_createViaOnboard);
}

/** Reactive list for VendorOrder. */
export function useListVendorOrder() {
  return useQuery(api.queries.listVendorOrder);
}

/** Reactive get-by-id for VendorOrder. Pass "skip" to suspend. */
export function useGetVendorOrder(id: string | "skip") {
  return useQuery(api.queries.getVendorOrder, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for VendorOrder.cancel. */
export function useVendorOrderCancel() {
  return useMutation(api.mutations.VendorOrder_cancel);
}

/** Mutation hook for VendorOrder.confirm. */
export function useVendorOrderConfirm() {
  return useMutation(api.mutations.VendorOrder_confirm);
}

/** Mutation hook for VendorOrder.markPartiallyReceived. */
export function useVendorOrderMarkPartiallyReceived() {
  return useMutation(api.mutations.VendorOrder_markPartiallyReceived);
}

/** Mutation hook for VendorOrder.markReceived. */
export function useVendorOrderMarkReceived() {
  return useMutation(api.mutations.VendorOrder_markReceived);
}

/** Mutation hook for VendorOrder.open. */
export function useVendorOrderOpen() {
  return useMutation(api.mutations.VendorOrder_open);
}

/** Mutation hook for VendorOrder.submit. */
export function useVendorOrderSubmit() {
  return useMutation(api.mutations.VendorOrder_submit);
}

/** Mutation hook for VendorOrder.updateTotals. */
export function useVendorOrderUpdateTotals() {
  return useMutation(api.mutations.VendorOrder_updateTotals);
}

/** Governed creation hook for VendorOrder.open. */
export function useCreateVendorOrder() {
  return useMutation(api.mutations.VendorOrder_createViaOpen);
}

/** Reactive list for VendorOrderLine. */
export function useListVendorOrderLine() {
  return useQuery(api.queries.listVendorOrderLine);
}

/** Reactive get-by-id for VendorOrderLine. Pass "skip" to suspend. */
export function useGetVendorOrderLine(id: string | "skip") {
  return useQuery(api.queries.getVendorOrderLine, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for VendorOrderLine.addLine. */
export function useVendorOrderLineAddLine() {
  return useMutation(api.mutations.VendorOrderLine_addLine);
}

/** Mutation hook for VendorOrderLine.cancelLine. */
export function useVendorOrderLineCancelLine() {
  return useMutation(api.mutations.VendorOrderLine_cancelLine);
}

/** Mutation hook for VendorOrderLine.recordReceipt. */
export function useVendorOrderLineRecordReceipt() {
  return useMutation(api.mutations.VendorOrderLine_recordReceipt);
}

/** Governed creation hook for VendorOrderLine.addLine. */
export function useCreateVendorOrderLine() {
  return useMutation(api.mutations.VendorOrderLine_createViaAddLine);
}

/** Reactive list for Venue. */
export function useListVenue() {
  return useQuery(api.queries.listVenue);
}

/** Reactive get-by-id for Venue. Pass "skip" to suspend. */
export function useGetVenue(id: string | "skip") {
  return useQuery(api.queries.getVenue, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for Venue.activate. */
export function useVenueActivate() {
  return useMutation(api.mutations.Venue_activate);
}

/** Mutation hook for Venue.changeCapacity. */
export function useVenueChangeCapacity() {
  return useMutation(api.mutations.Venue_changeCapacity);
}

/** Mutation hook for Venue.deactivate. */
export function useVenueDeactivate() {
  return useMutation(api.mutations.Venue_deactivate);
}

/** Mutation hook for Venue.register. */
export function useVenueRegister() {
  return useMutation(api.mutations.Venue_register);
}

/** Mutation hook for Venue.updateDetails. */
export function useVenueUpdateDetails() {
  return useMutation(api.mutations.Venue_updateDetails);
}

/** Governed creation hook for Venue.register. */
export function useCreateVenue() {
  return useMutation(api.mutations.Venue_createViaRegister);
}

/** Reactive list for WasteRecord. */
export function useListWasteRecord() {
  return useQuery(api.queries.listWasteRecord);
}

/** Reactive get-by-id for WasteRecord. Pass "skip" to suspend. */
export function useGetWasteRecord(id: string | "skip") {
  return useQuery(api.queries.getWasteRecord, id === "skip" ? "skip" : { id: id as any });
}

/** Mutation hook for WasteRecord.record. */
export function useWasteRecordRecord() {
  return useMutation(api.mutations.WasteRecord_record);
}

/** Mutation hook for WasteRecord.voidRecord. */
export function useWasteRecordVoidRecord() {
  return useMutation(api.mutations.WasteRecord_voidRecord);
}

/** Governed creation hook for WasteRecord.record. */
export function useCreateWasteRecord() {
  return useMutation(api.mutations.WasteRecord_createViaRecord);
}

export const MANIFEST_CONVEX_REACT_HOOK_COUNT = 373 as const;
