import { convexTest } from "convex-test";
import { beforeAll, describe, expect, it } from "vitest";
import { api } from "../../convex/_generated/api";
import schema from "../../convex/schema";
import { createManifestTestContext } from "@angriff36/manifest/proof-kit/convex-test";
import { modules } from "./convex-test-modules";
import {
  buildStoredZip,
  buildStyledWorkbook,
  bytesOf,
  sha256Hex,
} from "./zipFixture";
import {
  buildWorkbookProvenance,
  PROVENANCE_BYTE_BUDGET,
} from "../../src/lib/tppReports/workbookProvenance";

/**
 * Runtime proof AC-022 (PR01-03): an authorized operator can inspect, from
 * the import record, the preserved original (storage id + checksum),
 * workbook/sheet/cell coordinates, raw text/value, date system, parser
 * version, and the normalized result — raw evidence separate from the
 * interpreted value. Fixtures are synthetic workbooks shaped like TPP
 * exports, never the private archive.
 */

function harness() {
  return createManifestTestContext({
    convexTest: convexTest as never,
    schema,
    modules,
  });
}

beforeAll(() => {
  if (!process.env.CONVEX_FIELD_ENCRYPTION_KEY) {
    process.env.CONVEX_FIELD_ENCRYPTION_KEY =
      "A1MKNFPVRhFaPf83T45BwooVzAogtiphQhYraAD5gqU=";
  }
});

type Actor = ReturnType<ReturnType<typeof harness>["asRole"]>;

type ActionRunner = {
  action: (fn: unknown, args?: unknown) => Promise<unknown>;
};
function asActions(actor: Actor): ActionRunner {
  return actor as unknown as ActionRunner;
}

interface ArtifactRow {
  _id: string;
  name: string;
  disposition: string;
  parseStatus: string;
  checksum: string | null;
  storageId: string | null;
  provenance: string;
}

interface ProvenanceCell {
  ref: string;
  raw: string;
  outcome: string;
  value?: string | number | boolean;
  unit: string | null;
  formula?: string;
  dateSystem?: string;
  mergedRange?: string;
}

// A BEO-shaped workbook exercising the provenance spine: a merged title, a
// date serial under a date format, a unit-bearing format, hand-typed
// accounting parentheses, and a formula whose cached value is read (never
// executed).
const BEO_CELLS = [
  { ref: "A1", is: "Banquet Event Order" },
  { ref: "A3", is: "Event Date:" },
  { ref: "B3", v: "44927", s: 0 },
  { ref: "A4", is: "Guarantee:" },
  { ref: "B4", v: "75", s: 1 },
  { ref: "A5", is: "Balance Due:" },
  { ref: "B5", is: "(1,234.50)" },
  { ref: "A6", is: "Setup Hours:" },
  { ref: "B6", v: "2", s: 2 },
  { ref: "A7", is: "Staff Count:" },
  { ref: "B7", f: "B4/25", v: "3" },
];

const beoWorkbook = buildStyledWorkbook({
  sheetName: "BEO",
  numFmts: [
    { id: 164, code: "m/d/yyyy" },
    { id: 165, code: `0" hrs"` },
  ],
  xfNumFmtIds: [164, 2, 165],
  cells: BEO_CELLS,
  merges: ["A1:C1"],
});

describe("runtime proof: import provenance (AC-022)", () => {
  it("source provenance is inspectable from the import record", async () => {
    const tenantId = "tenant-import-provenance";
    const proof = harness();
    const owner = proof.asRole({
      subject: "import-provenance-owner",
      role: "owner",
      tenantId,
    });

    const archive = buildStoredZip([
      { name: "beo.xlsx", data: Array.from(beoWorkbook) },
      { name: "broken.xlsx", data: bytesOf("this is not a zip") },
    ]);

    const storageId = (await owner.run(async (ctx) =>
      (
        ctx as unknown as {
          storage: { store: (blob: Blob) => Promise<string> };
        }
      ).storage.store(new Blob([archive])),
    )) as string;

    const started = (await owner.mutation(api.importCoordinator.startImport, {
      sourceSystem: "tpp_legacy",
      datasetType: "events",
    })) as { importRunId: string };
    const importRunId = started.importRunId;

    await asActions(owner).action(api.archiveInventory.inventoryArchive, {
      importRunId,
      storageId,
      indexReportNames: ["beo.xlsx", "broken.xlsx"],
    });

    // --- Provenance records for every inventoried workbook. ---
    const first = (await asActions(owner).action(
      api.archiveProvenance.recordArchiveProvenance,
      { importRunId },
    )) as { recorded: number; skipped: number };
    expect(first).toEqual({ recorded: 2, skipped: 0 });

    // --- The operator read path: the generated by-run artifact query. ---
    const readBack = (await owner.query(
      api.queries.listImportArtifactByImportRunId,
      { importRunId },
    )) as ArtifactRow[];
    expect(readBack).toHaveLength(2);
    const byName = new Map(readBack.map((row) => [row.name, row]));
    const beo = byName.get("beo.xlsx")!;
    const broken = byName.get("broken.xlsx")!;

    // Preserved original: the archive bytes live on the run's storage +
    // checksum; each artifact points into it by entry name and its own
    // checksum of the workbook's decompressed bytes.
    const run = (await owner.run(async (ctx) => ctx.db.get(importRunId))) as {
      archiveStorageId: string | null;
      archiveChecksum: string | null;
    };
    expect(run.archiveStorageId).toBe(storageId);
    expect(run.archiveChecksum).toBe(await sha256Hex(archive));
    expect(beo.checksum).toBe(await sha256Hex(beoWorkbook));

    // --- The provenance document: coordinates, raw, interpreted, systems. ---
    const provenance = JSON.parse(beo.provenance) as {
      archiveEntry: string;
      indexed: string;
      workbook: {
        parserVersion: string;
        dateSystem: string;
        timezone: string;
        timezoneAssumption: string;
        macros: string;
        sheetCount: number;
        cellCount: number;
        cellsTruncated: boolean;
        sheets: Array<{
          name: string;
          mergedRanges: string[];
          cells: ProvenanceCell[];
        }>;
      };
    };
    // Inventory's own provenance keys survive the merge.
    expect(provenance.archiveEntry).toBe("beo.xlsx");
    expect(provenance.indexed).toBe("in_both");

    expect(beo.parseStatus).toBe("parsed");
    expect(provenance.workbook.parserVersion).toBe("xlsx-interpreted-1");
    expect(provenance.workbook.dateSystem).toBe("1900");
    expect(provenance.workbook.timezone).toBe("naive-local");
    expect(provenance.workbook.timezoneAssumption).toContain("never converted");
    expect(provenance.workbook.macros).toBe("absent");
    expect(provenance.workbook.sheetCount).toBe(1);

    const sheet = provenance.workbook.sheets[0]!;
    expect(sheet.name).toBe("BEO");
    expect(sheet.mergedRanges).toEqual(["A1:C1"]);

    const cellAt = (ref: string) => {
      const cell = sheet.cells.find((entry) => entry.ref === ref);
      if (cell === undefined) throw new Error(`provenance has no cell ${ref}`);
      return cell;
    };

    // Raw serial preserved next to the interpreted date — evidence, not a
    // replacement.
    const printed = cellAt("B3");
    expect(printed).toMatchObject({
      raw: "44927",
      value: "2023-01-01",
      outcome: "date_1900",
      dateSystem: "1900",
    });
    expect(printed.raw).not.toBe(printed.value);

    // Units only from the cell's own format literal (issue #274).
    expect(cellAt("B4").unit).toBeNull();
    expect(cellAt("B6")).toMatchObject({ unit: "hrs" });

    // Accounting parentheses and fractions keep raw text + normalized value.
    expect(cellAt("B5")).toMatchObject({
      raw: "(1,234.50)",
      value: -1234.5,
      outcome: "accounting_negative",
    });

    // Formula recorded verbatim with its CACHED value — never executed.
    expect(cellAt("B7")).toMatchObject({
      outcome: "formula_cached_value",
      value: 3,
      formula: "B4/25",
    });

    // Merge coordinates ride the anchor cell.
    expect(cellAt("A1").mergedRange).toBe("A1:C1");

    // --- An unreadable container records a named error, not a blank. ---
    expect(broken.parseStatus).toBe("failed");
    const brokenProvenance = JSON.parse(broken.provenance) as {
      workbook: { parserVersion: string; error: string };
    };
    expect(brokenProvenance.workbook.parserVersion).toBe("xlsx-interpreted-1");
    expect(brokenProvenance.workbook.error).toContain("Not a ZIP container");

    // --- Re-running records nothing new (idempotent). ---
    const second = (await asActions(owner).action(
      api.archiveProvenance.recordArchiveProvenance,
      { importRunId },
    )) as { recorded: number; skipped: number };
    expect(second).toEqual({ recorded: 0, skipped: 2 });

    // --- Order independence: classification after provenance keeps it. ---
    const classified = (await asActions(owner).action(
      api.archiveDisposition.classifyArchiveWorkbooks,
      { importRunId },
    )) as { classified: number };
    expect(classified.classified).toBe(2);
    const afterClassify = (await owner.query(
      api.queries.listImportArtifactByImportRunId,
      { importRunId },
    )) as ArtifactRow[];
    const beoAfter = afterClassify.find((row) => row.name === "beo.xlsx")!;
    expect(beoAfter.disposition).toBe("normalized");
    const provenanceAfter = JSON.parse(beoAfter.provenance) as {
      workbook: { parserVersion: string };
    };
    expect(provenanceAfter.workbook.parserVersion).toBe("xlsx-interpreted-1");

    // --- Authorization: a role without importAccess sees nothing and
    // cannot record; the operator still can. ---
    const staff = proof.asRole({
      subject: "import-provenance-staff",
      role: "sales_staff",
      tenantId,
    });
    const staffView = (await staff.query(
      api.queries.listImportArtifactByImportRunId,
      { importRunId },
    )) as ArtifactRow[];
    expect(staffView).toEqual([]);
    await expect(
      asActions(staff).action(api.archiveProvenance.recordArchiveProvenance, {
        importRunId,
      }),
    ).rejects.toThrow(/managers/i);
    const ownerStill = (await owner.query(
      api.queries.listImportArtifactByImportRunId,
      { importRunId },
    )) as ArtifactRow[];
    expect(ownerStill).toHaveLength(2);
  });

  it("provenance is byte-bounded: huge cell values truncate, never blow the document", () => {
    // Review R2-14: a cell-count cap cannot bound the persisted JSON — a
    // single legal cell can hold hundreds of kilobytes, and Convex caps the
    // whole document at 1 MiB. The builder truncates values (marked) and
    // stops recording cells at a serialized-byte budget.
    // 32 KiB single value: over the per-field cap (fixture spreads cap out
    // below ~64 KiB), far above what one field should persist verbatim.
    const oneHuge = buildStyledWorkbook({
      cells: [{ ref: "A1", is: "Q".repeat(32 * 1024) }],
    });
    const single = buildWorkbookProvenance(Buffer.from(oneHuge));
    expect(single.byteBudget).toBe(PROVENANCE_BYTE_BUDGET);
    expect(JSON.stringify(single).length).toBeLessThan(64 * 1024);
    const cell = single.sheets[0].cells[0];
    expect(cell.truncated).toBe(true);
    expect(cell.raw.endsWith("…[truncated]")).toBe(true);
    expect(cell.raw.length).toBeLessThanOrEqual(2200);

    const manyBig = buildStyledWorkbook({
      cells: Array.from({ length: 200 }, (_, i) => ({
        ref: `A${i + 1}`,
        is: "z".repeat(8 * 1024),
      })),
    });
    const capped = buildWorkbookProvenance(Buffer.from(manyBig));
    expect(capped.cellCount).toBe(200);
    expect(capped.cellsTruncated).toBe(true);
    const recorded = capped.sheets.reduce(
      (sum, sheet) => sum + sheet.cells.length,
      0,
    );
    expect(recorded).toBeGreaterThan(0);
    expect(recorded).toBeLessThan(200);
    expect(JSON.stringify(capped).length).toBeLessThan(
      PROVENANCE_BYTE_BUDGET + 4096,
    );

    // Merge-heavy sheets are bounded too (review round 2): ranges share the
    // byte budget and stop at a count cap, flagged in the document.
    const mergeHeavy = buildStyledWorkbook({
      cells: [{ ref: "A1", is: "merge title" }],
      merges: Array.from({ length: 5000 }, (_, i) => `A${i + 1}:C${i + 1}`),
    });
    const mergeCapped = buildWorkbookProvenance(Buffer.from(mergeHeavy));
    expect(mergeCapped.mergedRangesTruncated).toBe(true);
    expect(mergeCapped.sheets[0].mergedRanges.length).toBeLessThanOrEqual(256);
    expect(JSON.stringify(mergeCapped).length).toBeLessThan(
      PROVENANCE_BYTE_BUDGET + 4096,
    );
  });
});
