// GENERATED by the Manifest → Convex projection. DO NOT EDIT.
// Computed property helpers (14 entit(y/ies)).
// Call from queries/mutations or app code; never stored.

import type { Doc } from "./_generated/dataModel";

/** Self-only computed fields for Client. Pass the stored document. */
export function computeClient(doc: Record<string, any>): Record<string, any> {
  return {
    displayName: ((doc.clientType === "company") ? doc.companyName : ((doc.givenName + " ") + doc.familyName)),
    isArchived: (doc.status === "archived"),
  };
}

/** Self-only computed fields for Dish. Pass the stored document. */
export function computeDish(doc: Record<string, any>): Record<string, any> {
  return {
    isActive: (doc.status === "active"),
    isRetired: (doc.status === "retired"),
  };
}

/** Self-only computed fields for Event. Pass the stored document. */
export function computeEvent(doc: Record<string, any>): Record<string, any> {
  return {
    isTerminal: ((doc.stage === "cancelled") || (doc.stage === "closed_out")),
    isEditable: (((doc.stage === "planning") || (doc.stage === "pending_approval")) || (doc.stage === "approved")),
    isReadyForExecution: (((((doc.prepTasks) ?? []).filter((t: Doc<"prepTasks">) => (((t.status !== "completed") && (t.status !== "cancelled")))).length === 0) && (((doc.packLists) ?? []).filter((p: Doc<"packLists">) => (((p.status !== "dispatched") && (p.status !== "cancelled")))).length === 0)) && (((doc.deliveries) ?? []).filter((d: Doc<"deliveries">) => ((((d.status !== "delivered") && (d.status !== "cancelled")) && (d.status !== "failed")))).length === 0)),
  };
}

/** Self-only computed fields for EventGuest. Pass the stored document. */
export function computeEventGuest(doc: Record<string, any>): Record<string, any> {
  return {
    isCheckedIn: (doc.checkedInAt != null),
  };
}

/** Self-only computed fields for Ingredient. Pass the stored document. */
export function computeIngredient(doc: Record<string, any>): Record<string, any> {
  return {
    isActive: (doc.status === "active"),
    isDiscontinued: (doc.status === "discontinued"),
  };
}

/** Self-only computed fields for InventoryItem. Pass the stored document. */
export function computeInventoryItem(doc: Record<string, any>): Record<string, any> {
  return {
    isBelowPar: ((doc.parLevel > 0) && (doc.quantityOnHand < doc.parLevel)),
    isBelowReorder: ((doc.reorderThreshold > 0) && (doc.quantityOnHand < doc.reorderThreshold)),
    inventoryValue: (doc.quantityOnHand * doc.unitCost),
  };
}

/** Self-only computed fields for Menu. Pass the stored document. */
export function computeMenu(doc: Record<string, any>): Record<string, any> {
  return {
    isPublished: (doc.status === "published"),
    isEditable: (doc.status === "draft"),
  };
}

/** Self-only computed fields for Organization. Pass the stored document. */
export function computeOrganization(doc: Record<string, any>): Record<string, any> {
  return {
    isOperable: ((doc.status === "active") && (doc.deletedAt == null)),
  };
}

/** Self-only computed fields for Person. Pass the stored document. */
export function computePerson(doc: Record<string, any>): Record<string, any> {
  return {
    displayName: ((doc.givenName + " ") + doc.familyName),
    isAssignable: ((doc.status === "active") && (doc.deletedAt == null)),
  };
}

/** Self-only computed fields for Recipe. Pass the stored document. */
export function computeRecipe(doc: Record<string, any>): Record<string, any> {
  return {
    isPublished: (doc.status === "published"),
    isEditable: (doc.status === "draft"),
  };
}

/** Self-only computed fields for StorageLocation. Pass the stored document. */
export function computeStorageLocation(doc: Record<string, any>): Record<string, any> {
  return {
    isActive: (doc.status === "active"),
  };
}

/** Self-only computed fields for VendorOrderLine. Pass the stored document. */
export function computeVendorOrderLine(doc: Record<string, any>): Record<string, any> {
  return {
    lineTotal: (doc.orderedQuantity * doc.unitCost),
    remainingQuantity: (doc.orderedQuantity - doc.receivedQuantity),
  };
}

/** Self-only computed fields for Venue. Pass the stored document. */
export function computeVenue(doc: Record<string, any>): Record<string, any> {
  return {
    isActive: (doc.status === "active"),
  };
}

/** Self-only computed fields for WasteRecord. Pass the stored document. */
export function computeWasteRecord(doc: Record<string, any>): Record<string, any> {
  return {
    costImpact: (doc.quantity * doc.unitCost),
  };
}
