// GENERATED by the Manifest → Convex projection. DO NOT EDIT.
// Computed property helpers (23 entit(y/ies)).
// Call from queries/mutations or app code; never stored.

import type { Doc } from "./_generated/dataModel";

/** Computed fields for Client. Pass the stored (and hydrated) document. */
export function computeClient(doc: Record<string, any>): Record<string, any> {
  const __displayName = ((doc.clientType === "company") ? doc.companyName : ((doc.givenName + " ") + doc.familyName));
  doc.displayName = __displayName;
  const __isArchived = (doc.status === "archived");
  doc.isArchived = __isArchived;
  return {
    displayName: __displayName,
    isArchived: __isArchived,
  };
}

/** Computed fields for Dish. Pass the stored (and hydrated) document. */
export function computeDish(doc: Record<string, any>): Record<string, any> {
  const __isActive = (doc.status === "active");
  doc.isActive = __isActive;
  const __isRetired = (doc.status === "retired");
  doc.isRetired = __isRetired;
  return {
    isActive: __isActive,
    isRetired: __isRetired,
  };
}

/** Computed fields for Equipment. Pass the stored (and hydrated) document. */
export function computeEquipment(doc: Record<string, any>): Record<string, any> {
  const __isActive = (doc.status === "active");
  doc.isActive = __isActive;
  const __totalValue = (doc.quantity * doc.purchaseValue);
  doc.totalValue = __totalValue;
  return {
    isActive: __isActive,
    totalValue: __totalValue,
  };
}

/** Preload nested relations for Event computeds (mutates doc in place). */
export async function hydrateComputedRelationsForEvent(ctx: any, doc: Record<string, any>): Promise<void> {
  const docId = doc._id;
  {
    const __fk = ((doc as any) as any).clientId;
    ((doc as any) as any).client = __fk != null ? await ctx.db.get(__fk as any) : null;
  }
  (doc as any).eventDishes = await ctx.db.query("eventDishes").withIndex("by_eventId", (q: any) => q.eq("eventId", docId)).collect();
  (doc as any).assignments = await ctx.db.query("eventAssignments").withIndex("by_eventId", (q: any) => q.eq("eventId", docId)).collect();
  (doc as any).prepTasks = await ctx.db.query("prepTasks").withIndex("by_eventId", (q: any) => q.eq("eventId", docId)).collect();
  (doc as any).packLists = await ctx.db.query("packLists").withIndex("by_eventId", (q: any) => q.eq("eventId", docId)).collect();
  (doc as any).deliveries = await ctx.db.query("deliveries").withIndex("by_eventId", (q: any) => q.eq("eventId", docId)).collect();
}

/** Computed fields for Event. Pass the stored (and hydrated) document. */
export function computeEvent(doc: Record<string, any>): Record<string, any> {
  const __isTerminal = ((doc.stage === "cancelled") || (doc.stage === "closed_out"));
  doc.isTerminal = __isTerminal;
  const __isEditable = (((doc.stage === "planning") || (doc.stage === "pending_approval")) || (doc.stage === "approved"));
  doc.isEditable = __isEditable;
  const __hasAssignedClient = ((doc.client != null) && (doc.client.deletedAt == null));
  doc.hasAssignedClient = __hasAssignedClient;
  const __hasExpectedHeadcount = (doc.expectedHeadcount > 0);
  doc.hasExpectedHeadcount = __hasExpectedHeadcount;
  const __hasMenuDishes = (((doc.eventDishes) ?? []).filter((d: Doc<"eventDishes">) => (((d.deletedAt == null) && (d.removedAt == null)))).length > 0);
  doc.hasMenuDishes = __hasMenuDishes;
  const __hasStaffAssigned = (((doc.assignments) ?? []).filter((a: Doc<"eventAssignments">) => (((a.deletedAt == null) && (a.status !== "unassigned")))).length > 0);
  doc.hasStaffAssigned = __hasStaffAssigned;
  const __isSetupReady = (((doc.hasAssignedClient && doc.hasExpectedHeadcount) && doc.hasMenuDishes) && doc.hasStaffAssigned);
  doc.isSetupReady = __isSetupReady;
  const __isReadyForExecution = (((((doc.prepTasks) ?? []).filter((t: Doc<"prepTasks">) => (((t.status !== "completed") && (t.status !== "cancelled")))).length === 0) && (((doc.packLists) ?? []).filter((p: Doc<"packLists">) => ((((p.status !== "dispatched") && (p.status !== "cancelled")) && (p.status !== "draft")))).length === 0)) && (((doc.deliveries) ?? []).filter((d: Doc<"deliveries">) => ((((d.status !== "delivered") && (d.status !== "cancelled")) && (d.status !== "failed")))).length === 0));
  doc.isReadyForExecution = __isReadyForExecution;
  const __estimatedFoodCost = ((((doc.eventDishes) ?? []).filter((item: Doc<"eventDishes">) => (((item.deletedAt == null) && (item.addedAt != null))))) ?? []).map((item: Record<string, any>) => (item.estimatedCost)).reduce((acc: number, v: unknown) => acc + (typeof v === "number" ? v : 0), 0);
  doc.estimatedFoodCost = __estimatedFoodCost;
  return {
    isTerminal: __isTerminal,
    isEditable: __isEditable,
    hasAssignedClient: __hasAssignedClient,
    hasExpectedHeadcount: __hasExpectedHeadcount,
    hasMenuDishes: __hasMenuDishes,
    hasStaffAssigned: __hasStaffAssigned,
    isSetupReady: __isSetupReady,
    isReadyForExecution: __isReadyForExecution,
    estimatedFoodCost: __estimatedFoodCost,
  };
}

/** Preload nested relations for EventDish computeds (mutates doc in place). */
export async function hydrateComputedRelationsForEventDish(ctx: any, doc: Record<string, any>): Promise<void> {
  const docId = doc._id;
  {
    const __fk = ((doc as any) as any).eventId;
    ((doc as any) as any).event = __fk != null ? await ctx.db.get(__fk as any) : null;
  }
  {
    const __fk = ((doc as any) as any).dishId;
    ((doc as any) as any).dish = __fk != null ? await ctx.db.get(__fk as any) : null;
  }
  if (((doc as any) as any).dish) {
    ((doc as any) as any).dish.recipeLines = await ctx.db.query("dishRecipes").withIndex("by_dishId", (q: any) => q.eq("dishId", ((doc as any) as any).dish._id)).collect();
    for (const __agg0 of (((doc as any) as any).dish.recipeLines ?? []) as any[]) {
      {
        const __fk = (__agg0 as any).recipeId;
        (__agg0 as any).recipe = __fk != null ? await ctx.db.get(__fk as any) : null;
      }
      if ((__agg0 as any).recipe) {
        (__agg0 as any).recipe.ingredientLines = await ctx.db.query("recipeIngredients").withIndex("by_recipeId", (q: any) => q.eq("recipeId", (__agg0 as any).recipe._id)).collect();
        for (const __agg1 of ((__agg0 as any).recipe.ingredientLines ?? []) as any[]) {
          {
            const __fk = (__agg1 as any).ingredientId;
            (__agg1 as any).ingredient = __fk != null ? await ctx.db.get(__fk as any) : null;
          }
        }
      }
    }
  }
}

/** Computed fields for EventDish. Pass the stored (and hydrated) document. */
export function computeEventDish(doc: Record<string, any>): Record<string, any> {
  const __targetHeadcount = ((doc.headcountOverride > 0) ? doc.headcountOverride : doc.event.expectedHeadcount);
  doc.targetHeadcount = __targetHeadcount;
  const __requiredBatches = (() => { const __vals = ((((doc.dish.recipeLines) ?? []).filter((line: Record<string, any>) => (((line.deletedAt == null) && (line.attachedAt != null))))) ?? []).map((line: Record<string, any>) => (((line.recipe.servesPerYield > 0) ? Math.ceil((doc.targetHeadcount / line.recipe.servesPerYield)) : 0))).filter((v: unknown): v is number => typeof v === "number"); return __vals.length === 0 ? undefined : Math.max(...__vals); })();
  doc.requiredBatches = __requiredBatches;
  const __requiredYieldQuantity = (() => { const __vals = ((((doc.dish.recipeLines) ?? []).filter((line: Record<string, any>) => (((line.deletedAt == null) && (line.attachedAt != null))))) ?? []).map((line: Record<string, any>) => ((((line.recipe.servesPerYield > 0) ? Math.ceil((doc.targetHeadcount / line.recipe.servesPerYield)) : 0) * line.recipe.yieldQuantity))).filter((v: unknown): v is number => typeof v === "number"); return __vals.length === 0 ? undefined : Math.max(...__vals); })();
  doc.requiredYieldQuantity = __requiredYieldQuantity;
  const __estimatedCost = ((((doc.dish.recipeLines) ?? []).filter((line: Record<string, any>) => (((line.deletedAt == null) && (line.attachedAt != null))))) ?? []).map((line: Record<string, any>) => ((((line.recipe.servesPerYield > 0) ? Math.ceil((doc.targetHeadcount / line.recipe.servesPerYield)) : 0) * ((((line.recipe.ingredientLines) ?? []).filter((il: Record<string, any>) => (((il.deletedAt == null) && (il.addedAt != null))))) ?? []).map((il: Record<string, any>) => (((il.unit === il.ingredient.unit) ? ((il.quantity * il.wasteFactor) * il.ingredient.costPerUnit) : 0))).reduce((acc: number, v: unknown) => acc + (typeof v === "number" ? v : 0), 0)))).reduce((acc: number, v: unknown) => acc + (typeof v === "number" ? v : 0), 0);
  doc.estimatedCost = __estimatedCost;
  return {
    targetHeadcount: __targetHeadcount,
    requiredBatches: __requiredBatches,
    requiredYieldQuantity: __requiredYieldQuantity,
    estimatedCost: __estimatedCost,
  };
}

/** Computed fields for EventGuest. Pass the stored (and hydrated) document. */
export function computeEventGuest(doc: Record<string, any>): Record<string, any> {
  const __isCheckedIn = (doc.checkedInAt != null);
  doc.isCheckedIn = __isCheckedIn;
  return {
    isCheckedIn: __isCheckedIn,
  };
}

/** Computed fields for EventTemplate. Pass the stored (and hydrated) document. */
export function computeEventTemplate(doc: Record<string, any>): Record<string, any> {
  const __isActive = (doc.status === "active");
  doc.isActive = __isActive;
  return {
    isActive: __isActive,
  };
}

/** Computed fields for Ingredient. Pass the stored (and hydrated) document. */
export function computeIngredient(doc: Record<string, any>): Record<string, any> {
  const __isActive = (doc.status === "active");
  doc.isActive = __isActive;
  const __isDiscontinued = (doc.status === "discontinued");
  doc.isDiscontinued = __isDiscontinued;
  return {
    isActive: __isActive,
    isDiscontinued: __isDiscontinued,
  };
}

/** Preload nested relations for InventoryItem computeds (mutates doc in place). */
export async function hydrateComputedRelationsForInventoryItem(ctx: any, doc: Record<string, any>): Promise<void> {
  const docId = doc._id;
  (doc as any).reservations = await ctx.db.query("inventoryReservations").withIndex("by_inventoryItemId", (q: any) => q.eq("inventoryItemId", docId)).collect();
}

/** Computed fields for InventoryItem. Pass the stored (and hydrated) document. */
export function computeInventoryItem(doc: Record<string, any>): Record<string, any> {
  const __isBelowPar = ((doc.parLevel > 0) && (doc.quantityOnHand < doc.parLevel));
  doc.isBelowPar = __isBelowPar;
  const __isBelowReorder = ((doc.reorderThreshold > 0) && (doc.quantityOnHand < doc.reorderThreshold));
  doc.isBelowReorder = __isBelowReorder;
  const __inventoryValue = (doc.quantityOnHand * doc.unitCost);
  doc.inventoryValue = __inventoryValue;
  const __totalReserved = ((doc.reservations) ?? []).map((r: Doc<"inventoryReservations">) => (((r.status === "active") ? r.quantity : 0))).reduce((acc: number, v: unknown) => acc + (typeof v === "number" ? v : 0), 0);
  doc.totalReserved = __totalReserved;
  const __availableQuantity = (doc.quantityOnHand - doc.totalReserved);
  doc.availableQuantity = __availableQuantity;
  return {
    isBelowPar: __isBelowPar,
    isBelowReorder: __isBelowReorder,
    inventoryValue: __inventoryValue,
    totalReserved: __totalReserved,
    availableQuantity: __availableQuantity,
  };
}

/** Computed fields for Invoice. Pass the stored (and hydrated) document. */
export function computeInvoice(doc: Record<string, any>): Record<string, any> {
  const __invoiceCurrencyCode = (((doc.currencyCode != null) && (((doc.currencyCode).trim()).length === 3)) ? doc.currencyCode : "USD");
  doc.invoiceCurrencyCode = __invoiceCurrencyCode;
  const __safeExchangeRate = (((doc.exchangeRate != null) && (doc.exchangeRate > 0)) ? doc.exchangeRate : 1);
  doc.safeExchangeRate = __safeExchangeRate;
  const __functionalCurrencyTotal = Math.round((doc.total * doc.safeExchangeRate));
  doc.functionalCurrencyTotal = __functionalCurrencyTotal;
  const __functionalCurrencyAmountDue = Math.round((doc.amountDue * doc.safeExchangeRate));
  doc.functionalCurrencyAmountDue = __functionalCurrencyAmountDue;
  return {
    invoiceCurrencyCode: __invoiceCurrencyCode,
    safeExchangeRate: __safeExchangeRate,
    functionalCurrencyTotal: __functionalCurrencyTotal,
    functionalCurrencyAmountDue: __functionalCurrencyAmountDue,
  };
}

/** Computed fields for Lead. Pass the stored (and hydrated) document. */
export function computeLead(doc: Record<string, any>): Record<string, any> {
  const __displayName = ((doc.leadType === "company") ? doc.companyName : ((doc.givenName + " ") + doc.familyName));
  doc.displayName = __displayName;
  return {
    displayName: __displayName,
  };
}

/** Computed fields for Menu. Pass the stored (and hydrated) document. */
export function computeMenu(doc: Record<string, any>): Record<string, any> {
  const __isPublished = (doc.status === "published");
  doc.isPublished = __isPublished;
  const __isEditable = (doc.status === "draft");
  doc.isEditable = __isEditable;
  return {
    isPublished: __isPublished,
    isEditable: __isEditable,
  };
}

/** Computed fields for Organization. Pass the stored (and hydrated) document. */
export function computeOrganization(doc: Record<string, any>): Record<string, any> {
  const __isOperable = ((doc.status === "active") && (doc.deletedAt == null));
  doc.isOperable = __isOperable;
  const __functionalCurrencyCode = (((doc.defaultCurrencyCode != null) && (((doc.defaultCurrencyCode).trim()).length === 3)) ? doc.defaultCurrencyCode : "USD");
  doc.functionalCurrencyCode = __functionalCurrencyCode;
  return {
    isOperable: __isOperable,
    functionalCurrencyCode: __functionalCurrencyCode,
  };
}

/** Computed fields for Person. Pass the stored (and hydrated) document. */
export function computePerson(doc: Record<string, any>): Record<string, any> {
  const __displayName = ((doc.givenName + " ") + doc.familyName);
  doc.displayName = __displayName;
  const __isAssignable = ((doc.status === "active") && (doc.deletedAt == null));
  doc.isAssignable = __isAssignable;
  return {
    displayName: __displayName,
    isAssignable: __isAssignable,
  };
}

/** Preload nested relations for Recipe computeds (mutates doc in place). */
export async function hydrateComputedRelationsForRecipe(ctx: any, doc: Record<string, any>): Promise<void> {
  const docId = doc._id;
  (doc as any).ingredientLines = await ctx.db.query("recipeIngredients").withIndex("by_recipeId", (q: any) => q.eq("recipeId", docId)).collect();
  for (const __agg0 of ((doc as any).ingredientLines ?? []) as any[]) {
    {
      const __fk = (__agg0 as any).ingredientId;
      (__agg0 as any).ingredient = __fk != null ? await ctx.db.get(__fk as any) : null;
    }
  }
}

/** Computed fields for Recipe. Pass the stored (and hydrated) document. */
export function computeRecipe(doc: Record<string, any>): Record<string, any> {
  const __isPublished = (doc.status === "published");
  doc.isPublished = __isPublished;
  const __isEditable = (doc.status === "draft");
  doc.isEditable = __isEditable;
  const __liveBatchCost = ((((doc.ingredientLines) ?? []).filter((line: Doc<"recipeIngredients">) => (((line.deletedAt == null) && (line.addedAt != null))))) ?? []).map((line: Record<string, any>) => (((line.unit === line.ingredient.unit) ? ((line.quantity * line.wasteFactor) * line.ingredient.costPerUnit) : 0))).reduce((acc: number, v: unknown) => acc + (typeof v === "number" ? v : 0), 0);
  doc.liveBatchCost = __liveBatchCost;
  const __liveCostPerGuest = ((doc.servesPerYield > 0) ? (((((doc.ingredientLines) ?? []).filter((line: Doc<"recipeIngredients">) => (((line.deletedAt == null) && (line.addedAt != null))))) ?? []).map((line: Record<string, any>) => (((line.unit === line.ingredient.unit) ? ((line.quantity * line.wasteFactor) * line.ingredient.costPerUnit) : 0))).reduce((acc: number, v: unknown) => acc + (typeof v === "number" ? v : 0), 0) / doc.servesPerYield) : 0);
  doc.liveCostPerGuest = __liveCostPerGuest;
  return {
    isPublished: __isPublished,
    isEditable: __isEditable,
    liveBatchCost: __liveBatchCost,
    liveCostPerGuest: __liveCostPerGuest,
  };
}

/** Preload nested relations for RecipeIngredient computeds (mutates doc in place). */
export async function hydrateComputedRelationsForRecipeIngredient(ctx: any, doc: Record<string, any>): Promise<void> {
  const docId = doc._id;
  {
    const __fk = ((doc as any) as any).ingredientId;
    ((doc as any) as any).ingredient = __fk != null ? await ctx.db.get(__fk as any) : null;
  }
}

/** Computed fields for RecipeIngredient. Pass the stored (and hydrated) document. */
export function computeRecipeIngredient(doc: Record<string, any>): Record<string, any> {
  const __adjustedQuantity = (doc.quantity * doc.wasteFactor);
  doc.adjustedQuantity = __adjustedQuantity;
  const __unitsMatchIngredientPrice = (doc.unit === doc.ingredient.unit);
  doc.unitsMatchIngredientPrice = __unitsMatchIngredientPrice;
  const __liveIngredientCost = ((doc.unit === doc.ingredient.unit) ? ((doc.quantity * doc.wasteFactor) * doc.ingredient.costPerUnit) : 0);
  doc.liveIngredientCost = __liveIngredientCost;
  return {
    adjustedQuantity: __adjustedQuantity,
    unitsMatchIngredientPrice: __unitsMatchIngredientPrice,
    liveIngredientCost: __liveIngredientCost,
  };
}

/** Computed fields for StorageLocation. Pass the stored (and hydrated) document. */
export function computeStorageLocation(doc: Record<string, any>): Record<string, any> {
  const __isActive = (doc.status === "active");
  doc.isActive = __isActive;
  return {
    isActive: __isActive,
  };
}

/** Computed fields for TaxRate. Pass the stored (and hydrated) document. */
export function computeTaxRate(doc: Record<string, any>): Record<string, any> {
  const __appliesToAny = ((doc.appliesToFood || doc.appliesToService) || doc.appliesToRental);
  doc.appliesToAny = __appliesToAny;
  return {
    appliesToAny: __appliesToAny,
  };
}

/** Computed fields for Vehicle. Pass the stored (and hydrated) document. */
export function computeVehicle(doc: Record<string, any>): Record<string, any> {
  const __isOperational = ((doc.operationalStatus === "available") || (doc.operationalStatus === "in_use"));
  doc.isOperational = __isOperational;
  return {
    isOperational: __isOperational,
  };
}

/** Preload nested relations for VendorOrder computeds (mutates doc in place). */
export async function hydrateComputedRelationsForVendorOrder(ctx: any, doc: Record<string, any>): Promise<void> {
  const docId = doc._id;
  (doc as any).lines = await ctx.db.query("vendorOrderLines").withIndex("by_vendorOrderId", (q: any) => q.eq("vendorOrderId", docId)).collect();
}

/** Computed fields for VendorOrder. Pass the stored (and hydrated) document. */
export function computeVendorOrder(doc: Record<string, any>): Record<string, any> {
  const __isDraft = (doc.status === "draft");
  doc.isDraft = __isDraft;
  const __isPendingApproval = (doc.status === "pending_approval");
  doc.isPendingApproval = __isPendingApproval;
  const __isOpenForReceiving = ((doc.status === "confirmed") || (doc.status === "partially_received"));
  doc.isOpenForReceiving = __isOpenForReceiving;
  const __hasIncompleteLines = (((doc.lines) ?? []).filter((line: Doc<"vendorOrderLines">) => ((((line.deletedAt == null) && (line.status !== "cancelled")) && (line.status !== "complete")))).length > 0);
  doc.hasIncompleteLines = __hasIncompleteLines;
  return {
    isDraft: __isDraft,
    isPendingApproval: __isPendingApproval,
    isOpenForReceiving: __isOpenForReceiving,
    hasIncompleteLines: __hasIncompleteLines,
  };
}

/** Computed fields for VendorOrderLine. Pass the stored (and hydrated) document. */
export function computeVendorOrderLine(doc: Record<string, any>): Record<string, any> {
  const __lineTotal = (doc.orderedQuantity * doc.unitCost);
  doc.lineTotal = __lineTotal;
  const __remainingQuantity = (doc.orderedQuantity - doc.receivedQuantity);
  doc.remainingQuantity = __remainingQuantity;
  const __isFullyReceived = ((doc.orderedQuantity > 0) && (doc.receivedQuantity >= doc.orderedQuantity));
  doc.isFullyReceived = __isFullyReceived;
  const __hasReceivingDiscrepancy = ((doc.discrepancyQuantity != null) && (doc.discrepancyQuantity > 0));
  doc.hasReceivingDiscrepancy = __hasReceivingDiscrepancy;
  return {
    lineTotal: __lineTotal,
    remainingQuantity: __remainingQuantity,
    isFullyReceived: __isFullyReceived,
    hasReceivingDiscrepancy: __hasReceivingDiscrepancy,
  };
}

/** Computed fields for Venue. Pass the stored (and hydrated) document. */
export function computeVenue(doc: Record<string, any>): Record<string, any> {
  const __isActive = (doc.status === "active");
  doc.isActive = __isActive;
  return {
    isActive: __isActive,
  };
}

/** Computed fields for WasteRecord. Pass the stored (and hydrated) document. */
export function computeWasteRecord(doc: Record<string, any>): Record<string, any> {
  const __costImpact = (doc.quantity * doc.unitCost);
  doc.costImpact = __costImpact;
  return {
    costImpact: __costImpact,
  };
}
