// GENERATED by the Manifest → Convex projection. DO NOT EDIT.
// 0 webhook route(s). 258 authenticated command dispatcher target(s).

import { httpRouter } from "convex/server";
import { httpAction } from "./_generated/server";
import { api } from "./_generated/api";

const http = httpRouter();

/** IR-derived command registry for the authenticated HTTP dispatcher. */
const COMMAND_DISPATCH = {
  "AvailabilityWindow.declare": {
    ref: api.mutations.AvailabilityWindow_createViaDeclare,
    params: ["personId","startsAt","endsAt","notes","idempotencyKey"] as const,
  },
  "AvailabilityWindow.withdraw": {
    ref: api.mutations.AvailabilityWindow_withdraw,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Client.archive": {
    ref: api.mutations.Client_archive,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "Client.assignOwner": {
    ref: api.mutations.Client_assignOwner,
    params: ["docId","assignedToId","version","idempotencyKey"] as const,
  },
  "Client.changeBillingProfile": {
    ref: api.mutations.Client_changeBillingProfile,
    params: ["docId","paymentTermsDays","taxExempt","taxId","version","idempotencyKey"] as const,
  },
  "Client.changeContact": {
    ref: api.mutations.Client_changeContact,
    params: ["docId","email","phone","website","addressLine1","addressLine2","city","region","postalCode","countryCode","version","idempotencyKey"] as const,
  },
  "Client.reactivate": {
    ref: api.mutations.Client_reactivate,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Client.register": {
    ref: api.mutations.Client_createViaRegister,
    params: ["clientType","companyName","givenName","familyName","email","phone","website","addressLine1","addressLine2","city","region","postalCode","countryCode","taxId","taxExempt","paymentTermsDays","notes","assignedToId","idempotencyKey"] as const,
  },
  "ClientContact.add": {
    ref: api.mutations.ClientContact_createViaAdd,
    params: ["clientId","givenName","familyName","title","email","phone","mobile","isPrimary","isBillingContact","notes","idempotencyKey"] as const,
  },
  "ClientContact.remove": {
    ref: api.mutations.ClientContact_remove,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "ClientContact.setPrimary": {
    ref: api.mutations.ClientContact_setPrimary,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "ClientContact.updateDetails": {
    ref: api.mutations.ClientContact_updateDetails,
    params: ["docId","givenName","familyName","title","email","phone","mobile","isBillingContact","notes","version","idempotencyKey"] as const,
  },
  "Contract.draft": {
    ref: api.mutations.Contract_createViaDraft,
    params: ["eventId","clientId","title","contractNumber","documentUrl","expiresAt","notes","idempotencyKey"] as const,
  },
  "Contract.expire": {
    ref: api.mutations.Contract_expire,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Contract.markViewed": {
    ref: api.mutations.Contract_markViewed,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Contract.markVoided": {
    ref: api.mutations.Contract_markVoided,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "Contract.send": {
    ref: api.mutations.Contract_send,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Contract.sign": {
    ref: api.mutations.Contract_sign,
    params: ["docId","signedBy","version","idempotencyKey"] as const,
  },
  "Delivery.cancel": {
    ref: api.mutations.Delivery_cancel,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "Delivery.confirmDelivery": {
    ref: api.mutations.Delivery_confirmDelivery,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Delivery.markFailed": {
    ref: api.mutations.Delivery_markFailed,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "Delivery.schedule": {
    ref: api.mutations.Delivery_createViaSchedule,
    params: ["packListId","eventId","destination","windowStartsAt","windowEndsAt","driverId","notes","idempotencyKey"] as const,
  },
  "Delivery.startTransit": {
    ref: api.mutations.Delivery_startTransit,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Dish.classifyAllergens": {
    ref: api.mutations.Dish_classifyAllergens,
    params: ["docId","allergenSummary","version","idempotencyKey"] as const,
  },
  "Dish.introduce": {
    ref: api.mutations.Dish_createViaIntroduce,
    params: ["name","portionSize","portionUnit","description","category","course","serviceStyle","dietaryTags","allergenSummary","idempotencyKey"] as const,
  },
  "Dish.reinstate": {
    ref: api.mutations.Dish_reinstate,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Dish.retire": {
    ref: api.mutations.Dish_retire,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "Dish.reviseDetails": {
    ref: api.mutations.Dish_reviseDetails,
    params: ["docId","name","description","category","course","serviceStyle","dietaryTags","version","idempotencyKey"] as const,
  },
  "Dish.updatePortioning": {
    ref: api.mutations.Dish_updatePortioning,
    params: ["docId","portionSize","portionUnit","version","idempotencyKey"] as const,
  },
  "DishRecipe.attach": {
    ref: api.mutations.DishRecipe_createViaAttach,
    params: ["dishId","recipeId","sortOrder","idempotencyKey"] as const,
  },
  "DishRecipe.detach": {
    ref: api.mutations.DishRecipe_detach,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "DishTask.add": {
    ref: api.mutations.DishTask_createViaAdd,
    params: ["dishId","name","category","taskType","defaultQuantity","defaultUnit","sortOrder","recipeId","ingredientId","instructions","idempotencyKey"] as const,
  },
  "DishTask.retire": {
    ref: api.mutations.DishTask_retire,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "DishTask.revise": {
    ref: api.mutations.DishTask_revise,
    params: ["docId","name","category","taskType","defaultQuantity","defaultUnit","sortOrder","recipeId","ingredientId","instructions","version","idempotencyKey"] as const,
  },
  "Event.approve": {
    ref: api.mutations.Event_approve,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Event.assignOwner": {
    ref: api.mutations.Event_assignOwner,
    params: ["docId","assignedToId","version","idempotencyKey"] as const,
  },
  "Event.beginExecution": {
    ref: api.mutations.Event_beginExecution,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Event.cancel": {
    ref: api.mutations.Event_cancel,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "Event.changeHeadcount": {
    ref: api.mutations.Event_changeHeadcount,
    params: ["docId","newHeadcount","version","idempotencyKey"] as const,
  },
  "Event.changePricing": {
    ref: api.mutations.Event_changePricing,
    params: ["docId","budgetAmount","quotedPrice","version","idempotencyKey"] as const,
  },
  "Event.changePrimaryContact": {
    ref: api.mutations.Event_changePrimaryContact,
    params: ["docId","primaryContactName","primaryContactEmail","primaryContactPhone","version","idempotencyKey"] as const,
  },
  "Event.changeRequirements": {
    ref: api.mutations.Event_changeRequirements,
    params: ["docId","accessibilityNeeds","serviceRequirements","operationalRequirements","version","idempotencyKey"] as const,
  },
  "Event.changeVenue": {
    ref: api.mutations.Event_changeVenue,
    params: ["docId","venueId","venueName","venueAddress","version","idempotencyKey"] as const,
  },
  "Event.closeOut": {
    ref: api.mutations.Event_closeOut,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Event.complete": {
    ref: api.mutations.Event_complete,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Event.planEngagement": {
    ref: api.mutations.Event_createViaPlanEngagement,
    params: ["clientId","title","eventType","startsAt","endsAt","expectedHeadcount","primaryContactName","budgetAmount","quotedPrice","venueId","venueName","venueAddress","primaryContactEmail","primaryContactPhone","accessibilityNeeds","serviceRequirements","operationalRequirements","assignedToId","idempotencyKey"] as const,
  },
  "Event.reschedule": {
    ref: api.mutations.Event_reschedule,
    params: ["docId","startsAt","endsAt","version","idempotencyKey"] as const,
  },
  "Event.returnToPlanning": {
    ref: api.mutations.Event_returnToPlanning,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "Event.submitForApproval": {
    ref: api.mutations.Event_submitForApproval,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "EventAllergenCheck.record": {
    ref: api.mutations.EventAllergenCheck_createViaRecord,
    params: ["eventId","result","eventDishId","dishId","flaggedAllergens","notes","idempotencyKey"] as const,
  },
  "EventAssignment.assign": {
    ref: api.mutations.EventAssignment_createViaAssign,
    params: ["eventId","personId","startsAt","endsAt","notes","idempotencyKey"] as const,
  },
  "EventAssignment.checkIn": {
    ref: api.mutations.EventAssignment_checkIn,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "EventAssignment.checkOut": {
    ref: api.mutations.EventAssignment_checkOut,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "EventAssignment.confirm": {
    ref: api.mutations.EventAssignment_confirm,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "EventAssignment.markNoShow": {
    ref: api.mutations.EventAssignment_markNoShow,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "EventAssignment.unassign": {
    ref: api.mutations.EventAssignment_unassign,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "EventCloseout.capture": {
    ref: api.mutations.EventCloseout_createViaCapture,
    params: ["eventId","actualRevenue","budgetedRevenue","revenueVariance","actualIngredientCost","actualWasteCost","actualLaborCost","actualVendorCost","budgetedCost","totalActualCost","costVariance","grossProfit","expectedHeadcount","actualHeadcount","unresolvedIssues","performanceNotes","notes","idempotencyKey"] as const,
  },
  "EventCloseout.finalize": {
    ref: api.mutations.EventCloseout_finalize,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "EventDish.addToEvent": {
    ref: api.mutations.EventDish_createViaAddToEvent,
    params: ["eventId","dishId","quantityServings","course","serviceStyle","specialInstructions","idempotencyKey"] as const,
  },
  "EventDish.adjustServings": {
    ref: api.mutations.EventDish_adjustServings,
    params: ["docId","quantityServings","version","idempotencyKey"] as const,
  },
  "EventDish.changeCourse": {
    ref: api.mutations.EventDish_changeCourse,
    params: ["docId","course","serviceStyle","version","idempotencyKey"] as const,
  },
  "EventDish.remove": {
    ref: api.mutations.EventDish_remove,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "EventDish.updateInstructions": {
    ref: api.mutations.EventDish_updateInstructions,
    params: ["docId","specialInstructions","version","idempotencyKey"] as const,
  },
  "EventGuest.assignTable": {
    ref: api.mutations.EventGuest_assignTable,
    params: ["docId","tableAssignment","version","idempotencyKey"] as const,
  },
  "EventGuest.checkIn": {
    ref: api.mutations.EventGuest_checkIn,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "EventGuest.invite": {
    ref: api.mutations.EventGuest_createViaInvite,
    params: ["eventId","name","email","phone","dietaryRestrictions","allergenRestrictions","accessibilityNeeds","specialMealRequired","idempotencyKey"] as const,
  },
  "EventGuest.rsvpConfirm": {
    ref: api.mutations.EventGuest_rsvpConfirm,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "EventGuest.rsvpDecline": {
    ref: api.mutations.EventGuest_rsvpDecline,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "EventGuest.withdraw": {
    ref: api.mutations.EventGuest_withdraw,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "Incident.beginInvestigation": {
    ref: api.mutations.Incident_beginInvestigation,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Incident.dismiss": {
    ref: api.mutations.Incident_dismiss,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "Incident.markResolved": {
    ref: api.mutations.Incident_markResolved,
    params: ["docId","resolution","version","idempotencyKey"] as const,
  },
  "Incident.report": {
    ref: api.mutations.Incident_createViaReport,
    params: ["eventId","severity","category","description","prepTaskId","deliveryId","shiftId","idempotencyKey"] as const,
  },
  "Ingredient.classifyAllergens": {
    ref: api.mutations.Ingredient_classifyAllergens,
    params: ["docId","allergens","version","idempotencyKey"] as const,
  },
  "Ingredient.discontinue": {
    ref: api.mutations.Ingredient_discontinue,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "Ingredient.introduce": {
    ref: api.mutations.Ingredient_createViaIntroduce,
    params: ["name","unit","costPerUnit","allergens","category","idempotencyKey"] as const,
  },
  "Ingredient.reinstate": {
    ref: api.mutations.Ingredient_reinstate,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Ingredient.updateCosting": {
    ref: api.mutations.Ingredient_updateCosting,
    params: ["docId","costPerUnit","version","idempotencyKey"] as const,
  },
  "Ingredient.updateDetails": {
    ref: api.mutations.Ingredient_updateDetails,
    params: ["docId","name","unit","category","version","idempotencyKey"] as const,
  },
  "IngredientDemand.calculate": {
    ref: api.mutations.IngredientDemand_createViaCalculate,
    params: ["eventId","ingredientId","requiredQuantity","unit","servings","dishId","sourceRecipeLineQuantity","sourceBatchMultiplier","sourceYieldQuantity","idempotencyKey"] as const,
  },
  "IngredientDemand.confirm": {
    ref: api.mutations.IngredientDemand_confirm,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "IngredientDemand.fulfill": {
    ref: api.mutations.IngredientDemand_fulfill,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "IngredientDemand.recalculate": {
    ref: api.mutations.IngredientDemand_recalculate,
    params: ["docId","newQuantity","reason","version","idempotencyKey"] as const,
  },
  "IngredientDemand.supersede": {
    ref: api.mutations.IngredientDemand_supersede,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "InventoryItem.adjustQuantity": {
    ref: api.mutations.InventoryItem_adjustQuantity,
    params: ["docId","delta","reason","version","idempotencyKey"] as const,
  },
  "InventoryItem.open": {
    ref: api.mutations.InventoryItem_createViaOpen,
    params: ["ingredientId","locationId","unit","quantityOnHand","parLevel","reorderThreshold","unitCost","idempotencyKey"] as const,
  },
  "InventoryItem.receiveStock": {
    ref: api.mutations.InventoryItem_receiveStock,
    params: ["docId","quantity","unitCost","version","idempotencyKey"] as const,
  },
  "InventoryItem.recount": {
    ref: api.mutations.InventoryItem_recount,
    params: ["docId","actualQuantity","version","idempotencyKey"] as const,
  },
  "InventoryItem.remove": {
    ref: api.mutations.InventoryItem_remove,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "InventoryItem.transferIn": {
    ref: api.mutations.InventoryItem_transferIn,
    params: ["docId","quantity","sourceLocationId","version","idempotencyKey"] as const,
  },
  "InventoryItem.transferOut": {
    ref: api.mutations.InventoryItem_transferOut,
    params: ["docId","quantity","destinationLocationId","version","idempotencyKey"] as const,
  },
  "InventoryItem.updateLevels": {
    ref: api.mutations.InventoryItem_updateLevels,
    params: ["docId","parLevel","reorderThreshold","unitCost","version","idempotencyKey"] as const,
  },
  "InventoryReservation.consume": {
    ref: api.mutations.InventoryReservation_consume,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "InventoryReservation.release": {
    ref: api.mutations.InventoryReservation_release,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "InventoryReservation.reserve": {
    ref: api.mutations.InventoryReservation_createViaReserve,
    params: ["inventoryItemId","eventId","ingredientId","quantity","idempotencyKey"] as const,
  },
  "Invoice.applyPayment": {
    ref: api.mutations.Invoice_applyPayment,
    params: ["docId","paymentAmount","paymentId","version","idempotencyKey"] as const,
  },
  "Invoice.issue": {
    ref: api.mutations.Invoice_createViaIssue,
    params: ["clientId","invoiceNumber","subtotal","taxAmount","discountAmount","total","eventId","paymentTermsDays","dueDate","notes","idempotencyKey"] as const,
  },
  "Invoice.markOverdue": {
    ref: api.mutations.Invoice_markOverdue,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Invoice.markViewed": {
    ref: api.mutations.Invoice_markViewed,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Invoice.markVoided": {
    ref: api.mutations.Invoice_markVoided,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "Invoice.recordRefund": {
    ref: api.mutations.Invoice_recordRefund,
    params: ["docId","refundAmount","paymentId","version","idempotencyKey"] as const,
  },
  "Invoice.send": {
    ref: api.mutations.Invoice_send,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Invoice.writeOff": {
    ref: api.mutations.Invoice_writeOff,
    params: ["docId","reason","writeOffAmount","version","idempotencyKey"] as const,
  },
  "Menu.archive": {
    ref: api.mutations.Menu_archive,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "Menu.draft": {
    ref: api.mutations.Menu_createViaDraft,
    params: ["name","description","category","isTemplate","basePrice","pricePerPerson","minGuests","maxGuests","idempotencyKey"] as const,
  },
  "Menu.markPublished": {
    ref: api.mutations.Menu_markPublished,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Menu.restore": {
    ref: api.mutations.Menu_restore,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Menu.reviseDetails": {
    ref: api.mutations.Menu_reviseDetails,
    params: ["docId","name","description","category","isTemplate","version","idempotencyKey"] as const,
  },
  "Menu.unpublish": {
    ref: api.mutations.Menu_unpublish,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "Menu.updatePricing": {
    ref: api.mutations.Menu_updatePricing,
    params: ["docId","basePrice","pricePerPerson","minGuests","maxGuests","version","idempotencyKey"] as const,
  },
  "MenuDish.add": {
    ref: api.mutations.MenuDish_createViaAdd,
    params: ["menuId","dishId","sortOrder","course","serviceStyle","specialInstructions","idempotencyKey"] as const,
  },
  "MenuDish.remove": {
    ref: api.mutations.MenuDish_remove,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "MenuDish.updateDetails": {
    ref: api.mutations.MenuDish_updateDetails,
    params: ["docId","sortOrder","course","serviceStyle","specialInstructions","version","idempotencyKey"] as const,
  },
  "Organization.deactivate": {
    ref: api.mutations.Organization_deactivate,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Organization.reactivate": {
    ref: api.mutations.Organization_reactivate,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Organization.register": {
    ref: api.mutations.Organization_createViaRegister,
    params: ["name","idempotencyKey"] as const,
  },
  "Organization.rename": {
    ref: api.mutations.Organization_rename,
    params: ["docId","name","version","idempotencyKey"] as const,
  },
  "Organization.suspend": {
    ref: api.mutations.Organization_suspend,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "PackList.cancel": {
    ref: api.mutations.PackList_cancel,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "PackList.dispatch": {
    ref: api.mutations.PackList_dispatch,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "PackList.markLoaded": {
    ref: api.mutations.PackList_markLoaded,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "PackList.markPacked": {
    ref: api.mutations.PackList_markPacked,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "PackList.open": {
    ref: api.mutations.PackList_createViaOpen,
    params: ["eventId","name","purpose","notes","idempotencyKey"] as const,
  },
  "PackList.startPacking": {
    ref: api.mutations.PackList_startPacking,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "PackListItem.addItem": {
    ref: api.mutations.PackListItem_createViaAddItem,
    params: ["packListId","description","requiredQuantity","unit","dishId","productionBatchId","eventDishId","prepTaskId","isGenerated","idempotencyKey"] as const,
  },
  "PackListItem.adjustQuantity": {
    ref: api.mutations.PackListItem_adjustQuantity,
    params: ["docId","requiredQuantity","version","idempotencyKey"] as const,
  },
  "PackListItem.markMissing": {
    ref: api.mutations.PackListItem_markMissing,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "PackListItem.markPacked": {
    ref: api.mutations.PackListItem_markPacked,
    params: ["docId","packedQuantity","version","idempotencyKey"] as const,
  },
  "PackListItem.refreshGenerated": {
    ref: api.mutations.PackListItem_refreshGenerated,
    params: ["docId","requiredQuantity","description","version","idempotencyKey"] as const,
  },
  "Payment.beginProcessing": {
    ref: api.mutations.Payment_beginProcessing,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Payment.fail": {
    ref: api.mutations.Payment_fail,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "Payment.record": {
    ref: api.mutations.Payment_createViaRecord,
    params: ["invoiceId","clientId","amount","method","eventId","paymentMethodId","notes","idempotencyKey"] as const,
  },
  "Payment.refund": {
    ref: api.mutations.Payment_refund,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "Payment.settle": {
    ref: api.mutations.Payment_settle,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "PaymentMethod.clearDefault": {
    ref: api.mutations.PaymentMethod_clearDefault,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "PaymentMethod.expire": {
    ref: api.mutations.PaymentMethod_expire,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "PaymentMethod.invalidate": {
    ref: api.mutations.PaymentMethod_invalidate,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "PaymentMethod.makeDefault": {
    ref: api.mutations.PaymentMethod_makeDefault,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "PaymentMethod.reactivate": {
    ref: api.mutations.PaymentMethod_reactivate,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "PaymentMethod.register": {
    ref: api.mutations.PaymentMethod_createViaRegister,
    params: ["clientId","methodType","provider","lastFour","isDefault","notes","idempotencyKey"] as const,
  },
  "PaymentMethod.remove": {
    ref: api.mutations.PaymentMethod_remove,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "PayrollInput.finalize": {
    ref: api.mutations.PayrollInput_finalize,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "PayrollInput.markVoided": {
    ref: api.mutations.PayrollInput_markVoided,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "PayrollInput.prepare": {
    ref: api.mutations.PayrollInput_createViaPrepare,
    params: ["personId","periodStart","periodEnd","regularMinutes","overtimeMinutes","totalMinutes","eventId","shiftId","hourlyRate","overtimeRate","grossAmount","notes","idempotencyKey"] as const,
  },
  "Person.assignRole": {
    ref: api.mutations.Person_assignRole,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Person.correctIdentity": {
    ref: api.mutations.Person_correctIdentity,
    params: ["docId","givenName","familyName","phone","version","idempotencyKey"] as const,
  },
  "Person.deactivate": {
    ref: api.mutations.Person_deactivate,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Person.hire": {
    ref: api.mutations.Person_createViaHire,
    params: ["givenName","familyName","email","phone","employmentType","employeeNumber","authSubjectId","idempotencyKey"] as const,
  },
  "Person.reactivate": {
    ref: api.mutations.Person_reactivate,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Person.terminate": {
    ref: api.mutations.Person_terminate,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "PrepTask.cancel": {
    ref: api.mutations.PrepTask_cancel,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "PrepTask.claim": {
    ref: api.mutations.PrepTask_claim,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "PrepTask.complete": {
    ref: api.mutations.PrepTask_complete,
    params: ["docId","completedQuantity","version","idempotencyKey"] as const,
  },
  "PrepTask.markBlocked": {
    ref: api.mutations.PrepTask_markBlocked,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "PrepTask.open": {
    ref: api.mutations.PrepTask_createViaOpen,
    params: ["eventDishId","eventId","name","quantity","unit","ingredientId","ingredientDemandId","recipeId","dishTaskId","dishId","category","taskType","specialInstructions","isGenerated","station","dueAt","notes","idempotencyKey"] as const,
  },
  "PrepTask.refreshGenerated": {
    ref: api.mutations.PrepTask_refreshGenerated,
    params: ["docId","quantity","specialInstructions","version","idempotencyKey"] as const,
  },
  "PrepTask.release": {
    ref: api.mutations.PrepTask_release,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "PrepTask.revise": {
    ref: api.mutations.PrepTask_revise,
    params: ["docId","name","quantity","unit","category","taskType","specialInstructions","ingredientId","recipeId","version","idempotencyKey"] as const,
  },
  "PrepTask.start": {
    ref: api.mutations.PrepTask_start,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "PrepTask.unblock": {
    ref: api.mutations.PrepTask_unblock,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "ProductionBatch.cancel": {
    ref: api.mutations.ProductionBatch_cancel,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "ProductionBatch.complete": {
    ref: api.mutations.ProductionBatch_complete,
    params: ["docId","actualYield","version","idempotencyKey"] as const,
  },
  "ProductionBatch.plan": {
    ref: api.mutations.ProductionBatch_createViaPlan,
    params: ["recipeId","plannedYield","yieldUnit","eventId","notes","idempotencyKey"] as const,
  },
  "ProductionBatch.start": {
    ref: api.mutations.ProductionBatch_start,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Proposal.accept": {
    ref: api.mutations.Proposal_accept,
    params: ["docId","eventId","version","idempotencyKey"] as const,
  },
  "Proposal.decline": {
    ref: api.mutations.Proposal_decline,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Proposal.draft": {
    ref: api.mutations.Proposal_createViaDraft,
    params: ["clientId","title","subtotal","taxAmount","discountAmount","total","proposalNumber","eventDate","eventType","guestCount","venueName","venueAddress","expiresAt","notes","terms","idempotencyKey"] as const,
  },
  "Proposal.expire": {
    ref: api.mutations.Proposal_expire,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Proposal.markViewed": {
    ref: api.mutations.Proposal_markViewed,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Proposal.send": {
    ref: api.mutations.Proposal_send,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "PurchaseNeed.assignToDraft": {
    ref: api.mutations.PurchaseNeed_assignToDraft,
    params: ["docId","vendorOrderId","vendorOrderLineId","version","idempotencyKey"] as const,
  },
  "PurchaseNeed.cancel": {
    ref: api.mutations.PurchaseNeed_cancel,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "PurchaseNeed.create": {
    ref: api.mutations.PurchaseNeed_create,
    params: ["eventId","ingredientDemandId","ingredientId","requiredQuantity","unit","idempotencyKey"] as const,
  },
  "PurchaseNeed.markDraftOrdered": {
    ref: api.mutations.PurchaseNeed_markDraftOrdered,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "PurchaseNeed.markFulfilled": {
    ref: api.mutations.PurchaseNeed_markFulfilled,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "PurchaseNeed.markOrdered": {
    ref: api.mutations.PurchaseNeed_markOrdered,
    params: ["docId","vendorOrderId","vendorOrderLineId","version","idempotencyKey"] as const,
  },
  "Qualification.expire": {
    ref: api.mutations.Qualification_expire,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Qualification.grant": {
    ref: api.mutations.Qualification_createViaGrant,
    params: ["personId","name","issuedAt","certificationType","expiresAt","documentRef","notes","idempotencyKey"] as const,
  },
  "Qualification.revoke": {
    ref: api.mutations.Qualification_revoke,
    params: ["docId","notes","version","idempotencyKey"] as const,
  },
  "QualityCheck.fail": {
    ref: api.mutations.QualityCheck_fail,
    params: ["docId","notes","version","idempotencyKey"] as const,
  },
  "QualityCheck.open": {
    ref: api.mutations.QualityCheck_createViaOpen,
    params: ["prepTaskId","productionBatchId","notes","idempotencyKey"] as const,
  },
  "QualityCheck.pass": {
    ref: api.mutations.QualityCheck_pass,
    params: ["docId","notes","version","idempotencyKey"] as const,
  },
  "QualityCheck.reinspect": {
    ref: api.mutations.QualityCheck_reinspect,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Recipe.draft": {
    ref: api.mutations.Recipe_createViaDraft,
    params: ["name","yieldQuantity","yieldUnit","batchMultiplier","category","cuisine","description","instructions","idempotencyKey"] as const,
  },
  "Recipe.publishVersion": {
    ref: api.mutations.Recipe_publishVersion,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Recipe.retire": {
    ref: api.mutations.Recipe_retire,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "Recipe.retract": {
    ref: api.mutations.Recipe_retract,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Recipe.reviseDraft": {
    ref: api.mutations.Recipe_reviseDraft,
    params: ["docId","name","yieldQuantity","yieldUnit","batchMultiplier","category","cuisine","description","instructions","version","idempotencyKey"] as const,
  },
  "RecipeImport.approveReview": {
    ref: api.mutations.RecipeImport_approveReview,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "RecipeImport.beginFinalization": {
    ref: api.mutations.RecipeImport_beginFinalization,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "RecipeImport.beginReview": {
    ref: api.mutations.RecipeImport_beginReview,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "RecipeImport.cancel": {
    ref: api.mutations.RecipeImport_cancel,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "RecipeImport.complete": {
    ref: api.mutations.RecipeImport_complete,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "RecipeImport.markFailed": {
    ref: api.mutations.RecipeImport_markFailed,
    params: ["docId","failureDetail","duringParsing","version","idempotencyKey"] as const,
  },
  "RecipeImport.recordParse": {
    ref: api.mutations.RecipeImport_recordParse,
    params: ["docId","parsedName","parsedLineCount","parsedDescription","parsedCategory","parsedCuisine","parsedInstructions","parsedYieldQuantity","parsedYieldUnit","parsedBatchMultiplier","version","idempotencyKey"] as const,
  },
  "RecipeImport.recordRecipe": {
    ref: api.mutations.RecipeImport_recordRecipe,
    params: ["docId","resultingRecipeId","version","idempotencyKey"] as const,
  },
  "RecipeImport.recordResolutionProgress": {
    ref: api.mutations.RecipeImport_recordResolutionProgress,
    params: ["docId","resolvedLineCount","version","idempotencyKey"] as const,
  },
  "RecipeImport.resumeReview": {
    ref: api.mutations.RecipeImport_resumeReview,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "RecipeImport.upload": {
    ref: api.mutations.RecipeImport_createViaUpload,
    params: ["sourceKind","rawSourceText","sourceByteCount","sourceFingerprint","sourceFilename","idempotencyKey"] as const,
  },
  "RecipeImportLine.attachCreatedIngredient": {
    ref: api.mutations.RecipeImportLine_attachCreatedIngredient,
    params: ["docId","matchedIngredientId","version","idempotencyKey"] as const,
  },
  "RecipeImportLine.confirmExisting": {
    ref: api.mutations.RecipeImportLine_confirmExisting,
    params: ["docId","matchedIngredientId","version","idempotencyKey"] as const,
  },
  "RecipeImportLine.confirmNew": {
    ref: api.mutations.RecipeImportLine_confirmNew,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "RecipeImportLine.discard": {
    ref: api.mutations.RecipeImportLine_discard,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "RecipeImportLine.markNew": {
    ref: api.mutations.RecipeImportLine_markNew,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "RecipeImportLine.resetResolution": {
    ref: api.mutations.RecipeImportLine_resetResolution,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "RecipeImportLine.stage": {
    ref: api.mutations.RecipeImportLine_createViaStage,
    params: ["importId","sourceOrder","sourceLine","parsedQuantity","parsedUnit","parsedIngredientName","preparationNote","idempotencyKey"] as const,
  },
  "RecipeImportLine.suggestExactMatch": {
    ref: api.mutations.RecipeImportLine_suggestExactMatch,
    params: ["docId","matchedIngredientId","version","idempotencyKey"] as const,
  },
  "RecipeImportLine.suggestPossibleMatches": {
    ref: api.mutations.RecipeImportLine_suggestPossibleMatches,
    params: ["docId","possibleMatchIngredientIds","version","idempotencyKey"] as const,
  },
  "RecipeIngredient.add": {
    ref: api.mutations.RecipeIngredient_createViaAdd,
    params: ["recipeId","ingredientId","quantity","unit","sortOrder","prepNotes","idempotencyKey"] as const,
  },
  "RecipeIngredient.adjustQuantity": {
    ref: api.mutations.RecipeIngredient_adjustQuantity,
    params: ["docId","quantity","unit","version","idempotencyKey"] as const,
  },
  "RecipeIngredient.remove": {
    ref: api.mutations.RecipeIngredient_remove,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "RecipeStep.add": {
    ref: api.mutations.RecipeStep_createViaAdd,
    params: ["recipeId","instruction","sortOrder","durationMinutes","idempotencyKey"] as const,
  },
  "RecipeStep.remove": {
    ref: api.mutations.RecipeStep_remove,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "RecipeStep.revise": {
    ref: api.mutations.RecipeStep_revise,
    params: ["docId","instruction","sortOrder","durationMinutes","version","idempotencyKey"] as const,
  },
  "SavedReportDefinition.archive": {
    ref: api.mutations.SavedReportDefinition_archive,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "SavedReportDefinition.changeSharing": {
    ref: api.mutations.SavedReportDefinition_changeSharing,
    params: ["docId","sharingScope","version","idempotencyKey"] as const,
  },
  "SavedReportDefinition.createDefinition": {
    ref: api.mutations.SavedReportDefinition_createViaCreateDefinition,
    params: ["name","subjectArea","chartType","definition","sharingScope","idempotencyKey"] as const,
  },
  "SavedReportDefinition.rename": {
    ref: api.mutations.SavedReportDefinition_rename,
    params: ["docId","name","version","idempotencyKey"] as const,
  },
  "SavedReportDefinition.restore": {
    ref: api.mutations.SavedReportDefinition_restore,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "SavedReportDefinition.updateDefinition": {
    ref: api.mutations.SavedReportDefinition_updateDefinition,
    params: ["docId","chartType","definition","subjectArea","version","idempotencyKey"] as const,
  },
  "Shift.cancel": {
    ref: api.mutations.Shift_cancel,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "Shift.complete": {
    ref: api.mutations.Shift_complete,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Shift.markNoShow": {
    ref: api.mutations.Shift_markNoShow,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Shift.schedule": {
    ref: api.mutations.Shift_createViaSchedule,
    params: ["personId","startsAt","endsAt","eventId","notes","idempotencyKey"] as const,
  },
  "Shift.start": {
    ref: api.mutations.Shift_start,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "StorageLocation.activate": {
    ref: api.mutations.StorageLocation_activate,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "StorageLocation.deactivate": {
    ref: api.mutations.StorageLocation_deactivate,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "StorageLocation.register": {
    ref: api.mutations.StorageLocation_createViaRegister,
    params: ["name","locationType","temperatureZone","minTemperature","maxTemperature","temperatureUnit","idempotencyKey"] as const,
  },
  "StorageLocation.reviseDetails": {
    ref: api.mutations.StorageLocation_reviseDetails,
    params: ["docId","name","locationType","temperatureZone","minTemperature","maxTemperature","temperatureUnit","version","idempotencyKey"] as const,
  },
  "TimeRecord.clockIn": {
    ref: api.mutations.TimeRecord_createViaClockIn,
    params: ["personId","shiftId","eventId","notes","idempotencyKey"] as const,
  },
  "TimeRecord.clockOut": {
    ref: api.mutations.TimeRecord_clockOut,
    params: ["docId","breakMinutes","notes","version","idempotencyKey"] as const,
  },
  "TimeRecord.correct": {
    ref: api.mutations.TimeRecord_correct,
    params: ["docId","clockInAt","clockOutAt","breakMinutes","notes","version","idempotencyKey"] as const,
  },
  "Vendor.onboard": {
    ref: api.mutations.Vendor_createViaOnboard,
    params: ["name","email","phone","addressLine1","city","region","postalCode","countryCode","paymentTermsDays","notes","idempotencyKey"] as const,
  },
  "Vendor.reinstate": {
    ref: api.mutations.Vendor_reinstate,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Vendor.suspend": {
    ref: api.mutations.Vendor_suspend,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "Vendor.terminate": {
    ref: api.mutations.Vendor_terminate,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "Vendor.updateDetails": {
    ref: api.mutations.Vendor_updateDetails,
    params: ["docId","name","email","phone","addressLine1","city","region","postalCode","countryCode","paymentTermsDays","notes","version","idempotencyKey"] as const,
  },
  "VendorOrder.cancel": {
    ref: api.mutations.VendorOrder_cancel,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "VendorOrder.confirm": {
    ref: api.mutations.VendorOrder_confirm,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "VendorOrder.markPartiallyReceived": {
    ref: api.mutations.VendorOrder_markPartiallyReceived,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "VendorOrder.markReceived": {
    ref: api.mutations.VendorOrder_markReceived,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "VendorOrder.open": {
    ref: api.mutations.VendorOrder_createViaOpen,
    params: ["vendorId","eventId","sourceRangeStart","sourceRangeEnd","orderNumber","notes","idempotencyKey"] as const,
  },
  "VendorOrder.submit": {
    ref: api.mutations.VendorOrder_submit,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "VendorOrder.updateTotals": {
    ref: api.mutations.VendorOrder_updateTotals,
    params: ["docId","subtotal","taxAmount","shippingAmount","version","idempotencyKey"] as const,
  },
  "VendorOrderLine.addLine": {
    ref: api.mutations.VendorOrderLine_createViaAddLine,
    params: ["vendorOrderId","ingredientId","orderedQuantity","unit","unitCost","ingredientDemandId","locationId","idempotencyKey"] as const,
  },
  "VendorOrderLine.cancelLine": {
    ref: api.mutations.VendorOrderLine_cancelLine,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "VendorOrderLine.recordReceipt": {
    ref: api.mutations.VendorOrderLine_recordReceipt,
    params: ["docId","quantity","locationId","discrepancyQuantity","discrepancyNotes","version","idempotencyKey"] as const,
  },
  "VendorOrderLine.reviseQuantity": {
    ref: api.mutations.VendorOrderLine_reviseQuantity,
    params: ["docId","orderedQuantity","unitCost","version","idempotencyKey"] as const,
  },
  "VendorOrderLineDemand.link": {
    ref: api.mutations.VendorOrderLineDemand_createViaLink,
    params: ["vendorOrderLineId","ingredientDemandId","contributionQuantity","unit","idempotencyKey"] as const,
  },
  "VendorOrderLineDemand.retire": {
    ref: api.mutations.VendorOrderLineDemand_retire,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "VendorOrderLineDemand.revise": {
    ref: api.mutations.VendorOrderLineDemand_revise,
    params: ["docId","contributionQuantity","version","idempotencyKey"] as const,
  },
  "Venue.activate": {
    ref: api.mutations.Venue_activate,
    params: ["docId","version","idempotencyKey"] as const,
  },
  "Venue.changeCapacity": {
    ref: api.mutations.Venue_changeCapacity,
    params: ["docId","capacity","version","idempotencyKey"] as const,
  },
  "Venue.deactivate": {
    ref: api.mutations.Venue_deactivate,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
  "Venue.register": {
    ref: api.mutations.Venue_createViaRegister,
    params: ["name","venueType","capacity","addressLine1","addressLine2","city","region","postalCode","countryCode","contactName","contactEmail","contactPhone","accessNotes","cateringNotes","idempotencyKey"] as const,
  },
  "Venue.updateDetails": {
    ref: api.mutations.Venue_updateDetails,
    params: ["docId","name","venueType","addressLine1","addressLine2","city","region","postalCode","countryCode","contactName","contactEmail","contactPhone","accessNotes","cateringNotes","version","idempotencyKey"] as const,
  },
  "WasteRecord.record": {
    ref: api.mutations.WasteRecord_createViaRecord,
    params: ["ingredientId","locationId","quantity","unit","reason","eventId","inventoryItemId","unitCost","notes","idempotencyKey"] as const,
  },
  "WasteRecord.voidRecord": {
    ref: api.mutations.WasteRecord_voidRecord,
    params: ["docId","reason","version","idempotencyKey"] as const,
  },
} as const;

const DISPATCHER_FORBIDDEN_BODY_KEYS = new Set(["__auth","user","role","tenantId","orgId","userId","actorId","identity"]);

http.route({
  pathPrefix: "/api/manifest/",
  method: "POST",
  handler: httpAction(async (ctx, request) => {
    const identity = await ctx.auth.getUserIdentity();
    if (identity === null) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers: { "Content-Type": "application/json" } });
    }
    const url = new URL(request.url);
    const match = url.pathname.match(/^\/api\/manifest\/([^/]+)\/commands\/([^/]+)\/?$/);
    if (!match) {
      return new Response(JSON.stringify({ error: "Not found" }), { status: 404, headers: { "Content-Type": "application/json" } });
    }
    const entity = match[1]!;
    const command = match[2]!;
    const entry = (COMMAND_DISPATCH as Record<string, { ref: any; params: readonly string[] }>)[entity + "." + command];
    if (!entry) {
      return new Response(JSON.stringify({ error: "Unknown command " + entity + "." + command }), { status: 404, headers: { "Content-Type": "application/json" } });
    }
    let body: Record<string, unknown> = {};
    try {
      const parsed = await request.json();
      if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
        return new Response(JSON.stringify({ error: "Invalid JSON body" }), { status: 400, headers: { "Content-Type": "application/json" } });
      }
      body = parsed as Record<string, unknown>;
    } catch {
      return new Response(JSON.stringify({ error: "Invalid JSON body" }), { status: 400, headers: { "Content-Type": "application/json" } });
    }
    const args: Record<string, unknown> = {};
    for (const name of entry.params) {
      if (DISPATCHER_FORBIDDEN_BODY_KEYS.has(name)) continue;
      if (Object.prototype.hasOwnProperty.call(body, name)) args[name] = body[name];
    }
    try {
      const result = await ctx.runMutation(entry.ref, args as any);
      return new Response(JSON.stringify({ data: result }), { status: 200, headers: { "Content-Type": "application/json" } });
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      return new Response(JSON.stringify({ error: message }), { status: 400, headers: { "Content-Type": "application/json" } });
    }
  }),
});

export default http;
