// GENERATED by the Manifest → Convex projection. DO NOT EDIT.
// 0 webhook route(s).

import { httpRouter } from "convex/server";
import { httpAction } from "./_generated/server";
import { api } from "./_generated/api";

const http = httpRouter();


export default http;
