// GENERATED by the Manifest → Convex projection. DO NOT EDIT.
// 0 cron job(s).

import { cronJobs } from "convex/server";
import { api } from "./_generated/api";

const crons = cronJobs();


export default crons;
