/** Generated by Manifest contract-tests.convex — do not edit by hand. */
import { describe, it, expect } from "vitest";
import * as queries from "../convex/queries";
import * as mutations from "../convex/mutations";

describe("Manifest Convex contract", () => {
  it("exports mutation Attachment_attach", () => {
    expect(typeof (mutations as any).Attachment_attach).toBe("function");
  });
  it("exports mutation Attachment_remove", () => {
    expect(typeof (mutations as any).Attachment_remove).toBe("function");
  });
  it("exports mutation AvailabilityWindow_declare", () => {
    expect(typeof (mutations as any).AvailabilityWindow_declare).toBe("function");
  });
  it("exports mutation AvailabilityWindow_withdraw", () => {
    expect(typeof (mutations as any).AvailabilityWindow_withdraw).toBe("function");
  });
  it("exports mutation Client_archive", () => {
    expect(typeof (mutations as any).Client_archive).toBe("function");
  });
  it("exports mutation Client_assignOwner", () => {
    expect(typeof (mutations as any).Client_assignOwner).toBe("function");
  });
  it("exports mutation Client_changeBillingProfile", () => {
    expect(typeof (mutations as any).Client_changeBillingProfile).toBe("function");
  });
  it("exports mutation Client_changeContact", () => {
    expect(typeof (mutations as any).Client_changeContact).toBe("function");
  });
  it("exports mutation Client_markMerged", () => {
    expect(typeof (mutations as any).Client_markMerged).toBe("function");
  });
  it("exports mutation Client_reactivate", () => {
    expect(typeof (mutations as any).Client_reactivate).toBe("function");
  });
  it("exports mutation Client_register", () => {
    expect(typeof (mutations as any).Client_register).toBe("function");
  });
  it("exports mutation Client_stageClientMerge", () => {
    expect(typeof (mutations as any).Client_stageClientMerge).toBe("function");
  });
  it("exports mutation ClientCommunication_record", () => {
    expect(typeof (mutations as any).ClientCommunication_record).toBe("function");
  });
  it("exports mutation ClientContact_add", () => {
    expect(typeof (mutations as any).ClientContact_add).toBe("function");
  });
  it("exports mutation ClientContact_reassignClient", () => {
    expect(typeof (mutations as any).ClientContact_reassignClient).toBe("function");
  });
  it("exports mutation ClientContact_remove", () => {
    expect(typeof (mutations as any).ClientContact_remove).toBe("function");
  });
  it("exports mutation ClientContact_setPrimary", () => {
    expect(typeof (mutations as any).ClientContact_setPrimary).toBe("function");
  });
  it("exports mutation ClientContact_stageClientMerge", () => {
    expect(typeof (mutations as any).ClientContact_stageClientMerge).toBe("function");
  });
  it("exports mutation ClientContact_updateDetails", () => {
    expect(typeof (mutations as any).ClientContact_updateDetails).toBe("function");
  });
  it("exports mutation ClientMerge_merge", () => {
    expect(typeof (mutations as any).ClientMerge_merge).toBe("function");
  });
  it("exports mutation Contract_draft", () => {
    expect(typeof (mutations as any).Contract_draft).toBe("function");
  });
  it("exports mutation Contract_expire", () => {
    expect(typeof (mutations as any).Contract_expire).toBe("function");
  });
  it("exports mutation Contract_markViewed", () => {
    expect(typeof (mutations as any).Contract_markViewed).toBe("function");
  });
  it("exports mutation Contract_markVoided", () => {
    expect(typeof (mutations as any).Contract_markVoided).toBe("function");
  });
  it("exports mutation Contract_reassignClient", () => {
    expect(typeof (mutations as any).Contract_reassignClient).toBe("function");
  });
  it("exports mutation Contract_send", () => {
    expect(typeof (mutations as any).Contract_send).toBe("function");
  });
  it("exports mutation Contract_sign", () => {
    expect(typeof (mutations as any).Contract_sign).toBe("function");
  });
  it("exports mutation Contract_stageClientMerge", () => {
    expect(typeof (mutations as any).Contract_stageClientMerge).toBe("function");
  });
  it("exports mutation CorrectiveAction_close", () => {
    expect(typeof (mutations as any).CorrectiveAction_close).toBe("function");
  });
  it("exports mutation CorrectiveAction_open", () => {
    expect(typeof (mutations as any).CorrectiveAction_open).toBe("function");
  });
  it("exports mutation CreditMemo_issue", () => {
    expect(typeof (mutations as any).CreditMemo_issue).toBe("function");
  });
  it("exports mutation CreditMemo_reassignClient", () => {
    expect(typeof (mutations as any).CreditMemo_reassignClient).toBe("function");
  });
  it("exports mutation CreditMemo_stageClientMerge", () => {
    expect(typeof (mutations as any).CreditMemo_stageClientMerge).toBe("function");
  });
  it("exports mutation Delivery_cancel", () => {
    expect(typeof (mutations as any).Delivery_cancel).toBe("function");
  });
  it("exports mutation Delivery_confirmDelivery", () => {
    expect(typeof (mutations as any).Delivery_confirmDelivery).toBe("function");
  });
  it("exports mutation Delivery_markFailed", () => {
    expect(typeof (mutations as any).Delivery_markFailed).toBe("function");
  });
  it("exports mutation Delivery_schedule", () => {
    expect(typeof (mutations as any).Delivery_schedule).toBe("function");
  });
  it("exports mutation Delivery_startTransit", () => {
    expect(typeof (mutations as any).Delivery_startTransit).toBe("function");
  });
  it("exports mutation Dish_classifyAllergens", () => {
    expect(typeof (mutations as any).Dish_classifyAllergens).toBe("function");
  });
  it("exports mutation Dish_introduce", () => {
    expect(typeof (mutations as any).Dish_introduce).toBe("function");
  });
  it("exports mutation Dish_reinstate", () => {
    expect(typeof (mutations as any).Dish_reinstate).toBe("function");
  });
  it("exports mutation Dish_retire", () => {
    expect(typeof (mutations as any).Dish_retire).toBe("function");
  });
  it("exports mutation Dish_reviseDetails", () => {
    expect(typeof (mutations as any).Dish_reviseDetails).toBe("function");
  });
  it("exports mutation Dish_updatePortioning", () => {
    expect(typeof (mutations as any).Dish_updatePortioning).toBe("function");
  });
  it("exports mutation DishRecipe_attach", () => {
    expect(typeof (mutations as any).DishRecipe_attach).toBe("function");
  });
  it("exports mutation DishRecipe_detach", () => {
    expect(typeof (mutations as any).DishRecipe_detach).toBe("function");
  });
  it("exports mutation DishTask_add", () => {
    expect(typeof (mutations as any).DishTask_add).toBe("function");
  });
  it("exports mutation DishTask_retire", () => {
    expect(typeof (mutations as any).DishTask_retire).toBe("function");
  });
  it("exports mutation DishTask_revise", () => {
    expect(typeof (mutations as any).DishTask_revise).toBe("function");
  });
  it("exports mutation EmailNotificationSubscription_configure", () => {
    expect(typeof (mutations as any).EmailNotificationSubscription_configure).toBe("function");
  });
  it("exports mutation EmailNotificationSubscription_updateSubscriptions", () => {
    expect(typeof (mutations as any).EmailNotificationSubscription_updateSubscriptions).toBe("function");
  });
  it("exports mutation Equipment_reactivate", () => {
    expect(typeof (mutations as any).Equipment_reactivate).toBe("function");
  });
  it("exports mutation Equipment_recount", () => {
    expect(typeof (mutations as any).Equipment_recount).toBe("function");
  });
  it("exports mutation Equipment_register", () => {
    expect(typeof (mutations as any).Equipment_register).toBe("function");
  });
  it("exports mutation Equipment_retire", () => {
    expect(typeof (mutations as any).Equipment_retire).toBe("function");
  });
  it("exports mutation Equipment_reviseDetails", () => {
    expect(typeof (mutations as any).Equipment_reviseDetails).toBe("function");
  });
  it("exports mutation Equipment_updateCondition", () => {
    expect(typeof (mutations as any).Equipment_updateCondition).toBe("function");
  });
  it("exports mutation EquipmentMaintenanceTask_applyService", () => {
    expect(typeof (mutations as any).EquipmentMaintenanceTask_applyService).toBe("function");
  });
  it("exports mutation EquipmentMaintenanceTask_schedule", () => {
    expect(typeof (mutations as any).EquipmentMaintenanceTask_schedule).toBe("function");
  });
  it("exports mutation EquipmentReservation_cancel", () => {
    expect(typeof (mutations as any).EquipmentReservation_cancel).toBe("function");
  });
  it("exports mutation EquipmentReservation_checkOut", () => {
    expect(typeof (mutations as any).EquipmentReservation_checkOut).toBe("function");
  });
  it("exports mutation EquipmentReservation_markReturned", () => {
    expect(typeof (mutations as any).EquipmentReservation_markReturned).toBe("function");
  });
  it("exports mutation EquipmentServiceEntry_record", () => {
    expect(typeof (mutations as any).EquipmentServiceEntry_record).toBe("function");
  });
  it("exports mutation Event_approve", () => {
    expect(typeof (mutations as any).Event_approve).toBe("function");
  });
  it("exports mutation Event_assignOwner", () => {
    expect(typeof (mutations as any).Event_assignOwner).toBe("function");
  });
  it("exports mutation Event_beginExecution", () => {
    expect(typeof (mutations as any).Event_beginExecution).toBe("function");
  });
  it("exports mutation Event_cancel", () => {
    expect(typeof (mutations as any).Event_cancel).toBe("function");
  });
  it("exports mutation Event_changeHeadcount", () => {
    expect(typeof (mutations as any).Event_changeHeadcount).toBe("function");
  });
  it("exports mutation Event_changePricing", () => {
    expect(typeof (mutations as any).Event_changePricing).toBe("function");
  });
  it("exports mutation Event_changePrimaryContact", () => {
    expect(typeof (mutations as any).Event_changePrimaryContact).toBe("function");
  });
  it("exports mutation Event_changeRequirements", () => {
    expect(typeof (mutations as any).Event_changeRequirements).toBe("function");
  });
  it("exports mutation Event_changeVenue", () => {
    expect(typeof (mutations as any).Event_changeVenue).toBe("function");
  });
  it("exports mutation Event_closeOut", () => {
    expect(typeof (mutations as any).Event_closeOut).toBe("function");
  });
  it("exports mutation Event_complete", () => {
    expect(typeof (mutations as any).Event_complete).toBe("function");
  });
  it("exports mutation Event_configureRecurrence", () => {
    expect(typeof (mutations as any).Event_configureRecurrence).toBe("function");
  });
  it("exports mutation Event_planEngagement", () => {
    expect(typeof (mutations as any).Event_planEngagement).toBe("function");
  });
  it("exports mutation Event_reassignClient", () => {
    expect(typeof (mutations as any).Event_reassignClient).toBe("function");
  });
  it("exports mutation Event_reschedule", () => {
    expect(typeof (mutations as any).Event_reschedule).toBe("function");
  });
  it("exports mutation Event_returnToPlanning", () => {
    expect(typeof (mutations as any).Event_returnToPlanning).toBe("function");
  });
  it("exports mutation Event_stageClientMerge", () => {
    expect(typeof (mutations as any).Event_stageClientMerge).toBe("function");
  });
  it("exports mutation Event_stopRecurrence", () => {
    expect(typeof (mutations as any).Event_stopRecurrence).toBe("function");
  });
  it("exports mutation Event_submitForApproval", () => {
    expect(typeof (mutations as any).Event_submitForApproval).toBe("function");
  });
  it("exports mutation EventAllergenCheck_record", () => {
    expect(typeof (mutations as any).EventAllergenCheck_record).toBe("function");
  });
  it("exports mutation EventAssignment_assign", () => {
    expect(typeof (mutations as any).EventAssignment_assign).toBe("function");
  });
  it("exports mutation EventAssignment_checkIn", () => {
    expect(typeof (mutations as any).EventAssignment_checkIn).toBe("function");
  });
  it("exports mutation EventAssignment_checkOut", () => {
    expect(typeof (mutations as any).EventAssignment_checkOut).toBe("function");
  });
  it("exports mutation EventAssignment_confirm", () => {
    expect(typeof (mutations as any).EventAssignment_confirm).toBe("function");
  });
  it("exports mutation EventAssignment_markNoShow", () => {
    expect(typeof (mutations as any).EventAssignment_markNoShow).toBe("function");
  });
  it("exports mutation EventAssignment_unassign", () => {
    expect(typeof (mutations as any).EventAssignment_unassign).toBe("function");
  });
  it("exports mutation EventCloseout_capture", () => {
    expect(typeof (mutations as any).EventCloseout_capture).toBe("function");
  });
  it("exports mutation EventCloseout_finalize", () => {
    expect(typeof (mutations as any).EventCloseout_finalize).toBe("function");
  });
  it("exports mutation EventDish_addToEvent", () => {
    expect(typeof (mutations as any).EventDish_addToEvent).toBe("function");
  });
  it("exports mutation EventDish_adjustServings", () => {
    expect(typeof (mutations as any).EventDish_adjustServings).toBe("function");
  });
  it("exports mutation EventDish_changeCourse", () => {
    expect(typeof (mutations as any).EventDish_changeCourse).toBe("function");
  });
  it("exports mutation EventDish_remove", () => {
    expect(typeof (mutations as any).EventDish_remove).toBe("function");
  });
  it("exports mutation EventDish_updateInstructions", () => {
    expect(typeof (mutations as any).EventDish_updateInstructions).toBe("function");
  });
  it("exports listEventDishRecipeSeed / getEventDishRecipeSeed", () => {
    expect(typeof (queries as any).listEventDishRecipeSeed).toBe("function");
    expect(typeof (queries as any).getEventDishRecipeSeed).toBe("function");
  });
  it("exports mutation EventDishRecipeSeed_seed", () => {
    expect(typeof (mutations as any).EventDishRecipeSeed_seed).toBe("function");
  });
  it("exports mutation EventGuest_assignTable", () => {
    expect(typeof (mutations as any).EventGuest_assignTable).toBe("function");
  });
  it("exports mutation EventGuest_checkIn", () => {
    expect(typeof (mutations as any).EventGuest_checkIn).toBe("function");
  });
  it("exports mutation EventGuest_invite", () => {
    expect(typeof (mutations as any).EventGuest_invite).toBe("function");
  });
  it("exports mutation EventGuest_rsvpConfirm", () => {
    expect(typeof (mutations as any).EventGuest_rsvpConfirm).toBe("function");
  });
  it("exports mutation EventGuest_rsvpDecline", () => {
    expect(typeof (mutations as any).EventGuest_rsvpDecline).toBe("function");
  });
  it("exports mutation EventGuest_withdraw", () => {
    expect(typeof (mutations as any).EventGuest_withdraw).toBe("function");
  });
  it("exports mutation EventIngredientContribution_record", () => {
    expect(typeof (mutations as any).EventIngredientContribution_record).toBe("function");
  });
  it("exports mutation EventIngredientContribution_retire", () => {
    expect(typeof (mutations as any).EventIngredientContribution_retire).toBe("function");
  });
  it("exports mutation EventIngredientContribution_revise", () => {
    expect(typeof (mutations as any).EventIngredientContribution_revise).toBe("function");
  });
  it("exports mutation EventTemplate_archive", () => {
    expect(typeof (mutations as any).EventTemplate_archive).toBe("function");
  });
  it("exports mutation EventTemplate_define", () => {
    expect(typeof (mutations as any).EventTemplate_define).toBe("function");
  });
  it("exports mutation EventTemplate_reactivate", () => {
    expect(typeof (mutations as any).EventTemplate_reactivate).toBe("function");
  });
  it("exports mutation EventTemplate_revise", () => {
    expect(typeof (mutations as any).EventTemplate_revise).toBe("function");
  });
  it("exports mutation EventTimelineActivity_adjust", () => {
    expect(typeof (mutations as any).EventTimelineActivity_adjust).toBe("function");
  });
  it("exports mutation EventTimelineActivity_remove", () => {
    expect(typeof (mutations as any).EventTimelineActivity_remove).toBe("function");
  });
  it("exports mutation EventTimelineActivity_schedule", () => {
    expect(typeof (mutations as any).EventTimelineActivity_schedule).toBe("function");
  });
  it("exports mutation Incident_beginInvestigation", () => {
    expect(typeof (mutations as any).Incident_beginInvestigation).toBe("function");
  });
  it("exports mutation Incident_clearCorrectiveActionLock", () => {
    expect(typeof (mutations as any).Incident_clearCorrectiveActionLock).toBe("function");
  });
  it("exports mutation Incident_dismiss", () => {
    expect(typeof (mutations as any).Incident_dismiss).toBe("function");
  });
  it("exports mutation Incident_markResolved", () => {
    expect(typeof (mutations as any).Incident_markResolved).toBe("function");
  });
  it("exports mutation Incident_report", () => {
    expect(typeof (mutations as any).Incident_report).toBe("function");
  });
  it("exports mutation Ingredient_classifyAllergens", () => {
    expect(typeof (mutations as any).Ingredient_classifyAllergens).toBe("function");
  });
  it("exports mutation Ingredient_configureSubstitutes", () => {
    expect(typeof (mutations as any).Ingredient_configureSubstitutes).toBe("function");
  });
  it("exports mutation Ingredient_discontinue", () => {
    expect(typeof (mutations as any).Ingredient_discontinue).toBe("function");
  });
  it("exports mutation Ingredient_introduce", () => {
    expect(typeof (mutations as any).Ingredient_introduce).toBe("function");
  });
  it("exports mutation Ingredient_reinstate", () => {
    expect(typeof (mutations as any).Ingredient_reinstate).toBe("function");
  });
  it("exports mutation Ingredient_setPreferredVendor", () => {
    expect(typeof (mutations as any).Ingredient_setPreferredVendor).toBe("function");
  });
  it("exports mutation Ingredient_setPreferredVendors", () => {
    expect(typeof (mutations as any).Ingredient_setPreferredVendors).toBe("function");
  });
  it("exports mutation Ingredient_updateCosting", () => {
    expect(typeof (mutations as any).Ingredient_updateCosting).toBe("function");
  });
  it("exports mutation Ingredient_updateDetails", () => {
    expect(typeof (mutations as any).Ingredient_updateDetails).toBe("function");
  });
  it("exports mutation IngredientDemand_calculate", () => {
    expect(typeof (mutations as any).IngredientDemand_calculate).toBe("function");
  });
  it("exports mutation IngredientDemand_confirm", () => {
    expect(typeof (mutations as any).IngredientDemand_confirm).toBe("function");
  });
  it("exports mutation IngredientDemand_ensurePurchaseEligible", () => {
    expect(typeof (mutations as any).IngredientDemand_ensurePurchaseEligible).toBe("function");
  });
  it("exports mutation IngredientDemand_fulfill", () => {
    expect(typeof (mutations as any).IngredientDemand_fulfill).toBe("function");
  });
  it("exports mutation IngredientDemand_markReleased", () => {
    expect(typeof (mutations as any).IngredientDemand_markReleased).toBe("function");
  });
  it("exports mutation IngredientDemand_recalculate", () => {
    expect(typeof (mutations as any).IngredientDemand_recalculate).toBe("function");
  });
  it("exports mutation IngredientDemand_supersede", () => {
    expect(typeof (mutations as any).IngredientDemand_supersede).toBe("function");
  });
  it("exports mutation IngredientDemand_syncFromContributions", () => {
    expect(typeof (mutations as any).IngredientDemand_syncFromContributions).toBe("function");
  });
  it("exports mutation IngredientPriceObservation_record", () => {
    expect(typeof (mutations as any).IngredientPriceObservation_record).toBe("function");
  });
  it("exports mutation InventoryItem_adjustQuantity", () => {
    expect(typeof (mutations as any).InventoryItem_adjustQuantity).toBe("function");
  });
  it("exports mutation InventoryItem_open", () => {
    expect(typeof (mutations as any).InventoryItem_open).toBe("function");
  });
  it("exports mutation InventoryItem_receiveStock", () => {
    expect(typeof (mutations as any).InventoryItem_receiveStock).toBe("function");
  });
  it("exports mutation InventoryItem_recount", () => {
    expect(typeof (mutations as any).InventoryItem_recount).toBe("function");
  });
  it("exports mutation InventoryItem_remove", () => {
    expect(typeof (mutations as any).InventoryItem_remove).toBe("function");
  });
  it("exports mutation InventoryItem_setExpiry", () => {
    expect(typeof (mutations as any).InventoryItem_setExpiry).toBe("function");
  });
  it("exports mutation InventoryItem_transferIn", () => {
    expect(typeof (mutations as any).InventoryItem_transferIn).toBe("function");
  });
  it("exports mutation InventoryItem_transferOut", () => {
    expect(typeof (mutations as any).InventoryItem_transferOut).toBe("function");
  });
  it("exports mutation InventoryItem_updateLevels", () => {
    expect(typeof (mutations as any).InventoryItem_updateLevels).toBe("function");
  });
  it("exports mutation InventoryLot_record", () => {
    expect(typeof (mutations as any).InventoryLot_record).toBe("function");
  });
  it("exports mutation InventoryReservation_consume", () => {
    expect(typeof (mutations as any).InventoryReservation_consume).toBe("function");
  });
  it("exports mutation InventoryReservation_release", () => {
    expect(typeof (mutations as any).InventoryReservation_release).toBe("function");
  });
  it("exports mutation InventoryReservation_reserve", () => {
    expect(typeof (mutations as any).InventoryReservation_reserve).toBe("function");
  });
  it("exports mutation Invoice_applyCredit", () => {
    expect(typeof (mutations as any).Invoice_applyCredit).toBe("function");
  });
  it("exports mutation Invoice_applyPayment", () => {
    expect(typeof (mutations as any).Invoice_applyPayment).toBe("function");
  });
  it("exports mutation Invoice_issue", () => {
    expect(typeof (mutations as any).Invoice_issue).toBe("function");
  });
  it("exports mutation Invoice_markDepositPaid", () => {
    expect(typeof (mutations as any).Invoice_markDepositPaid).toBe("function");
  });
  it("exports mutation Invoice_markOverdue", () => {
    expect(typeof (mutations as any).Invoice_markOverdue).toBe("function");
  });
  it("exports mutation Invoice_markViewed", () => {
    expect(typeof (mutations as any).Invoice_markViewed).toBe("function");
  });
  it("exports mutation Invoice_markVoided", () => {
    expect(typeof (mutations as any).Invoice_markVoided).toBe("function");
  });
  it("exports mutation Invoice_reassignClient", () => {
    expect(typeof (mutations as any).Invoice_reassignClient).toBe("function");
  });
  it("exports mutation Invoice_recordCreditMemo", () => {
    expect(typeof (mutations as any).Invoice_recordCreditMemo).toBe("function");
  });
  it("exports mutation Invoice_recordRefund", () => {
    expect(typeof (mutations as any).Invoice_recordRefund).toBe("function");
  });
  it("exports mutation Invoice_send", () => {
    expect(typeof (mutations as any).Invoice_send).toBe("function");
  });
  it("exports mutation Invoice_sendBalanceReminder", () => {
    expect(typeof (mutations as any).Invoice_sendBalanceReminder).toBe("function");
  });
  it("exports mutation Invoice_setDeposit", () => {
    expect(typeof (mutations as any).Invoice_setDeposit).toBe("function");
  });
  it("exports mutation Invoice_stageClientMerge", () => {
    expect(typeof (mutations as any).Invoice_stageClientMerge).toBe("function");
  });
  it("exports mutation Invoice_writeOff", () => {
    expect(typeof (mutations as any).Invoice_writeOff).toBe("function");
  });
  it("exports mutation Lead_capture", () => {
    expect(typeof (mutations as any).Lead_capture).toBe("function");
  });
  it("exports mutation Lead_confirmConversion", () => {
    expect(typeof (mutations as any).Lead_confirmConversion).toBe("function");
  });
  it("exports mutation Lead_confirmProposalSent", () => {
    expect(typeof (mutations as any).Lead_confirmProposalSent).toBe("function");
  });
  it("exports mutation Lead_reviseDetails", () => {
    expect(typeof (mutations as any).Lead_reviseDetails).toBe("function");
  });
  it("exports mutation Lead_stageConversion", () => {
    expect(typeof (mutations as any).Lead_stageConversion).toBe("function");
  });
  it("exports mutation Lead_stageProposal", () => {
    expect(typeof (mutations as any).Lead_stageProposal).toBe("function");
  });
  it("exports mutation Lead_updatePipeline", () => {
    expect(typeof (mutations as any).Lead_updatePipeline).toBe("function");
  });
  it("exports mutation Menu_archive", () => {
    expect(typeof (mutations as any).Menu_archive).toBe("function");
  });
  it("exports mutation Menu_draft", () => {
    expect(typeof (mutations as any).Menu_draft).toBe("function");
  });
  it("exports mutation Menu_markPublished", () => {
    expect(typeof (mutations as any).Menu_markPublished).toBe("function");
  });
  it("exports mutation Menu_restore", () => {
    expect(typeof (mutations as any).Menu_restore).toBe("function");
  });
  it("exports mutation Menu_reviseDetails", () => {
    expect(typeof (mutations as any).Menu_reviseDetails).toBe("function");
  });
  it("exports mutation Menu_unpublish", () => {
    expect(typeof (mutations as any).Menu_unpublish).toBe("function");
  });
  it("exports mutation Menu_updatePricing", () => {
    expect(typeof (mutations as any).Menu_updatePricing).toBe("function");
  });
  it("exports mutation MenuDish_add", () => {
    expect(typeof (mutations as any).MenuDish_add).toBe("function");
  });
  it("exports mutation MenuDish_remove", () => {
    expect(typeof (mutations as any).MenuDish_remove).toBe("function");
  });
  it("exports mutation MenuDish_updateDetails", () => {
    expect(typeof (mutations as any).MenuDish_updateDetails).toBe("function");
  });
  it("exports mutation MenuDish_updateSellingPrice", () => {
    expect(typeof (mutations as any).MenuDish_updateSellingPrice).toBe("function");
  });
  it("exports mutation Organization_configureBranding", () => {
    expect(typeof (mutations as any).Organization_configureBranding).toBe("function");
  });
  it("exports mutation Organization_deactivate", () => {
    expect(typeof (mutations as any).Organization_deactivate).toBe("function");
  });
  it("exports mutation Organization_reactivate", () => {
    expect(typeof (mutations as any).Organization_reactivate).toBe("function");
  });
  it("exports mutation Organization_register", () => {
    expect(typeof (mutations as any).Organization_register).toBe("function");
  });
  it("exports mutation Organization_rename", () => {
    expect(typeof (mutations as any).Organization_rename).toBe("function");
  });
  it("exports mutation Organization_suspend", () => {
    expect(typeof (mutations as any).Organization_suspend).toBe("function");
  });
  it("exports mutation OrganizationCapabilitySetting_register", () => {
    expect(typeof (mutations as any).OrganizationCapabilitySetting_register).toBe("function");
  });
  it("exports mutation OrganizationCapabilitySetting_setEnabled", () => {
    expect(typeof (mutations as any).OrganizationCapabilitySetting_setEnabled).toBe("function");
  });
  it("exports mutation PackList_cancel", () => {
    expect(typeof (mutations as any).PackList_cancel).toBe("function");
  });
  it("exports mutation PackList_dispatch", () => {
    expect(typeof (mutations as any).PackList_dispatch).toBe("function");
  });
  it("exports mutation PackList_markLoaded", () => {
    expect(typeof (mutations as any).PackList_markLoaded).toBe("function");
  });
  it("exports mutation PackList_markPacked", () => {
    expect(typeof (mutations as any).PackList_markPacked).toBe("function");
  });
  it("exports mutation PackList_open", () => {
    expect(typeof (mutations as any).PackList_open).toBe("function");
  });
  it("exports mutation PackList_startPacking", () => {
    expect(typeof (mutations as any).PackList_startPacking).toBe("function");
  });
  it("exports mutation PackListItem_addItem", () => {
    expect(typeof (mutations as any).PackListItem_addItem).toBe("function");
  });
  it("exports mutation PackListItem_adjustQuantity", () => {
    expect(typeof (mutations as any).PackListItem_adjustQuantity).toBe("function");
  });
  it("exports mutation PackListItem_markMissing", () => {
    expect(typeof (mutations as any).PackListItem_markMissing).toBe("function");
  });
  it("exports mutation PackListItem_markPacked", () => {
    expect(typeof (mutations as any).PackListItem_markPacked).toBe("function");
  });
  it("exports mutation Payment_beginProcessing", () => {
    expect(typeof (mutations as any).Payment_beginProcessing).toBe("function");
  });
  it("exports mutation Payment_fail", () => {
    expect(typeof (mutations as any).Payment_fail).toBe("function");
  });
  it("exports mutation Payment_reassignClient", () => {
    expect(typeof (mutations as any).Payment_reassignClient).toBe("function");
  });
  it("exports mutation Payment_record", () => {
    expect(typeof (mutations as any).Payment_record).toBe("function");
  });
  it("exports mutation Payment_refund", () => {
    expect(typeof (mutations as any).Payment_refund).toBe("function");
  });
  it("exports mutation Payment_settle", () => {
    expect(typeof (mutations as any).Payment_settle).toBe("function");
  });
  it("exports mutation Payment_stageClientMerge", () => {
    expect(typeof (mutations as any).Payment_stageClientMerge).toBe("function");
  });
  it("exports mutation PaymentMethod_clearDefault", () => {
    expect(typeof (mutations as any).PaymentMethod_clearDefault).toBe("function");
  });
  it("exports mutation PaymentMethod_expire", () => {
    expect(typeof (mutations as any).PaymentMethod_expire).toBe("function");
  });
  it("exports mutation PaymentMethod_invalidate", () => {
    expect(typeof (mutations as any).PaymentMethod_invalidate).toBe("function");
  });
  it("exports mutation PaymentMethod_makeDefault", () => {
    expect(typeof (mutations as any).PaymentMethod_makeDefault).toBe("function");
  });
  it("exports mutation PaymentMethod_reactivate", () => {
    expect(typeof (mutations as any).PaymentMethod_reactivate).toBe("function");
  });
  it("exports mutation PaymentMethod_reassignClient", () => {
    expect(typeof (mutations as any).PaymentMethod_reassignClient).toBe("function");
  });
  it("exports mutation PaymentMethod_register", () => {
    expect(typeof (mutations as any).PaymentMethod_register).toBe("function");
  });
  it("exports mutation PaymentMethod_remove", () => {
    expect(typeof (mutations as any).PaymentMethod_remove).toBe("function");
  });
  it("exports mutation PaymentMethod_stageClientMerge", () => {
    expect(typeof (mutations as any).PaymentMethod_stageClientMerge).toBe("function");
  });
  it("exports mutation PayrollInput_finalize", () => {
    expect(typeof (mutations as any).PayrollInput_finalize).toBe("function");
  });
  it("exports mutation PayrollInput_markVoided", () => {
    expect(typeof (mutations as any).PayrollInput_markVoided).toBe("function");
  });
  it("exports mutation PayrollInput_prepare", () => {
    expect(typeof (mutations as any).PayrollInput_prepare).toBe("function");
  });
  it("exports mutation Person_assignRole", () => {
    expect(typeof (mutations as any).Person_assignRole).toBe("function");
  });
  it("exports mutation Person_correctIdentity", () => {
    expect(typeof (mutations as any).Person_correctIdentity).toBe("function");
  });
  it("exports mutation Person_deactivate", () => {
    expect(typeof (mutations as any).Person_deactivate).toBe("function");
  });
  it("exports mutation Person_hire", () => {
    expect(typeof (mutations as any).Person_hire).toBe("function");
  });
  it("exports mutation Person_reactivate", () => {
    expect(typeof (mutations as any).Person_reactivate).toBe("function");
  });
  it("exports mutation Person_terminate", () => {
    expect(typeof (mutations as any).Person_terminate).toBe("function");
  });
  it("exports mutation PrepTask_cancel", () => {
    expect(typeof (mutations as any).PrepTask_cancel).toBe("function");
  });
  it("exports mutation PrepTask_claim", () => {
    expect(typeof (mutations as any).PrepTask_claim).toBe("function");
  });
  it("exports mutation PrepTask_complete", () => {
    expect(typeof (mutations as any).PrepTask_complete).toBe("function");
  });
  it("exports mutation PrepTask_markBlocked", () => {
    expect(typeof (mutations as any).PrepTask_markBlocked).toBe("function");
  });
  it("exports mutation PrepTask_open", () => {
    expect(typeof (mutations as any).PrepTask_open).toBe("function");
  });
  it("exports mutation PrepTask_refreshGenerated", () => {
    expect(typeof (mutations as any).PrepTask_refreshGenerated).toBe("function");
  });
  it("exports mutation PrepTask_release", () => {
    expect(typeof (mutations as any).PrepTask_release).toBe("function");
  });
  it("exports mutation PrepTask_revise", () => {
    expect(typeof (mutations as any).PrepTask_revise).toBe("function");
  });
  it("exports mutation PrepTask_start", () => {
    expect(typeof (mutations as any).PrepTask_start).toBe("function");
  });
  it("exports mutation PrepTask_unblock", () => {
    expect(typeof (mutations as any).PrepTask_unblock).toBe("function");
  });
  it("exports mutation PrepTaskDependency_declare", () => {
    expect(typeof (mutations as any).PrepTaskDependency_declare).toBe("function");
  });
  it("exports mutation PrepTaskDependency_satisfy", () => {
    expect(typeof (mutations as any).PrepTaskDependency_satisfy).toBe("function");
  });
  it("exports mutation ProductionBatch_cancel", () => {
    expect(typeof (mutations as any).ProductionBatch_cancel).toBe("function");
  });
  it("exports mutation ProductionBatch_complete", () => {
    expect(typeof (mutations as any).ProductionBatch_complete).toBe("function");
  });
  it("exports mutation ProductionBatch_plan", () => {
    expect(typeof (mutations as any).ProductionBatch_plan).toBe("function");
  });
  it("exports mutation ProductionBatch_start", () => {
    expect(typeof (mutations as any).ProductionBatch_start).toBe("function");
  });
  it("exports mutation Proposal_accept", () => {
    expect(typeof (mutations as any).Proposal_accept).toBe("function");
  });
  it("exports mutation Proposal_decline", () => {
    expect(typeof (mutations as any).Proposal_decline).toBe("function");
  });
  it("exports mutation Proposal_draft", () => {
    expect(typeof (mutations as any).Proposal_draft).toBe("function");
  });
  it("exports mutation Proposal_expire", () => {
    expect(typeof (mutations as any).Proposal_expire).toBe("function");
  });
  it("exports mutation Proposal_markViewed", () => {
    expect(typeof (mutations as any).Proposal_markViewed).toBe("function");
  });
  it("exports mutation Proposal_reassignClient", () => {
    expect(typeof (mutations as any).Proposal_reassignClient).toBe("function");
  });
  it("exports mutation Proposal_send", () => {
    expect(typeof (mutations as any).Proposal_send).toBe("function");
  });
  it("exports mutation Proposal_stageClientMerge", () => {
    expect(typeof (mutations as any).Proposal_stageClientMerge).toBe("function");
  });
  it("exports mutation PurchaseNeed_assignToDraft", () => {
    expect(typeof (mutations as any).PurchaseNeed_assignToDraft).toBe("function");
  });
  it("exports mutation PurchaseNeed_cancel", () => {
    expect(typeof (mutations as any).PurchaseNeed_cancel).toBe("function");
  });
  it("exports mutation PurchaseNeed_create", () => {
    expect(typeof (mutations as any).PurchaseNeed_create).toBe("function");
  });
  it("exports mutation PurchaseNeed_markDraftOrdered", () => {
    expect(typeof (mutations as any).PurchaseNeed_markDraftOrdered).toBe("function");
  });
  it("exports mutation PurchaseNeed_markFulfilled", () => {
    expect(typeof (mutations as any).PurchaseNeed_markFulfilled).toBe("function");
  });
  it("exports mutation PurchaseNeed_markOrdered", () => {
    expect(typeof (mutations as any).PurchaseNeed_markOrdered).toBe("function");
  });
  it("exports mutation PurchaseNeed_reviseRequired", () => {
    expect(typeof (mutations as any).PurchaseNeed_reviseRequired).toBe("function");
  });
  it("exports mutation Qualification_expire", () => {
    expect(typeof (mutations as any).Qualification_expire).toBe("function");
  });
  it("exports mutation Qualification_grant", () => {
    expect(typeof (mutations as any).Qualification_grant).toBe("function");
  });
  it("exports mutation Qualification_revoke", () => {
    expect(typeof (mutations as any).Qualification_revoke).toBe("function");
  });
  it("exports mutation QualityCheck_fail", () => {
    expect(typeof (mutations as any).QualityCheck_fail).toBe("function");
  });
  it("exports mutation QualityCheck_open", () => {
    expect(typeof (mutations as any).QualityCheck_open).toBe("function");
  });
  it("exports mutation QualityCheck_pass", () => {
    expect(typeof (mutations as any).QualityCheck_pass).toBe("function");
  });
  it("exports mutation QualityCheck_reinspect", () => {
    expect(typeof (mutations as any).QualityCheck_reinspect).toBe("function");
  });
  it("exports mutation Recipe_draft", () => {
    expect(typeof (mutations as any).Recipe_draft).toBe("function");
  });
  it("exports mutation Recipe_publishVersion", () => {
    expect(typeof (mutations as any).Recipe_publishVersion).toBe("function");
  });
  it("exports mutation Recipe_retire", () => {
    expect(typeof (mutations as any).Recipe_retire).toBe("function");
  });
  it("exports mutation Recipe_retract", () => {
    expect(typeof (mutations as any).Recipe_retract).toBe("function");
  });
  it("exports mutation Recipe_reviseDraft", () => {
    expect(typeof (mutations as any).Recipe_reviseDraft).toBe("function");
  });
  it("exports mutation RecipeImport_approveReview", () => {
    expect(typeof (mutations as any).RecipeImport_approveReview).toBe("function");
  });
  it("exports mutation RecipeImport_beginFinalization", () => {
    expect(typeof (mutations as any).RecipeImport_beginFinalization).toBe("function");
  });
  it("exports mutation RecipeImport_beginReview", () => {
    expect(typeof (mutations as any).RecipeImport_beginReview).toBe("function");
  });
  it("exports mutation RecipeImport_cancel", () => {
    expect(typeof (mutations as any).RecipeImport_cancel).toBe("function");
  });
  it("exports mutation RecipeImport_complete", () => {
    expect(typeof (mutations as any).RecipeImport_complete).toBe("function");
  });
  it("exports mutation RecipeImport_markFailed", () => {
    expect(typeof (mutations as any).RecipeImport_markFailed).toBe("function");
  });
  it("exports mutation RecipeImport_recordParse", () => {
    expect(typeof (mutations as any).RecipeImport_recordParse).toBe("function");
  });
  it("exports mutation RecipeImport_recordRecipe", () => {
    expect(typeof (mutations as any).RecipeImport_recordRecipe).toBe("function");
  });
  it("exports mutation RecipeImport_recordResolutionProgress", () => {
    expect(typeof (mutations as any).RecipeImport_recordResolutionProgress).toBe("function");
  });
  it("exports mutation RecipeImport_resumeReview", () => {
    expect(typeof (mutations as any).RecipeImport_resumeReview).toBe("function");
  });
  it("exports mutation RecipeImport_upload", () => {
    expect(typeof (mutations as any).RecipeImport_upload).toBe("function");
  });
  it("exports mutation RecipeImportLine_attachCreatedIngredient", () => {
    expect(typeof (mutations as any).RecipeImportLine_attachCreatedIngredient).toBe("function");
  });
  it("exports mutation RecipeImportLine_confirmExisting", () => {
    expect(typeof (mutations as any).RecipeImportLine_confirmExisting).toBe("function");
  });
  it("exports mutation RecipeImportLine_confirmNew", () => {
    expect(typeof (mutations as any).RecipeImportLine_confirmNew).toBe("function");
  });
  it("exports mutation RecipeImportLine_discard", () => {
    expect(typeof (mutations as any).RecipeImportLine_discard).toBe("function");
  });
  it("exports mutation RecipeImportLine_markNew", () => {
    expect(typeof (mutations as any).RecipeImportLine_markNew).toBe("function");
  });
  it("exports mutation RecipeImportLine_resetResolution", () => {
    expect(typeof (mutations as any).RecipeImportLine_resetResolution).toBe("function");
  });
  it("exports mutation RecipeImportLine_stage", () => {
    expect(typeof (mutations as any).RecipeImportLine_stage).toBe("function");
  });
  it("exports mutation RecipeImportLine_suggestExactMatch", () => {
    expect(typeof (mutations as any).RecipeImportLine_suggestExactMatch).toBe("function");
  });
  it("exports mutation RecipeImportLine_suggestPossibleMatches", () => {
    expect(typeof (mutations as any).RecipeImportLine_suggestPossibleMatches).toBe("function");
  });
  it("exports mutation RecipeIngredient_add", () => {
    expect(typeof (mutations as any).RecipeIngredient_add).toBe("function");
  });
  it("exports mutation RecipeIngredient_adjustQuantity", () => {
    expect(typeof (mutations as any).RecipeIngredient_adjustQuantity).toBe("function");
  });
  it("exports mutation RecipeIngredient_remove", () => {
    expect(typeof (mutations as any).RecipeIngredient_remove).toBe("function");
  });
  it("exports mutation RecipeStep_add", () => {
    expect(typeof (mutations as any).RecipeStep_add).toBe("function");
  });
  it("exports mutation RecipeStep_remove", () => {
    expect(typeof (mutations as any).RecipeStep_remove).toBe("function");
  });
  it("exports mutation RecipeStep_revise", () => {
    expect(typeof (mutations as any).RecipeStep_revise).toBe("function");
  });
  it("exports mutation RecurringAvailability_declare", () => {
    expect(typeof (mutations as any).RecurringAvailability_declare).toBe("function");
  });
  it("exports mutation RecurringAvailability_withdraw", () => {
    expect(typeof (mutations as any).RecurringAvailability_withdraw).toBe("function");
  });
  it("exports mutation SavedReportDefinition_archive", () => {
    expect(typeof (mutations as any).SavedReportDefinition_archive).toBe("function");
  });
  it("exports mutation SavedReportDefinition_changeSharing", () => {
    expect(typeof (mutations as any).SavedReportDefinition_changeSharing).toBe("function");
  });
  it("exports mutation SavedReportDefinition_createDefinition", () => {
    expect(typeof (mutations as any).SavedReportDefinition_createDefinition).toBe("function");
  });
  it("exports mutation SavedReportDefinition_rename", () => {
    expect(typeof (mutations as any).SavedReportDefinition_rename).toBe("function");
  });
  it("exports mutation SavedReportDefinition_restore", () => {
    expect(typeof (mutations as any).SavedReportDefinition_restore).toBe("function");
  });
  it("exports mutation SavedReportDefinition_updateDefinition", () => {
    expect(typeof (mutations as any).SavedReportDefinition_updateDefinition).toBe("function");
  });
  it("exports mutation Shift_applyApprovedSwap", () => {
    expect(typeof (mutations as any).Shift_applyApprovedSwap).toBe("function");
  });
  it("exports mutation Shift_cancel", () => {
    expect(typeof (mutations as any).Shift_cancel).toBe("function");
  });
  it("exports mutation Shift_complete", () => {
    expect(typeof (mutations as any).Shift_complete).toBe("function");
  });
  it("exports mutation Shift_markNoShow", () => {
    expect(typeof (mutations as any).Shift_markNoShow).toBe("function");
  });
  it("exports mutation Shift_schedule", () => {
    expect(typeof (mutations as any).Shift_schedule).toBe("function");
  });
  it("exports mutation Shift_stageApprovedSwap", () => {
    expect(typeof (mutations as any).Shift_stageApprovedSwap).toBe("function");
  });
  it("exports mutation Shift_start", () => {
    expect(typeof (mutations as any).Shift_start).toBe("function");
  });
  it("exports mutation ShiftSwapRequest_accept", () => {
    expect(typeof (mutations as any).ShiftSwapRequest_accept).toBe("function");
  });
  it("exports mutation ShiftSwapRequest_approve", () => {
    expect(typeof (mutations as any).ShiftSwapRequest_approve).toBe("function");
  });
  it("exports mutation ShiftSwapRequest_decline", () => {
    expect(typeof (mutations as any).ShiftSwapRequest_decline).toBe("function");
  });
  it("exports mutation ShiftSwapRequest_propose", () => {
    expect(typeof (mutations as any).ShiftSwapRequest_propose).toBe("function");
  });
  it("exports mutation ShiftSwapRequest_reject", () => {
    expect(typeof (mutations as any).ShiftSwapRequest_reject).toBe("function");
  });
  it("exports mutation ShiftSwapRequest_withdraw", () => {
    expect(typeof (mutations as any).ShiftSwapRequest_withdraw).toBe("function");
  });
  it("exports mutation ShiftType_define", () => {
    expect(typeof (mutations as any).ShiftType_define).toBe("function");
  });
  it("exports mutation ShiftType_reactivate", () => {
    expect(typeof (mutations as any).ShiftType_reactivate).toBe("function");
  });
  it("exports mutation ShiftType_retire", () => {
    expect(typeof (mutations as any).ShiftType_retire).toBe("function");
  });
  it("exports mutation StockCountLine_confirmLedgerMatch", () => {
    expect(typeof (mutations as any).StockCountLine_confirmLedgerMatch).toBe("function");
  });
  it("exports mutation StockCountLine_freeze", () => {
    expect(typeof (mutations as any).StockCountLine_freeze).toBe("function");
  });
  it("exports mutation StockCountLine_reconcileVariance", () => {
    expect(typeof (mutations as any).StockCountLine_reconcileVariance).toBe("function");
  });
  it("exports mutation StockCountLine_recordCount", () => {
    expect(typeof (mutations as any).StockCountLine_recordCount).toBe("function");
  });
  it("exports mutation StockCountLine_reviseCount", () => {
    expect(typeof (mutations as any).StockCountLine_reviseCount).toBe("function");
  });
  it("exports mutation StockCountSession_close", () => {
    expect(typeof (mutations as any).StockCountSession_close).toBe("function");
  });
  it("exports mutation StockCountSession_start", () => {
    expect(typeof (mutations as any).StockCountSession_start).toBe("function");
  });
  it("exports mutation StockTransfer_record", () => {
    expect(typeof (mutations as any).StockTransfer_record).toBe("function");
  });
  it("exports mutation StorageLocation_activate", () => {
    expect(typeof (mutations as any).StorageLocation_activate).toBe("function");
  });
  it("exports mutation StorageLocation_deactivate", () => {
    expect(typeof (mutations as any).StorageLocation_deactivate).toBe("function");
  });
  it("exports mutation StorageLocation_register", () => {
    expect(typeof (mutations as any).StorageLocation_register).toBe("function");
  });
  it("exports mutation StorageLocation_reviseDetails", () => {
    expect(typeof (mutations as any).StorageLocation_reviseDetails).toBe("function");
  });
  it("exports mutation TaxRate_define", () => {
    expect(typeof (mutations as any).TaxRate_define).toBe("function");
  });
  it("exports mutation TaxRate_revise", () => {
    expect(typeof (mutations as any).TaxRate_revise).toBe("function");
  });
  it("exports mutation TaxRate_setActive", () => {
    expect(typeof (mutations as any).TaxRate_setActive).toBe("function");
  });
  it("exports mutation TimeOffRequest_approve", () => {
    expect(typeof (mutations as any).TimeOffRequest_approve).toBe("function");
  });
  it("exports mutation TimeOffRequest_decline", () => {
    expect(typeof (mutations as any).TimeOffRequest_decline).toBe("function");
  });
  it("exports mutation TimeOffRequest_submit", () => {
    expect(typeof (mutations as any).TimeOffRequest_submit).toBe("function");
  });
  it("exports mutation TimeRecord_clockIn", () => {
    expect(typeof (mutations as any).TimeRecord_clockIn).toBe("function");
  });
  it("exports mutation TimeRecord_clockOut", () => {
    expect(typeof (mutations as any).TimeRecord_clockOut).toBe("function");
  });
  it("exports mutation TimeRecord_correct", () => {
    expect(typeof (mutations as any).TimeRecord_correct).toBe("function");
  });
  it("exports mutation TrainingCompletion_record", () => {
    expect(typeof (mutations as any).TrainingCompletion_record).toBe("function");
  });
  it("exports mutation TrainingModule_define", () => {
    expect(typeof (mutations as any).TrainingModule_define).toBe("function");
  });
  it("exports mutation TrainingModule_reactivate", () => {
    expect(typeof (mutations as any).TrainingModule_reactivate).toBe("function");
  });
  it("exports mutation TrainingModule_retire", () => {
    expect(typeof (mutations as any).TrainingModule_retire).toBe("function");
  });
  it("exports mutation Vehicle_register", () => {
    expect(typeof (mutations as any).Vehicle_register).toBe("function");
  });
  it("exports mutation Vehicle_reviseDetails", () => {
    expect(typeof (mutations as any).Vehicle_reviseDetails).toBe("function");
  });
  it("exports mutation Vehicle_updateOperationalStatus", () => {
    expect(typeof (mutations as any).Vehicle_updateOperationalStatus).toBe("function");
  });
  it("exports mutation Vendor_onboard", () => {
    expect(typeof (mutations as any).Vendor_onboard).toBe("function");
  });
  it("exports mutation Vendor_reinstate", () => {
    expect(typeof (mutations as any).Vendor_reinstate).toBe("function");
  });
  it("exports mutation Vendor_suspend", () => {
    expect(typeof (mutations as any).Vendor_suspend).toBe("function");
  });
  it("exports mutation Vendor_terminate", () => {
    expect(typeof (mutations as any).Vendor_terminate).toBe("function");
  });
  it("exports mutation Vendor_updateDetails", () => {
    expect(typeof (mutations as any).Vendor_updateDetails).toBe("function");
  });
  it("exports mutation VendorContact_add", () => {
    expect(typeof (mutations as any).VendorContact_add).toBe("function");
  });
  it("exports mutation VendorContact_remove", () => {
    expect(typeof (mutations as any).VendorContact_remove).toBe("function");
  });
  it("exports mutation VendorContact_update", () => {
    expect(typeof (mutations as any).VendorContact_update).toBe("function");
  });
  it("exports mutation VendorContract_activate", () => {
    expect(typeof (mutations as any).VendorContract_activate).toBe("function");
  });
  it("exports mutation VendorContract_draft", () => {
    expect(typeof (mutations as any).VendorContract_draft).toBe("function");
  });
  it("exports mutation VendorContract_markExpired", () => {
    expect(typeof (mutations as any).VendorContract_markExpired).toBe("function");
  });
  it("exports mutation VendorContract_terminate", () => {
    expect(typeof (mutations as any).VendorContract_terminate).toBe("function");
  });
  it("exports mutation VendorContract_updateTerms", () => {
    expect(typeof (mutations as any).VendorContract_updateTerms).toBe("function");
  });
  it("exports mutation VendorContractPriceTier_add", () => {
    expect(typeof (mutations as any).VendorContractPriceTier_add).toBe("function");
  });
  it("exports mutation VendorContractPriceTier_remove", () => {
    expect(typeof (mutations as any).VendorContractPriceTier_remove).toBe("function");
  });
  it("exports mutation VendorContractPriceTier_update", () => {
    expect(typeof (mutations as any).VendorContractPriceTier_update).toBe("function");
  });
  it("exports mutation VendorOrder_approve", () => {
    expect(typeof (mutations as any).VendorOrder_approve).toBe("function");
  });
  it("exports mutation VendorOrder_cancel", () => {
    expect(typeof (mutations as any).VendorOrder_cancel).toBe("function");
  });
  it("exports mutation VendorOrder_confirm", () => {
    expect(typeof (mutations as any).VendorOrder_confirm).toBe("function");
  });
  it("exports mutation VendorOrder_ensureWeeklyDraft", () => {
    expect(typeof (mutations as any).VendorOrder_ensureWeeklyDraft).toBe("function");
  });
  it("exports mutation VendorOrder_markPartiallyReceived", () => {
    expect(typeof (mutations as any).VendorOrder_markPartiallyReceived).toBe("function");
  });
  it("exports mutation VendorOrder_markReceived", () => {
    expect(typeof (mutations as any).VendorOrder_markReceived).toBe("function");
  });
  it("exports mutation VendorOrder_open", () => {
    expect(typeof (mutations as any).VendorOrder_open).toBe("function");
  });
  it("exports mutation VendorOrder_requestChanges", () => {
    expect(typeof (mutations as any).VendorOrder_requestChanges).toBe("function");
  });
  it("exports mutation VendorOrder_submit", () => {
    expect(typeof (mutations as any).VendorOrder_submit).toBe("function");
  });
  it("exports mutation VendorOrder_submitForApproval", () => {
    expect(typeof (mutations as any).VendorOrder_submitForApproval).toBe("function");
  });
  it("exports mutation VendorOrder_updateTotals", () => {
    expect(typeof (mutations as any).VendorOrder_updateTotals).toBe("function");
  });
  it("exports mutation VendorOrderLine_addLine", () => {
    expect(typeof (mutations as any).VendorOrderLine_addLine).toBe("function");
  });
  it("exports mutation VendorOrderLine_cancelLine", () => {
    expect(typeof (mutations as any).VendorOrderLine_cancelLine).toBe("function");
  });
  it("exports mutation VendorOrderLine_ensureWeeklyLine", () => {
    expect(typeof (mutations as any).VendorOrderLine_ensureWeeklyLine).toBe("function");
  });
  it("exports mutation VendorOrderLine_recordReceipt", () => {
    expect(typeof (mutations as any).VendorOrderLine_recordReceipt).toBe("function");
  });
  it("exports mutation VendorOrderLine_reviseQuantity", () => {
    expect(typeof (mutations as any).VendorOrderLine_reviseQuantity).toBe("function");
  });
  it("exports mutation VendorOrderLineDemand_link", () => {
    expect(typeof (mutations as any).VendorOrderLineDemand_link).toBe("function");
  });
  it("exports mutation VendorOrderLineDemand_retire", () => {
    expect(typeof (mutations as any).VendorOrderLineDemand_retire).toBe("function");
  });
  it("exports mutation VendorOrderLineDemand_revise", () => {
    expect(typeof (mutations as any).VendorOrderLineDemand_revise).toBe("function");
  });
  it("exports mutation Venue_activate", () => {
    expect(typeof (mutations as any).Venue_activate).toBe("function");
  });
  it("exports mutation Venue_changeCapacity", () => {
    expect(typeof (mutations as any).Venue_changeCapacity).toBe("function");
  });
  it("exports mutation Venue_deactivate", () => {
    expect(typeof (mutations as any).Venue_deactivate).toBe("function");
  });
  it("exports mutation Venue_register", () => {
    expect(typeof (mutations as any).Venue_register).toBe("function");
  });
  it("exports mutation Venue_updateDetails", () => {
    expect(typeof (mutations as any).Venue_updateDetails).toBe("function");
  });
  it("exports mutation WasteRecord_record", () => {
    expect(typeof (mutations as any).WasteRecord_record).toBe("function");
  });
  it("exports mutation WasteRecord_voidRecord", () => {
    expect(typeof (mutations as any).WasteRecord_voidRecord).toBe("function");
  });
  it("exports mutation WeeklyPurchasingConfig_configure", () => {
    expect(typeof (mutations as any).WeeklyPurchasingConfig_configure).toBe("function");
  });
  it("exports mutation WeeklyPurchasingConfig_routeNeed", () => {
    expect(typeof (mutations as any).WeeklyPurchasingConfig_routeNeed).toBe("function");
  });
  it("exports mutation WeeklyPurchasingConfig_setOrderApprovalThreshold", () => {
    expect(typeof (mutations as any).WeeklyPurchasingConfig_setOrderApprovalThreshold).toBe("function");
  });
  it("exports mutation WeeklyScheduleNotice_acknowledge", () => {
    expect(typeof (mutations as any).WeeklyScheduleNotice_acknowledge).toBe("function");
  });
  it("exports mutation WeeklyScheduleNotice_publishSchedule", () => {
    expect(typeof (mutations as any).WeeklyScheduleNotice_publishSchedule).toBe("function");
  });
  it("exports mutation WeeklyScheduleNotice_republishSchedule", () => {
    expect(typeof (mutations as any).WeeklyScheduleNotice_republishSchedule).toBe("function");
  });
});

export const MANIFEST_CONTRACT_TEST_COUNT = 395 as const;
