/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as adminWindow from "../adminWindow.js";
import type * as agentHistoryWindow from "../agentHistoryWindow.js";
import type * as apiKeys from "../apiKeys.js";
import type * as archiveDisposition from "../archiveDisposition.js";
import type * as archiveInventory from "../archiveInventory.js";
import type * as archiveInventoryStore from "../archiveInventoryStore.js";
import type * as archiveProvenance from "../archiveProvenance.js";
import type * as assistantConfig from "../assistantConfig.js";
import type * as assistantTurn from "../assistantTurn.js";
import type * as authLink from "../authLink.js";
import type * as authProvision from "../authProvision.js";
import type * as authStatus from "../authStatus.js";
import type * as automaticExplanations from "../automaticExplanations.js";
import type * as brandLogo from "../brandLogo.js";
import type * as candidateHireRevocation from "../candidateHireRevocation.js";
import type * as candidateToTeam from "../candidateToTeam.js";
import type * as cascadePreview from "../cascadePreview.js";
import type * as catalogReclassification from "../catalogReclassification.js";
import type * as chatNotifyPreference from "../chatNotifyPreference.js";
import type * as clientDirectory from "../clientDirectory.js";
import type * as clientPortal from "../clientPortal.js";
import type * as clientPortalPayments from "../clientPortalPayments.js";
import type * as closeoutSources from "../closeoutSources.js";
import type * as commandReceipts from "../commandReceipts.js";
import type * as computed from "../computed.js";
import type * as crons from "../crons.js";
import type * as culinaryDemand from "../culinaryDemand.js";
import type * as culinaryDemandSweep from "../culinaryDemandSweep.js";
import type * as cutover from "../cutover.js";
import type * as deckShareLinks from "../deckShareLinks.js";
import type * as deliveryHealth from "../deliveryHealth.js";
import type * as demandProvenance from "../demandProvenance.js";
import type * as deploymentProbe from "../deploymentProbe.js";
import type * as dishLookup from "../dishLookup.js";
import type * as driverAssignment from "../driverAssignment.js";
import type * as emailNotifications from "../emailNotifications.js";
import type * as equipmentCheckout from "../equipmentCheckout.js";
import type * as eventActivity from "../eventActivity.js";
import type * as eventAutoStage from "../eventAutoStage.js";
import type * as eventCalendarMonth from "../eventCalendarMonth.js";
import type * as eventChecklistApply from "../eventChecklistApply.js";
import type * as eventCreateCatalog from "../eventCreateCatalog.js";
import type * as eventDayBriefing from "../eventDayBriefing.js";
import type * as eventLedger from "../eventLedger.js";
import type * as eventLookup from "../eventLookup.js";
import type * as eventMenuLookup from "../eventMenuLookup.js";
import type * as eventMonthRows from "../eventMonthRows.js";
import type * as eventReadiness from "../eventReadiness.js";
import type * as eventRouteLegs from "../eventRouteLegs.js";
import type * as eventRoutes from "../eventRoutes.js";
import type * as eventTimingRules from "../eventTimingRules.js";
import type * as eventsAreaWindow from "../eventsAreaWindow.js";
import type * as externalRecordLinkLists from "../externalRecordLinkLists.js";
import type * as facilitiesHistoryWindow from "../facilitiesHistoryWindow.js";
import type * as fileStorage from "../fileStorage.js";
import type * as financeWindow from "../financeWindow.js";
import type * as geocode from "../geocode.js";
import type * as goodshuffleItems from "../goodshuffleItems.js";
import type * as googleCalendar from "../googleCalendar.js";
import type * as googleCalendarHealth from "../googleCalendarHealth.js";
import type * as hiringPipeline from "../hiringPipeline.js";
import type * as historyWindow from "../historyWindow.js";
import type * as http from "../http.js";
import type * as importCancel from "../importCancel.js";
import type * as importClientByName from "../importClientByName.js";
import type * as importCommit from "../importCommit.js";
import type * as importCoordinator from "../importCoordinator.js";
import type * as importEventLookups from "../importEventLookups.js";
import type * as importHistory from "../importHistory.js";
import type * as importPaymentMatch from "../importPaymentMatch.js";
import type * as importPipeline from "../importPipeline.js";
import type * as importResolution from "../importResolution.js";
import type * as importServiceStyle from "../importServiceStyle.js";
import type * as importSourceDelta from "../importSourceDelta.js";
import type * as ingredientLookup from "../ingredientLookup.js";
import type * as inventoryAudit from "../inventoryAudit.js";
import type * as inventoryHistoryWindow from "../inventoryHistoryWindow.js";
import type * as inventoryWindow from "../inventoryWindow.js";
import type * as invoiceEmail from "../invoiceEmail.js";
import type * as invoicePayments from "../invoicePayments.js";
import type * as invoiceReminders from "../invoiceReminders.js";
import type * as kmParser from "../kmParser.js";
import type * as laborSummary from "../laborSummary.js";
import type * as ledgerReconstruction from "../ledgerReconstruction.js";
import type * as lib_acceptedRentalHolds from "../lib/acceptedRentalHolds.js";
import type * as lib_approvedDemandPurchasing from "../lib/approvedDemandPurchasing.js";
import type * as lib_assistantToolSurface from "../lib/assistantToolSurface.js";
import type * as lib_authContext from "../lib/authContext.js";
import type * as lib_autoStageFollowUp from "../lib/autoStageFollowUp.js";
import type * as lib_backendRelease from "../lib/backendRelease.js";
import type * as lib_blobs from "../lib/blobs.js";
import type * as lib_bookingAttribution from "../lib/bookingAttribution.js";
import type * as lib_calendarConnectionMirror from "../lib/calendarConnectionMirror.js";
import type * as lib_cancellationReconciliation from "../lib/cancellationReconciliation.js";
import type * as lib_cascadeReceipt from "../lib/cascadeReceipt.js";
import type * as lib_catalogUnitGrams from "../lib/catalogUnitGrams.js";
import type * as lib_cateringPackageOperations from "../lib/cateringPackageOperations.js";
import type * as lib_clerkSignInTicket from "../lib/clerkSignInTicket.js";
import type * as lib_clerkStaffAccount from "../lib/clerkStaffAccount.js";
import type * as lib_clientEmailConsent from "../lib/clientEmailConsent.js";
import type * as lib_clientOutreach from "../lib/clientOutreach.js";
import type * as lib_clientPortalLinks from "../lib/clientPortalLinks.js";
import type * as lib_clientPortalToken from "../lib/clientPortalToken.js";
import type * as lib_clockNow from "../lib/clockNow.js";
import type * as lib_closeoutCommercialReconciliation from "../lib/closeoutCommercialReconciliation.js";
import type * as lib_commandAudit from "../lib/commandAudit.js";
import type * as lib_commandIdempotency from "../lib/commandIdempotency.js";
import type * as lib_culinaryModel_catalogReclassification from "../lib/culinaryModel/catalogReclassification.js";
import type * as lib_culinaryModel_costing from "../lib/culinaryModel/costing.js";
import type * as lib_culinaryModel_demand from "../lib/culinaryModel/demand.js";
import type * as lib_culinaryModel_eventFoodCost from "../lib/culinaryModel/eventFoodCost.js";
import type * as lib_culinaryModel_importMapping from "../lib/culinaryModel/importMapping.js";
import type * as lib_culinaryModel_pricing from "../lib/culinaryModel/pricing.js";
import type * as lib_culinaryModel_productionPlan from "../lib/culinaryModel/productionPlan.js";
import type * as lib_culinaryModel_recipeEdition from "../lib/culinaryModel/recipeEdition.js";
import type * as lib_culinaryModel_tppImport from "../lib/culinaryModel/tppImport.js";
import type * as lib_culinaryModel_units from "../lib/culinaryModel/units.js";
import type * as lib_culinaryModel_unresolvedText from "../lib/culinaryModel/unresolvedText.js";
import type * as lib_culinaryOperations from "../lib/culinaryOperations.js";
import type * as lib_cutoverGate from "../lib/cutoverGate.js";
import type * as lib_cutoverProviders from "../lib/cutoverProviders.js";
import type * as lib_deliveryState from "../lib/deliveryState.js";
import type * as lib_demandChangePreview from "../lib/demandChangePreview.js";
import type * as lib_demandProvenance_DemandProvenanceManager from "../lib/demandProvenance/DemandProvenanceManager.js";
import type * as lib_demandProvenance_DemandSnapshotDiffManager from "../lib/demandProvenance/DemandSnapshotDiffManager.js";
import type * as lib_demandProvenance_types from "../lib/demandProvenance/types.js";
import type * as lib_demandReconciliation from "../lib/demandReconciliation.js";
import type * as lib_dietaryTags from "../lib/dietaryTags.js";
import type * as lib_dishRecipeRepair from "../lib/dishRecipeRepair.js";
import type * as lib_dropOffDelivery from "../lib/dropOffDelivery.js";
import type * as lib_encryption from "../lib/encryption.js";
import type * as lib_equipmentHold from "../lib/equipmentHold.js";
import type * as lib_equipmentReservationAvailability from "../lib/equipmentReservationAvailability.js";
import type * as lib_equipmentReturns from "../lib/equipmentReturns.js";
import type * as lib_eventCancellation from "../lib/eventCancellation.js";
import type * as lib_eventCreateServiceStyleEnsure from "../lib/eventCreateServiceStyleEnsure.js";
import type * as lib_eventDuplicate from "../lib/eventDuplicate.js";
import type * as lib_eventDuplicatePlanning from "../lib/eventDuplicatePlanning.js";
import type * as lib_eventImportTool from "../lib/eventImportTool.js";
import type * as lib_eventNumbering from "../lib/eventNumbering.js";
import type * as lib_eventPacket_commands from "../lib/eventPacket/commands.js";
import type * as lib_eventPacket_dishCosts from "../lib/eventPacket/dishCosts.js";
import type * as lib_eventPacket_finalLock from "../lib/eventPacket/finalLock.js";
import type * as lib_eventPacket_finalLockInput from "../lib/eventPacket/finalLockInput.js";
import type * as lib_eventPacket_reconcileNative from "../lib/eventPacket/reconcileNative.js";
import type * as lib_eventReadinessProjection from "../lib/eventReadinessProjection.js";
import type * as lib_eventRouteLegRead from "../lib/eventRouteLegRead.js";
import type * as lib_eventStaffingOperations from "../lib/eventStaffingOperations.js";
import type * as lib_eventTimingOperations from "../lib/eventTimingOperations.js";
import type * as lib_eventTimingPolicy from "../lib/eventTimingPolicy.js";
import type * as lib_fdcNutrientMapper from "../lib/fdcNutrientMapper.js";
import type * as lib_foodDatabaseClient from "../lib/foodDatabaseClient.js";
import type * as lib_foodDatabaseImage from "../lib/foodDatabaseImage.js";
import type * as lib_foodDensityFromLookup from "../lib/foodDensityFromLookup.js";
import type * as lib_googleCalendar from "../lib/googleCalendar.js";
import type * as lib_googleCalendarBasis from "../lib/googleCalendarBasis.js";
import type * as lib_headcountReconciliation from "../lib/headcountReconciliation.js";
import type * as lib_headcountStaffingReconciliation from "../lib/headcountStaffingReconciliation.js";
import type * as lib_householdVolumeParse from "../lib/householdVolumeParse.js";
import type * as lib_importCompanies from "../lib/importCompanies.js";
import type * as lib_importEquipmentRows from "../lib/importEquipmentRows.js";
import type * as lib_importEventFiles from "../lib/importEventFiles.js";
import type * as lib_importEventStage from "../lib/importEventStage.js";
import type * as lib_importIdentity from "../lib/importIdentity.js";
import type * as lib_importPackListLines from "../lib/importPackListLines.js";
import type * as lib_importRecordHomes from "../lib/importRecordHomes.js";
import type * as lib_importResolution from "../lib/importResolution.js";
import type * as lib_importSourceFields from "../lib/importSourceFields.js";
import type * as lib_ingredientAllergenParser from "../lib/ingredientAllergenParser.js";
import type * as lib_ingredientCatalogImageImport from "../lib/ingredientCatalogImageImport.js";
import type * as lib_ingredientLookupApplyCost from "../lib/ingredientLookupApplyCost.js";
import type * as lib_ingredientLookupApplyNutrition from "../lib/ingredientLookupApplyNutrition.js";
import type * as lib_ingredientLookupAutofill from "../lib/ingredientLookupAutofill.js";
import type * as lib_inventoryEvents from "../lib/inventoryEvents.js";
import type * as lib_invoiceIssueTotals from "../lib/invoiceIssueTotals.js";
import type * as lib_invoiceNumberFormat from "../lib/invoiceNumberFormat.js";
import type * as lib_invoiceNumberSequence from "../lib/invoiceNumberSequence.js";
import type * as lib_invoiceNumbering from "../lib/invoiceNumbering.js";
import type * as lib_invoicePricingReconciliation from "../lib/invoicePricingReconciliation.js";
import type * as lib_invoiceReminderPdf from "../lib/invoiceReminderPdf.js";
import type * as lib_invoiceStripeReconcile from "../lib/invoiceStripeReconcile.js";
import type * as lib_kitchenAccessGate from "../lib/kitchenAccessGate.js";
import type * as lib_lineOverridePurchasing from "../lib/lineOverridePurchasing.js";
import type * as lib_lookupCostBarcodeDiscovery from "../lib/lookupCostBarcodeDiscovery.js";
import type * as lib_lookupCostFromOpenPrices from "../lib/lookupCostFromOpenPrices.js";
import type * as lib_lookupCostTenantFallback from "../lib/lookupCostTenantFallback.js";
import type * as lib_materializationReceipt from "../lib/materializationReceipt.js";
import type * as lib_messageMedia from "../lib/messageMedia.js";
import type * as lib_nutritionUnitScaler from "../lib/nutritionUnitScaler.js";
import type * as lib_oldSystemEventStage from "../lib/oldSystemEventStage.js";
import type * as lib_oneOnlyRules from "../lib/oneOnlyRules.js";
import type * as lib_openFoodFactsMapper from "../lib/openFoodFactsMapper.js";
import type * as lib_operationalEvents from "../lib/operationalEvents.js";
import type * as lib_operationalTransactions from "../lib/operationalTransactions.js";
import type * as lib_orgCapabilityGate from "../lib/orgCapabilityGate.js";
import type * as lib_ownWorkspaceLinks from "../lib/ownWorkspaceLinks.js";
import type * as lib_packReconciliation from "../lib/packReconciliation.js";
import type * as lib_packRuleReconciliation from "../lib/packRuleReconciliation.js";
import type * as lib_packetReconciliation from "../lib/packetReconciliation.js";
import type * as lib_parseSearchQuery from "../lib/parseSearchQuery.js";
import type * as lib_paymentAccounting from "../lib/paymentAccounting.js";
import type * as lib_personAuthPick from "../lib/personAuthPick.js";
import type * as lib_prepRecipeEvents from "../lib/prepRecipeEvents.js";
import type * as lib_prepReconciliation from "../lib/prepReconciliation.js";
import type * as lib_prepTaskQuantity from "../lib/prepTaskQuantity.js";
import type * as lib_prepWorkReconciliation from "../lib/prepWorkReconciliation.js";
import type * as lib_proposalAcceptanceRevision from "../lib/proposalAcceptanceRevision.js";
import type * as lib_proposalBookingVenue from "../lib/proposalBookingVenue.js";
import type * as lib_proposalChangeDraft from "../lib/proposalChangeDraft.js";
import type * as lib_proposalDepositSeed from "../lib/proposalDepositSeed.js";
import type * as lib_proposalDishPricing from "../lib/proposalDishPricing.js";
import type * as lib_proposalDraft from "../lib/proposalDraft.js";
import type * as lib_proposalDraftReport from "../lib/proposalDraftReport.js";
import type * as lib_proposalEventCreation from "../lib/proposalEventCreation.js";
import type * as lib_proposalFollowTotals from "../lib/proposalFollowTotals.js";
import type * as lib_proposalGenerate from "../lib/proposalGenerate.js";
import type * as lib_proposalGenerateSources from "../lib/proposalGenerateSources.js";
import type * as lib_proposalHistoricalAcceptance from "../lib/proposalHistoricalAcceptance.js";
import type * as lib_proposalPictures from "../lib/proposalPictures.js";
import type * as lib_proposalPricing from "../lib/proposalPricing.js";
import type * as lib_proposalReconciliation from "../lib/proposalReconciliation.js";
import type * as lib_proposalRevision from "../lib/proposalRevision.js";
import type * as lib_purchasingEvents from "../lib/purchasingEvents.js";
import type * as lib_purchasingReschedule from "../lib/purchasingReschedule.js";
import type * as lib_qboSync from "../lib/qboSync.js";
import type * as lib_quoteInquiryVenue from "../lib/quoteInquiryVenue.js";
import type * as lib_quoteSelections from "../lib/quoteSelections.js";
import type * as lib_recipeReconciliation from "../lib/recipeReconciliation.js";
import type * as lib_recipeSheetApply from "../lib/recipeSheetApply.js";
import type * as lib_reconciliationFlags from "../lib/reconciliationFlags.js";
import type * as lib_reconciliationIsolation from "../lib/reconciliationIsolation.js";
import type * as lib_reconciliationReceipt from "../lib/reconciliationReceipt.js";
import type * as lib_redactPayload from "../lib/redactPayload.js";
import type * as lib_reminderDelivery from "../lib/reminderDelivery.js";
import type * as lib_rentalReconciliation from "../lib/rentalReconciliation.js";
import type * as lib_routeFollowUp from "../lib/routeFollowUp.js";
import type * as lib_routeProvider from "../lib/routeProvider.js";
import type * as lib_runOfShowAlertLoop from "../lib/runOfShowAlertLoop.js";
import type * as lib_safeMaterialization from "../lib/safeMaterialization.js";
import type * as lib_savedViewOperations from "../lib/savedViewOperations.js";
import type * as lib_serverOnlyStep from "../lib/serverOnlyStep.js";
import type * as lib_servingWeightGrams from "../lib/servingWeightGrams.js";
import type * as lib_shiftSchedulingEvents from "../lib/shiftSchedulingEvents.js";
import type * as lib_shiftTimingProposals from "../lib/shiftTimingProposals.js";
import type * as lib_staffSignInMailer from "../lib/staffSignInMailer.js";
import type * as lib_staffSignInPassword from "../lib/staffSignInPassword.js";
import type * as lib_staffSummaryContent from "../lib/staffSummaryContent.js";
import type * as lib_staffingReconciliation from "../lib/staffingReconciliation.js";
import type * as lib_standInPurchaseNeed from "../lib/standInPurchaseNeed.js";
import type * as lib_stripeCheckout from "../lib/stripeCheckout.js";
import type * as lib_styleReconciliation from "../lib/styleReconciliation.js";
import type * as lib_teamChatRead from "../lib/teamChatRead.js";
import type * as lib_teamChatScan from "../lib/teamChatScan.js";
import type * as lib_tenantSystemCommandRunner from "../lib/tenantSystemCommandRunner.js";
import type * as lib_timingFollowUp from "../lib/timingFollowUp.js";
import type * as lib_tppAccountNative from "../lib/tppAccountNative.js";
import type * as lib_tppHistoryRows from "../lib/tppHistoryRows.js";
import type * as lib_tppUploadContract from "../lib/tppUploadContract.js";
import type * as lib_travelLegEvents from "../lib/travelLegEvents.js";
import type * as lib_twilio from "../lib/twilio.js";
import type * as lib_typicalKitchenDensity from "../lib/typicalKitchenDensity.js";
import type * as lib_usdaCountPortionGrams from "../lib/usdaCountPortionGrams.js";
import type * as lib_vehicleDeliveryAvailability from "../lib/vehicleDeliveryAvailability.js";
import type * as lib_vendorItemPriceHistory from "../lib/vendorItemPriceHistory.js";
import type * as lib_venueFactsSnapshot from "../lib/venueFactsSnapshot.js";
import type * as lib_venueReconciliation from "../lib/venueReconciliation.js";
import type * as lib_volumeUnitMl from "../lib/volumeUnitMl.js";
import type * as logisticsWindow from "../logisticsWindow.js";
import type * as menuRecipeLookup from "../menuRecipeLookup.js";
import type * as messageInbox from "../messageInbox.js";
import type * as messageInboxPages from "../messageInboxPages.js";
import type * as messageReply from "../messageReply.js";
import type * as mutations from "../mutations.js";
import type * as notifications from "../notifications.js";
import type * as openingStock from "../openingStock.js";
import type * as outboundEmailThread from "../outboundEmailThread.js";
import type * as packScans from "../packScans.js";
import type * as packSections from "../packSections.js";
import type * as parallelRun from "../parallelRun.js";
import type * as personEmail from "../personEmail.js";
import type * as personEmployeeNumber from "../personEmployeeNumber.js";
import type * as personalDataErasure from "../personalDataErasure.js";
import type * as personalDataExport from "../personalDataExport.js";
import type * as planWindow from "../planWindow.js";
import type * as productionWindow from "../productionWindow.js";
import type * as proposalEmail from "../proposalEmail.js";
import type * as publicMenu from "../publicMenu.js";
import type * as pushDeviceHealth from "../pushDeviceHealth.js";
import type * as pushSubscriptions from "../pushSubscriptions.js";
import type * as qboSync from "../qboSync.js";
import type * as queries from "../queries.js";
import type * as quickImport from "../quickImport.js";
import type * as quoteBuilder from "../quoteBuilder.js";
import type * as reasonedChanges from "../reasonedChanges.js";
import type * as recipeWindow from "../recipeWindow.js";
import type * as recordHistory from "../recordHistory.js";
import type * as recurringEvents from "../recurringEvents.js";
import type * as rentalSales from "../rentalSales.js";
import type * as rigTrailer from "../rigTrailer.js";
import type * as routePlanner from "../routePlanner.js";
import type * as runOfShowAlerts from "../runOfShowAlerts.js";
import type * as runOfShowAlertsSend from "../runOfShowAlertsSend.js";
import type * as sagas from "../sagas.js";
import type * as schedulePush from "../schedulePush.js";
import type * as schedulePushSend from "../schedulePushSend.js";
import type * as scorecardEventScores from "../scorecardEventScores.js";
import type * as search from "../search.js";
import type * as shareLinks from "../shareLinks.js";
import type * as shiftTimingChanges from "../shiftTimingChanges.js";
import type * as signatureAcceptance from "../signatureAcceptance.js";
import type * as smsAlertClaims from "../smsAlertClaims.js";
import type * as smsAlertTexts from "../smsAlertTexts.js";
import type * as smsAlerts from "../smsAlerts.js";
import type * as sourceProvenance from "../sourceProvenance.js";
import type * as staffSelfReviews from "../staffSelfReviews.js";
import type * as staffShiftSwaps from "../staffShiftSwaps.js";
import type * as staffSignInEmail from "../staffSignInEmail.js";
import type * as staffSummaries from "../staffSummaries.js";
import type * as stripeConnect from "../stripeConnect.js";
import type * as systemHealthNotices from "../systemHealthNotices.js";
import type * as tastingApply from "../tastingApply.js";
import type * as tastingPrep from "../tastingPrep.js";
import type * as teamChat from "../teamChat.js";
import type * as teamChatCursor from "../teamChatCursor.js";
import type * as teamChatPush from "../teamChatPush.js";
import type * as teamChatPushSend from "../teamChatPushSend.js";
import type * as teamChatSend from "../teamChatSend.js";
import type * as todayDesk from "../todayDesk.js";
import type * as tppEquipmentItems from "../tppEquipmentItems.js";
import type * as tppMenuPackages from "../tppMenuPackages.js";
import type * as tppParser from "../tppParser.js";
import type * as tppReportFavorites from "../tppReportFavorites.js";
import type * as tppReports_contacts from "../tppReports/contacts.js";
import type * as tppReports_events from "../tppReports/events.js";
import type * as tppReports_financial from "../tppReports/financial.js";
import type * as tppReports_general from "../tppReports/general.js";
import type * as tppReports_menuItemCosting from "../tppReports/menuItemCosting.js";
import type * as tppReports_options from "../tppReports/options.js";
import type * as tppReports_shared from "../tppReports/shared.js";
import type * as tppUpload from "../tppUpload.js";
import type * as tppUploadFiles from "../tppUploadFiles.js";
import type * as travelFees from "../travelFees.js";
import type * as vehicleAssignment from "../vehicleAssignment.js";
import type * as vendorNames from "../vendorNames.js";
import type * as vendorOrderEmail from "../vendorOrderEmail.js";
import type * as vendorPriceList from "../vendorPriceList.js";
import type * as venueGallery from "../venueGallery.js";
import type * as venueVendorPolicy from "../venueVendorPolicy.js";
import type * as webhookDeliveries from "../webhookDeliveries.js";
import type * as webhookIntegrations from "../webhookIntegrations.js";
import type * as workforceHistoryWindow from "../workforceHistoryWindow.js";
import type * as workforceScheduling from "../workforceScheduling.js";
import type * as workforceWindow from "../workforceWindow.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  adminWindow: typeof adminWindow;
  agentHistoryWindow: typeof agentHistoryWindow;
  apiKeys: typeof apiKeys;
  archiveDisposition: typeof archiveDisposition;
  archiveInventory: typeof archiveInventory;
  archiveInventoryStore: typeof archiveInventoryStore;
  archiveProvenance: typeof archiveProvenance;
  assistantConfig: typeof assistantConfig;
  assistantTurn: typeof assistantTurn;
  authLink: typeof authLink;
  authProvision: typeof authProvision;
  authStatus: typeof authStatus;
  automaticExplanations: typeof automaticExplanations;
  brandLogo: typeof brandLogo;
  candidateHireRevocation: typeof candidateHireRevocation;
  candidateToTeam: typeof candidateToTeam;
  cascadePreview: typeof cascadePreview;
  catalogReclassification: typeof catalogReclassification;
  chatNotifyPreference: typeof chatNotifyPreference;
  clientDirectory: typeof clientDirectory;
  clientPortal: typeof clientPortal;
  clientPortalPayments: typeof clientPortalPayments;
  closeoutSources: typeof closeoutSources;
  commandReceipts: typeof commandReceipts;
  computed: typeof computed;
  crons: typeof crons;
  culinaryDemand: typeof culinaryDemand;
  culinaryDemandSweep: typeof culinaryDemandSweep;
  cutover: typeof cutover;
  deckShareLinks: typeof deckShareLinks;
  deliveryHealth: typeof deliveryHealth;
  demandProvenance: typeof demandProvenance;
  deploymentProbe: typeof deploymentProbe;
  dishLookup: typeof dishLookup;
  driverAssignment: typeof driverAssignment;
  emailNotifications: typeof emailNotifications;
  equipmentCheckout: typeof equipmentCheckout;
  eventActivity: typeof eventActivity;
  eventAutoStage: typeof eventAutoStage;
  eventCalendarMonth: typeof eventCalendarMonth;
  eventChecklistApply: typeof eventChecklistApply;
  eventCreateCatalog: typeof eventCreateCatalog;
  eventDayBriefing: typeof eventDayBriefing;
  eventLedger: typeof eventLedger;
  eventLookup: typeof eventLookup;
  eventMenuLookup: typeof eventMenuLookup;
  eventMonthRows: typeof eventMonthRows;
  eventReadiness: typeof eventReadiness;
  eventRouteLegs: typeof eventRouteLegs;
  eventRoutes: typeof eventRoutes;
  eventTimingRules: typeof eventTimingRules;
  eventsAreaWindow: typeof eventsAreaWindow;
  externalRecordLinkLists: typeof externalRecordLinkLists;
  facilitiesHistoryWindow: typeof facilitiesHistoryWindow;
  fileStorage: typeof fileStorage;
  financeWindow: typeof financeWindow;
  geocode: typeof geocode;
  goodshuffleItems: typeof goodshuffleItems;
  googleCalendar: typeof googleCalendar;
  googleCalendarHealth: typeof googleCalendarHealth;
  hiringPipeline: typeof hiringPipeline;
  historyWindow: typeof historyWindow;
  http: typeof http;
  importCancel: typeof importCancel;
  importClientByName: typeof importClientByName;
  importCommit: typeof importCommit;
  importCoordinator: typeof importCoordinator;
  importEventLookups: typeof importEventLookups;
  importHistory: typeof importHistory;
  importPaymentMatch: typeof importPaymentMatch;
  importPipeline: typeof importPipeline;
  importResolution: typeof importResolution;
  importServiceStyle: typeof importServiceStyle;
  importSourceDelta: typeof importSourceDelta;
  ingredientLookup: typeof ingredientLookup;
  inventoryAudit: typeof inventoryAudit;
  inventoryHistoryWindow: typeof inventoryHistoryWindow;
  inventoryWindow: typeof inventoryWindow;
  invoiceEmail: typeof invoiceEmail;
  invoicePayments: typeof invoicePayments;
  invoiceReminders: typeof invoiceReminders;
  kmParser: typeof kmParser;
  laborSummary: typeof laborSummary;
  ledgerReconstruction: typeof ledgerReconstruction;
  "lib/acceptedRentalHolds": typeof lib_acceptedRentalHolds;
  "lib/approvedDemandPurchasing": typeof lib_approvedDemandPurchasing;
  "lib/assistantToolSurface": typeof lib_assistantToolSurface;
  "lib/authContext": typeof lib_authContext;
  "lib/autoStageFollowUp": typeof lib_autoStageFollowUp;
  "lib/backendRelease": typeof lib_backendRelease;
  "lib/blobs": typeof lib_blobs;
  "lib/bookingAttribution": typeof lib_bookingAttribution;
  "lib/calendarConnectionMirror": typeof lib_calendarConnectionMirror;
  "lib/cancellationReconciliation": typeof lib_cancellationReconciliation;
  "lib/cascadeReceipt": typeof lib_cascadeReceipt;
  "lib/catalogUnitGrams": typeof lib_catalogUnitGrams;
  "lib/cateringPackageOperations": typeof lib_cateringPackageOperations;
  "lib/clerkSignInTicket": typeof lib_clerkSignInTicket;
  "lib/clerkStaffAccount": typeof lib_clerkStaffAccount;
  "lib/clientEmailConsent": typeof lib_clientEmailConsent;
  "lib/clientOutreach": typeof lib_clientOutreach;
  "lib/clientPortalLinks": typeof lib_clientPortalLinks;
  "lib/clientPortalToken": typeof lib_clientPortalToken;
  "lib/clockNow": typeof lib_clockNow;
  "lib/closeoutCommercialReconciliation": typeof lib_closeoutCommercialReconciliation;
  "lib/commandAudit": typeof lib_commandAudit;
  "lib/commandIdempotency": typeof lib_commandIdempotency;
  "lib/culinaryModel/catalogReclassification": typeof lib_culinaryModel_catalogReclassification;
  "lib/culinaryModel/costing": typeof lib_culinaryModel_costing;
  "lib/culinaryModel/demand": typeof lib_culinaryModel_demand;
  "lib/culinaryModel/eventFoodCost": typeof lib_culinaryModel_eventFoodCost;
  "lib/culinaryModel/importMapping": typeof lib_culinaryModel_importMapping;
  "lib/culinaryModel/pricing": typeof lib_culinaryModel_pricing;
  "lib/culinaryModel/productionPlan": typeof lib_culinaryModel_productionPlan;
  "lib/culinaryModel/recipeEdition": typeof lib_culinaryModel_recipeEdition;
  "lib/culinaryModel/tppImport": typeof lib_culinaryModel_tppImport;
  "lib/culinaryModel/units": typeof lib_culinaryModel_units;
  "lib/culinaryModel/unresolvedText": typeof lib_culinaryModel_unresolvedText;
  "lib/culinaryOperations": typeof lib_culinaryOperations;
  "lib/cutoverGate": typeof lib_cutoverGate;
  "lib/cutoverProviders": typeof lib_cutoverProviders;
  "lib/deliveryState": typeof lib_deliveryState;
  "lib/demandChangePreview": typeof lib_demandChangePreview;
  "lib/demandProvenance/DemandProvenanceManager": typeof lib_demandProvenance_DemandProvenanceManager;
  "lib/demandProvenance/DemandSnapshotDiffManager": typeof lib_demandProvenance_DemandSnapshotDiffManager;
  "lib/demandProvenance/types": typeof lib_demandProvenance_types;
  "lib/demandReconciliation": typeof lib_demandReconciliation;
  "lib/dietaryTags": typeof lib_dietaryTags;
  "lib/dishRecipeRepair": typeof lib_dishRecipeRepair;
  "lib/dropOffDelivery": typeof lib_dropOffDelivery;
  "lib/encryption": typeof lib_encryption;
  "lib/equipmentHold": typeof lib_equipmentHold;
  "lib/equipmentReservationAvailability": typeof lib_equipmentReservationAvailability;
  "lib/equipmentReturns": typeof lib_equipmentReturns;
  "lib/eventCancellation": typeof lib_eventCancellation;
  "lib/eventCreateServiceStyleEnsure": typeof lib_eventCreateServiceStyleEnsure;
  "lib/eventDuplicate": typeof lib_eventDuplicate;
  "lib/eventDuplicatePlanning": typeof lib_eventDuplicatePlanning;
  "lib/eventImportTool": typeof lib_eventImportTool;
  "lib/eventNumbering": typeof lib_eventNumbering;
  "lib/eventPacket/commands": typeof lib_eventPacket_commands;
  "lib/eventPacket/dishCosts": typeof lib_eventPacket_dishCosts;
  "lib/eventPacket/finalLock": typeof lib_eventPacket_finalLock;
  "lib/eventPacket/finalLockInput": typeof lib_eventPacket_finalLockInput;
  "lib/eventPacket/reconcileNative": typeof lib_eventPacket_reconcileNative;
  "lib/eventReadinessProjection": typeof lib_eventReadinessProjection;
  "lib/eventRouteLegRead": typeof lib_eventRouteLegRead;
  "lib/eventStaffingOperations": typeof lib_eventStaffingOperations;
  "lib/eventTimingOperations": typeof lib_eventTimingOperations;
  "lib/eventTimingPolicy": typeof lib_eventTimingPolicy;
  "lib/fdcNutrientMapper": typeof lib_fdcNutrientMapper;
  "lib/foodDatabaseClient": typeof lib_foodDatabaseClient;
  "lib/foodDatabaseImage": typeof lib_foodDatabaseImage;
  "lib/foodDensityFromLookup": typeof lib_foodDensityFromLookup;
  "lib/googleCalendar": typeof lib_googleCalendar;
  "lib/googleCalendarBasis": typeof lib_googleCalendarBasis;
  "lib/headcountReconciliation": typeof lib_headcountReconciliation;
  "lib/headcountStaffingReconciliation": typeof lib_headcountStaffingReconciliation;
  "lib/householdVolumeParse": typeof lib_householdVolumeParse;
  "lib/importCompanies": typeof lib_importCompanies;
  "lib/importEquipmentRows": typeof lib_importEquipmentRows;
  "lib/importEventFiles": typeof lib_importEventFiles;
  "lib/importEventStage": typeof lib_importEventStage;
  "lib/importIdentity": typeof lib_importIdentity;
  "lib/importPackListLines": typeof lib_importPackListLines;
  "lib/importRecordHomes": typeof lib_importRecordHomes;
  "lib/importResolution": typeof lib_importResolution;
  "lib/importSourceFields": typeof lib_importSourceFields;
  "lib/ingredientAllergenParser": typeof lib_ingredientAllergenParser;
  "lib/ingredientCatalogImageImport": typeof lib_ingredientCatalogImageImport;
  "lib/ingredientLookupApplyCost": typeof lib_ingredientLookupApplyCost;
  "lib/ingredientLookupApplyNutrition": typeof lib_ingredientLookupApplyNutrition;
  "lib/ingredientLookupAutofill": typeof lib_ingredientLookupAutofill;
  "lib/inventoryEvents": typeof lib_inventoryEvents;
  "lib/invoiceIssueTotals": typeof lib_invoiceIssueTotals;
  "lib/invoiceNumberFormat": typeof lib_invoiceNumberFormat;
  "lib/invoiceNumberSequence": typeof lib_invoiceNumberSequence;
  "lib/invoiceNumbering": typeof lib_invoiceNumbering;
  "lib/invoicePricingReconciliation": typeof lib_invoicePricingReconciliation;
  "lib/invoiceReminderPdf": typeof lib_invoiceReminderPdf;
  "lib/invoiceStripeReconcile": typeof lib_invoiceStripeReconcile;
  "lib/kitchenAccessGate": typeof lib_kitchenAccessGate;
  "lib/lineOverridePurchasing": typeof lib_lineOverridePurchasing;
  "lib/lookupCostBarcodeDiscovery": typeof lib_lookupCostBarcodeDiscovery;
  "lib/lookupCostFromOpenPrices": typeof lib_lookupCostFromOpenPrices;
  "lib/lookupCostTenantFallback": typeof lib_lookupCostTenantFallback;
  "lib/materializationReceipt": typeof lib_materializationReceipt;
  "lib/messageMedia": typeof lib_messageMedia;
  "lib/nutritionUnitScaler": typeof lib_nutritionUnitScaler;
  "lib/oldSystemEventStage": typeof lib_oldSystemEventStage;
  "lib/oneOnlyRules": typeof lib_oneOnlyRules;
  "lib/openFoodFactsMapper": typeof lib_openFoodFactsMapper;
  "lib/operationalEvents": typeof lib_operationalEvents;
  "lib/operationalTransactions": typeof lib_operationalTransactions;
  "lib/orgCapabilityGate": typeof lib_orgCapabilityGate;
  "lib/ownWorkspaceLinks": typeof lib_ownWorkspaceLinks;
  "lib/packReconciliation": typeof lib_packReconciliation;
  "lib/packRuleReconciliation": typeof lib_packRuleReconciliation;
  "lib/packetReconciliation": typeof lib_packetReconciliation;
  "lib/parseSearchQuery": typeof lib_parseSearchQuery;
  "lib/paymentAccounting": typeof lib_paymentAccounting;
  "lib/personAuthPick": typeof lib_personAuthPick;
  "lib/prepRecipeEvents": typeof lib_prepRecipeEvents;
  "lib/prepReconciliation": typeof lib_prepReconciliation;
  "lib/prepTaskQuantity": typeof lib_prepTaskQuantity;
  "lib/prepWorkReconciliation": typeof lib_prepWorkReconciliation;
  "lib/proposalAcceptanceRevision": typeof lib_proposalAcceptanceRevision;
  "lib/proposalBookingVenue": typeof lib_proposalBookingVenue;
  "lib/proposalChangeDraft": typeof lib_proposalChangeDraft;
  "lib/proposalDepositSeed": typeof lib_proposalDepositSeed;
  "lib/proposalDishPricing": typeof lib_proposalDishPricing;
  "lib/proposalDraft": typeof lib_proposalDraft;
  "lib/proposalDraftReport": typeof lib_proposalDraftReport;
  "lib/proposalEventCreation": typeof lib_proposalEventCreation;
  "lib/proposalFollowTotals": typeof lib_proposalFollowTotals;
  "lib/proposalGenerate": typeof lib_proposalGenerate;
  "lib/proposalGenerateSources": typeof lib_proposalGenerateSources;
  "lib/proposalHistoricalAcceptance": typeof lib_proposalHistoricalAcceptance;
  "lib/proposalPictures": typeof lib_proposalPictures;
  "lib/proposalPricing": typeof lib_proposalPricing;
  "lib/proposalReconciliation": typeof lib_proposalReconciliation;
  "lib/proposalRevision": typeof lib_proposalRevision;
  "lib/purchasingEvents": typeof lib_purchasingEvents;
  "lib/purchasingReschedule": typeof lib_purchasingReschedule;
  "lib/qboSync": typeof lib_qboSync;
  "lib/quoteInquiryVenue": typeof lib_quoteInquiryVenue;
  "lib/quoteSelections": typeof lib_quoteSelections;
  "lib/recipeReconciliation": typeof lib_recipeReconciliation;
  "lib/recipeSheetApply": typeof lib_recipeSheetApply;
  "lib/reconciliationFlags": typeof lib_reconciliationFlags;
  "lib/reconciliationIsolation": typeof lib_reconciliationIsolation;
  "lib/reconciliationReceipt": typeof lib_reconciliationReceipt;
  "lib/redactPayload": typeof lib_redactPayload;
  "lib/reminderDelivery": typeof lib_reminderDelivery;
  "lib/rentalReconciliation": typeof lib_rentalReconciliation;
  "lib/routeFollowUp": typeof lib_routeFollowUp;
  "lib/routeProvider": typeof lib_routeProvider;
  "lib/runOfShowAlertLoop": typeof lib_runOfShowAlertLoop;
  "lib/safeMaterialization": typeof lib_safeMaterialization;
  "lib/savedViewOperations": typeof lib_savedViewOperations;
  "lib/serverOnlyStep": typeof lib_serverOnlyStep;
  "lib/servingWeightGrams": typeof lib_servingWeightGrams;
  "lib/shiftSchedulingEvents": typeof lib_shiftSchedulingEvents;
  "lib/shiftTimingProposals": typeof lib_shiftTimingProposals;
  "lib/staffSignInMailer": typeof lib_staffSignInMailer;
  "lib/staffSignInPassword": typeof lib_staffSignInPassword;
  "lib/staffSummaryContent": typeof lib_staffSummaryContent;
  "lib/staffingReconciliation": typeof lib_staffingReconciliation;
  "lib/standInPurchaseNeed": typeof lib_standInPurchaseNeed;
  "lib/stripeCheckout": typeof lib_stripeCheckout;
  "lib/styleReconciliation": typeof lib_styleReconciliation;
  "lib/teamChatRead": typeof lib_teamChatRead;
  "lib/teamChatScan": typeof lib_teamChatScan;
  "lib/tenantSystemCommandRunner": typeof lib_tenantSystemCommandRunner;
  "lib/timingFollowUp": typeof lib_timingFollowUp;
  "lib/tppAccountNative": typeof lib_tppAccountNative;
  "lib/tppHistoryRows": typeof lib_tppHistoryRows;
  "lib/tppUploadContract": typeof lib_tppUploadContract;
  "lib/travelLegEvents": typeof lib_travelLegEvents;
  "lib/twilio": typeof lib_twilio;
  "lib/typicalKitchenDensity": typeof lib_typicalKitchenDensity;
  "lib/usdaCountPortionGrams": typeof lib_usdaCountPortionGrams;
  "lib/vehicleDeliveryAvailability": typeof lib_vehicleDeliveryAvailability;
  "lib/vendorItemPriceHistory": typeof lib_vendorItemPriceHistory;
  "lib/venueFactsSnapshot": typeof lib_venueFactsSnapshot;
  "lib/venueReconciliation": typeof lib_venueReconciliation;
  "lib/volumeUnitMl": typeof lib_volumeUnitMl;
  logisticsWindow: typeof logisticsWindow;
  menuRecipeLookup: typeof menuRecipeLookup;
  messageInbox: typeof messageInbox;
  messageInboxPages: typeof messageInboxPages;
  messageReply: typeof messageReply;
  mutations: typeof mutations;
  notifications: typeof notifications;
  openingStock: typeof openingStock;
  outboundEmailThread: typeof outboundEmailThread;
  packScans: typeof packScans;
  packSections: typeof packSections;
  parallelRun: typeof parallelRun;
  personEmail: typeof personEmail;
  personEmployeeNumber: typeof personEmployeeNumber;
  personalDataErasure: typeof personalDataErasure;
  personalDataExport: typeof personalDataExport;
  planWindow: typeof planWindow;
  productionWindow: typeof productionWindow;
  proposalEmail: typeof proposalEmail;
  publicMenu: typeof publicMenu;
  pushDeviceHealth: typeof pushDeviceHealth;
  pushSubscriptions: typeof pushSubscriptions;
  qboSync: typeof qboSync;
  queries: typeof queries;
  quickImport: typeof quickImport;
  quoteBuilder: typeof quoteBuilder;
  reasonedChanges: typeof reasonedChanges;
  recipeWindow: typeof recipeWindow;
  recordHistory: typeof recordHistory;
  recurringEvents: typeof recurringEvents;
  rentalSales: typeof rentalSales;
  rigTrailer: typeof rigTrailer;
  routePlanner: typeof routePlanner;
  runOfShowAlerts: typeof runOfShowAlerts;
  runOfShowAlertsSend: typeof runOfShowAlertsSend;
  sagas: typeof sagas;
  schedulePush: typeof schedulePush;
  schedulePushSend: typeof schedulePushSend;
  scorecardEventScores: typeof scorecardEventScores;
  search: typeof search;
  shareLinks: typeof shareLinks;
  shiftTimingChanges: typeof shiftTimingChanges;
  signatureAcceptance: typeof signatureAcceptance;
  smsAlertClaims: typeof smsAlertClaims;
  smsAlertTexts: typeof smsAlertTexts;
  smsAlerts: typeof smsAlerts;
  sourceProvenance: typeof sourceProvenance;
  staffSelfReviews: typeof staffSelfReviews;
  staffShiftSwaps: typeof staffShiftSwaps;
  staffSignInEmail: typeof staffSignInEmail;
  staffSummaries: typeof staffSummaries;
  stripeConnect: typeof stripeConnect;
  systemHealthNotices: typeof systemHealthNotices;
  tastingApply: typeof tastingApply;
  tastingPrep: typeof tastingPrep;
  teamChat: typeof teamChat;
  teamChatCursor: typeof teamChatCursor;
  teamChatPush: typeof teamChatPush;
  teamChatPushSend: typeof teamChatPushSend;
  teamChatSend: typeof teamChatSend;
  todayDesk: typeof todayDesk;
  tppEquipmentItems: typeof tppEquipmentItems;
  tppMenuPackages: typeof tppMenuPackages;
  tppParser: typeof tppParser;
  tppReportFavorites: typeof tppReportFavorites;
  "tppReports/contacts": typeof tppReports_contacts;
  "tppReports/events": typeof tppReports_events;
  "tppReports/financial": typeof tppReports_financial;
  "tppReports/general": typeof tppReports_general;
  "tppReports/menuItemCosting": typeof tppReports_menuItemCosting;
  "tppReports/options": typeof tppReports_options;
  "tppReports/shared": typeof tppReports_shared;
  tppUpload: typeof tppUpload;
  tppUploadFiles: typeof tppUploadFiles;
  travelFees: typeof travelFees;
  vehicleAssignment: typeof vehicleAssignment;
  vendorNames: typeof vendorNames;
  vendorOrderEmail: typeof vendorOrderEmail;
  vendorPriceList: typeof vendorPriceList;
  venueGallery: typeof venueGallery;
  venueVendorPolicy: typeof venueVendorPolicy;
  webhookDeliveries: typeof webhookDeliveries;
  webhookIntegrations: typeof webhookIntegrations;
  workforceHistoryWindow: typeof workforceHistoryWindow;
  workforceScheduling: typeof workforceScheduling;
  workforceWindow: typeof workforceWindow;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
