/**
 * Three-way ownership classification for Builder-owned generated files.
 * Compares recorded baseline, disk bytes, and freshly generated candidate.
 */
import {
  changedRegionsVsCandidate,
  createUnifiedDiff,
} from "./projectGenerationDiff";
import { hashContent } from "./projectGenerationPaths";
import type {
  OwnedFileThreeWayClassification,
  ThreeWayConflictDiagnostics,
} from "./projectGenerationTypes";

export interface ThreeWayInputs {
  path: string;
  baselineDigest: string;
  /** Exact prior generated bytes when recoverable; null if unavailable. */
  baselineContent: string | null;
  currentContent: string;
  candidateContent: string;
}

export interface ThreeWayDecision {
  classification: OwnedFileThreeWayClassification;
  currentDigest: string;
  candidateDigest: string;
  diagnostics: ThreeWayConflictDiagnostics | null;
}

export function classifyOwnedFileThreeWay(
  input: ThreeWayInputs,
): ThreeWayDecision {
  const currentDigest = hashContent(input.currentContent);
  const candidateDigest = hashContent(input.candidateContent);
  const currentEqualsBaseline = currentDigest === input.baselineDigest;
  const currentEqualsCandidate =
    input.currentContent === input.candidateContent;

  let classification: OwnedFileThreeWayClassification;
  if (currentEqualsBaseline && currentEqualsCandidate) {
    classification = "no-op";
  } else if (currentEqualsBaseline && !currentEqualsCandidate) {
    classification = "normal-update";
  } else if (!currentEqualsBaseline && currentEqualsCandidate) {
    classification = "safe-ledger-repair";
  } else {
    classification = "genuine-conflict";
  }

  if (classification !== "genuine-conflict") {
    return {
      classification,
      currentDigest,
      candidateDigest,
      diagnostics: null,
    };
  }

  const baselineAvailable = input.baselineContent !== null;
  const baselineToCurrentDiff = baselineAvailable
    ? createUnifiedDiff(
        `${input.path} (baseline)`,
        input.baselineContent!,
        `${input.path} (current)`,
        input.currentContent,
      )
    : [
        `Baseline content unavailable for digest ${input.baselineDigest}.`,
        "The ownership ledger records only the digest; exact prior bytes were not in `.builder/baselines/`.",
        "current → candidate diff is still shown below.",
      ].join("\n");

  const currentToCandidateDiff = createUnifiedDiff(
    `${input.path} (current)`,
    input.currentContent,
    `${input.path} (candidate)`,
    input.candidateContent,
  );

  const changedRegionsInCandidate = baselineAvailable
    ? changedRegionsVsCandidate(
        input.baselineContent!,
        input.currentContent,
        input.candidateContent,
      )
    : [];

  const diagnostics: ThreeWayConflictDiagnostics = {
    classification: "genuine-conflict",
    path: input.path,
    baselineDigest: input.baselineDigest,
    currentDigest,
    candidateDigest,
    baselineAvailable,
    currentMatchesCandidate: false,
    safeLedgerRepairPossible: false,
    baselineToCurrentDiff,
    currentToCandidateDiff,
    changedRegionsInCandidate,
  };

  return {
    classification,
    currentDigest,
    candidateDigest,
    diagnostics,
  };
}

export function formatThreeWayConflictMessage(
  diagnostics: ThreeWayConflictDiagnostics,
): string {
  const lines = [
    "Genuine ownership conflict — Builder will not overwrite or adopt.",
    `File: ${diagnostics.path}`,
    `Baseline digest:  ${diagnostics.baselineDigest}`,
    `Current digest:   ${diagnostics.currentDigest}`,
    `Candidate digest: ${diagnostics.candidateDigest}`,
    `Current matches fresh generated output: ${diagnostics.currentMatchesCandidate ? "yes" : "no"}`,
    `Safe automatic ledger repair possible: ${diagnostics.safeLedgerRepairPossible ? "yes" : "no"}`,
    "",
    "Do not hand-edit `.builder/ownership.json`.",
    "Do not run blind `adopt ownership` — the candidate does not match the current file.",
    "",
    "--- baseline → current ---",
    diagnostics.baselineToCurrentDiff,
    "",
    "--- current → candidate ---",
    diagnostics.currentToCandidateDiff,
  ];

  if (diagnostics.changedRegionsInCandidate.length > 0) {
    lines.push("", "Changed regions (baseline → current) vs candidate:");
    for (const region of diagnostics.changedRegionsInCandidate) {
      const flag = region.appearsInCandidate
        ? "appears in candidate"
        : "not in candidate";
      const lineSpan =
        region.currentLineCount > 1
          ? `${String(region.currentStartLine)}-${String(region.currentStartLine + region.currentLineCount - 1)}`
          : String(region.currentStartLine);
      lines.push(`  - lines ${lineSpan}: ${flag} — ${region.summary}`);
    }
  }

  return lines.join("\n");
}

/** Resolve baseline bytes: store hit, or current file when digests already match. */
export async function resolveBaselineContent(options: {
  baselineDigest: string;
  currentContent: string;
  readFromStore: (digest: string) => Promise<string | null>;
}): Promise<string | null> {
  if (hashContent(options.currentContent) === options.baselineDigest) {
    return options.currentContent;
  }
  return options.readFromStore(options.baselineDigest);
}

export function recordBaselineBlob(
  blobs: Map<string, string>,
  content: string,
): string {
  const digest = hashContent(content);
  blobs.set(digest, content);
  return digest;
}
