/** Shared project-generation types (keeps ownership/planning modules decoupled). */

export type GeneratedFileMap = ReadonlyMap<
  string,
  { readonly content: string }
>;

export interface OwnedFile {
  sha256: string;
  /**
   * Set by `builder adopt ownership` when on-disk content differs from the
   * stock Builder template. Update mode preserves these seams instead of
   * overwriting them with desired stock output.
   */
  baselined?: boolean;
}

export interface PackageOwnership {
  dependencies: Record<string, string>;
  devDependencies: Record<string, string>;
  scripts: Record<string, string>;
}

export interface EditableManifestOwnership {
  /** Capsule-owned editable Manifest source + config paths (never Builder-generated). */
  paths: string[];
  /** Config file among those paths when present. */
  configPath: string | null;
}

export interface OwnershipManifest {
  version: 1;
  files: Record<string, OwnedFile>;
  package: PackageOwnership;
  /** Recorded separately from generated-file digests. */
  editableManifest?: EditableManifestOwnership;
}

export type ProjectGenerationMode = "initial" | "update";

export type ProjectGenerationConflictReason =
  | "initialized-target"
  | "ownership-manifest-missing"
  | "ownership-manifest-invalid"
  | "owned-file-modified"
  | "owned-file-missing"
  | "app-owned-path"
  | "protected-path"
  | "lockfile-protected"
  | "package-entry-modified"
  | "editable-manifest-path";

export type OwnedFileThreeWayClassification =
  "normal-update" | "safe-ledger-repair" | "genuine-conflict" | "no-op";

export interface ThreeWayChangedRegion {
  currentStartLine: number;
  currentLineCount: number;
  summary: string;
  /** Whether this changed region's current-side text appears in the fresh candidate. */
  appearsInCandidate: boolean;
}

export interface ThreeWayConflictDiagnostics {
  classification: "genuine-conflict";
  path: string;
  baselineDigest: string;
  currentDigest: string;
  candidateDigest: string;
  baselineAvailable: boolean;
  currentMatchesCandidate: boolean;
  safeLedgerRepairPossible: boolean;
  baselineToCurrentDiff: string;
  currentToCandidateDiff: string;
  changedRegionsInCandidate: ThreeWayChangedRegion[];
}

export interface ProjectGenerationConflict {
  path: string;
  reason: ProjectGenerationConflictReason;
  message: string;
  /** Present for genuine three-way ownership conflicts. */
  diagnostics?: ThreeWayConflictDiagnostics;
}

export interface ProjectGenerationFollowUp {
  kind: "install" | "convex-deploy";
  message: string;
}

export interface ProjectGenerationPlan {
  mode: ProjectGenerationMode;
  targetDir: string;
  additions: string[];
  modifications: string[];
  conflicts: ProjectGenerationConflict[];
  deletions: string[];
  /** Paths where disk already matched the candidate; only ownership digest was repaired. */
  ledgerRepairs: string[];
  dependencyRequirementsChanged: boolean;
  followUps: ProjectGenerationFollowUp[];
  writes: Record<string, string>;
  nextOwnership: OwnershipManifest;
  preconditions: Record<string, string | null>;
  targetExisted: boolean;
  /**
   * Exact generated bytes to persist under `.builder/baselines/<sha256>` on apply.
   * Keyed by digest; enables baseline→current diffs on future conflicts.
   */
  baselineBlobs: Record<string, string>;
}

export interface PlanProjectGenerationOptions {
  mode: ProjectGenerationMode;
  targetDir: string;
  /** Builder-owned generated output only. */
  files: GeneratedFileMap;
  /**
   * Capsule-owned editable Manifest source/config.
   * Written on initial; preserved (never replaced) on update; never hashed into `files`.
   */
  editableManifestFiles?: GeneratedFileMap;
  editableManifestConfigPath?: string | null;
  destructiveOverride?: boolean;
  /**
   * Paths that leave Builder ownership without deletion (e.g. customized
   * tsconfig.json after shared-config policy relinquishment).
   */
  relinquishOwnership?: readonly string[];
}
