/** Generated by Manifest seed-pack Convex binding — do not edit by hand. */
import { ConvexHttpClient } from "convex/browser";
import { api } from "../convex/_generated/api";

const PACK_ID = "capsule";
const PACK_VERSION = "1.0.0";

export async function seedConvex(deploymentUrl: string): Promise<void> {
  const client = new ConvexHttpClient(deploymentUrl);
  void PACK_ID;
  void PACK_VERSION;
  // skip AvailabilityWindow: no create command in IR (2 rows unused)
  // skip Client: no create command in IR (2 rows unused)
  // skip ClientContact: no create command in IR (2 rows unused)
  // skip Contract: no create command in IR (2 rows unused)
  // skip Delivery: no create command in IR (2 rows unused)
  // skip Dish: no create command in IR (2 rows unused)
  // skip DishRecipe: no create command in IR (2 rows unused)
  // skip DishTask: no create command in IR (2 rows unused)
  // skip Event: no create command in IR (2 rows unused)
  // skip EventAllergenCheck: no create command in IR (2 rows unused)
  // skip EventAssignment: no create command in IR (2 rows unused)
  // skip EventCloseout: no create command in IR (2 rows unused)
  // skip EventDish: no create command in IR (2 rows unused)
  // skip EventGuest: no create command in IR (2 rows unused)
  // skip Incident: no create command in IR (2 rows unused)
  // skip Ingredient: no create command in IR (2 rows unused)
  // skip IngredientDemand: no create command in IR (2 rows unused)
  // skip InventoryItem: no create command in IR (2 rows unused)
  // skip InventoryReservation: no create command in IR (2 rows unused)
  // skip Invoice: no create command in IR (2 rows unused)
  // skip Menu: no create command in IR (2 rows unused)
  // skip MenuDish: no create command in IR (2 rows unused)
  // skip Organization: no create command in IR (2 rows unused)
  // skip PackList: no create command in IR (2 rows unused)
  // skip PackListItem: no create command in IR (2 rows unused)
  // skip Payment: no create command in IR (2 rows unused)
  // skip PaymentMethod: no create command in IR (2 rows unused)
  // skip PayrollInput: no create command in IR (2 rows unused)
  // skip Person: no create command in IR (2 rows unused)
  // skip PrepTask: no create command in IR (2 rows unused)
  // skip ProductionBatch: no create command in IR (2 rows unused)
  // skip Proposal: no create command in IR (2 rows unused)
  // PurchaseNeed → api.mutations.PurchaseNeed_create
  await client.mutation(api.mutations.PurchaseNeed_create, { "eventId": "eventId-purchase-need-1", "ingredientDemandId": "ingredientDemandId-purchase-need-1", "ingredientId": "ingredientId-purchase-need-1", "requiredQuantity": 1, "unit": "demo-unit-1" } as any);
  await client.mutation(api.mutations.PurchaseNeed_create, { "eventId": "eventId-purchase-need-2", "ingredientDemandId": "ingredientDemandId-purchase-need-2", "ingredientId": "ingredientId-purchase-need-2", "requiredQuantity": 2, "unit": "demo-unit-2" } as any);
  // skip Qualification: no create command in IR (2 rows unused)
  // skip QualityCheck: no create command in IR (2 rows unused)
  // skip Recipe: no create command in IR (2 rows unused)
  // skip RecipeImport: no create command in IR (2 rows unused)
  // skip RecipeImportLine: no create command in IR (2 rows unused)
  // skip RecipeIngredient: no create command in IR (2 rows unused)
  // skip RecipeStep: no create command in IR (2 rows unused)
  // skip SavedReportDefinition: no create command in IR (2 rows unused)
  // skip Shift: no create command in IR (2 rows unused)
  // skip SoftDeletable: not a Convex-persistent store (2 rows unused)
  // skip StorageLocation: no create command in IR (2 rows unused)
  // skip TenantScoped: not a Convex-persistent store (2 rows unused)
  // skip TimeRecord: no create command in IR (2 rows unused)
  // skip Vendor: no create command in IR (2 rows unused)
  // skip VendorOrder: no create command in IR (2 rows unused)
  // skip VendorOrderLine: no create command in IR (2 rows unused)
  // skip VendorOrderLineDemand: no create command in IR (2 rows unused)
  // skip Venue: no create command in IR (2 rows unused)
  // skip WasteRecord: no create command in IR (2 rows unused)
}

export const MANIFEST_CONVEX_SEED_BINDING = {
  "packId": "capsule",
  "version": "1.0.0",
  "entities": [
    {
      "entity": "AvailabilityWindow",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "Client",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "ClientContact",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "Contract",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "Delivery",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "Dish",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "DishRecipe",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "DishTask",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "Event",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "EventAllergenCheck",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "EventAssignment",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "EventCloseout",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "EventDish",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "EventGuest",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "Incident",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "Ingredient",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "IngredientDemand",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "InventoryItem",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "InventoryReservation",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "Invoice",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "Menu",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "MenuDish",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "Organization",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "PackList",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "PackListItem",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "Payment",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "PaymentMethod",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "PayrollInput",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "Person",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "PrepTask",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "ProductionBatch",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "Proposal",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "PurchaseNeed",
      "createMutation": "PurchaseNeed_create",
      "rowCount": 2
    },
    {
      "entity": "Qualification",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "QualityCheck",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "Recipe",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "RecipeImport",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "RecipeImportLine",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "RecipeIngredient",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "RecipeStep",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "SavedReportDefinition",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "Shift",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "SoftDeletable",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "StorageLocation",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "TenantScoped",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "TimeRecord",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "Vendor",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "VendorOrder",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "VendorOrderLine",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "VendorOrderLineDemand",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "Venue",
      "createMutation": null,
      "rowCount": 2
    },
    {
      "entity": "WasteRecord",
      "createMutation": null,
      "rowCount": 2
    }
  ]
} as const;
