sequenceDiagram
    participant Client
    participant Ingredient as Ingredient
    Client->>+Ingredient: configureSubstitutes(substituteIngredientIds)
    Note over Ingredient: Policies: ingredientRead, ingredientWrite, ingredientExecute
    Note over Ingredient: Guards (2)
    Ingredient->>Ingredient: guard[0]: self.introducedAt != null
    Ingredient->>Ingredient: guard[1]: self.deletedAt == null
    Ingredient->>Ingredient: mutate.substituteIngredientIds
    Ingredient-->>-Client: void