// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.555Z

import { z } from 'zod';

// Command: accept on Proposal
export const ProposalAcceptParamsSchema = z.object({
  eventId: z.string().uuid().optional(),
});

export type ProposalAcceptParams = z.infer<typeof ProposalAcceptParamsSchema>;
