// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.810Z

import { z } from 'zod';

// Command: activate on Venue
export const VenueActivateParamsSchema = z.object({});

export type VenueActivateParams = z.infer<typeof VenueActivateParamsSchema>;
