// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: add on RecipeIngredient
export const RecipeIngredientAddParamsSchema = z.object({
  recipeId: z.string().uuid(),
  ingredientId: z.string().uuid(),
  quantity: z.number(),
  unit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]),
  sortOrder: z.number().optional(),
  prepNotes: z.string().optional(),
});

export type RecipeIngredientAddParams = z.infer<typeof RecipeIngredientAddParamsSchema>;
