// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: addItem on PackListItem
export const PackListItemAddItemParamsSchema = z.object({
  packListId: z.string().uuid(),
  description: z.string(),
  requiredQuantity: z.number(),
  unit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]),
  dishId: z.string().uuid().optional(),
  productionBatchId: z.string().uuid().optional(),
});

export type PackListItemAddItemParams = z.infer<typeof PackListItemAddItemParamsSchema>;
