// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: addLine on VendorOrderLine
export const VendorOrderLineAddLineParamsSchema = z.object({
  vendorOrderId: z.string().uuid(),
  ingredientId: z.string().uuid(),
  orderedQuantity: z.number(),
  unit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]),
  unitCost: z.number(),
  ingredientDemandId: z.string().uuid().optional(),
  locationId: z.string().uuid().optional(),
});

export type VendorOrderLineAddLineParams = z.infer<typeof VendorOrderLineAddLineParamsSchema>;
