// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: adjustQuantity on RecipeIngredient
export const RecipeIngredientAdjustQuantityParamsSchema = z.object({
  quantity: z.number(),
  unit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]),
});

export type RecipeIngredientAdjustQuantityParams = z.infer<typeof RecipeIngredientAdjustQuantityParamsSchema>;
