// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: adjustServings on EventDish
export const EventDishAdjustServingsParamsSchema = z.object({
  quantityServings: z.number(),
});

export type EventDishAdjustServingsParams = z.infer<typeof EventDishAdjustServingsParamsSchema>;
