// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: adjustServings on EventDish
export const EventDishAdjustServingsParamsSchema = z.object({
  quantityServings: z.number(),
});

export type EventDishAdjustServingsParams = z.infer<typeof EventDishAdjustServingsParamsSchema>;
