// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: applyPayment on Invoice
export const InvoiceApplyPaymentParamsSchema = z.object({
  paymentAmount: z.number(),
  paymentId: z.string().optional(),
});

export type InvoiceApplyPaymentParams = z.infer<typeof InvoiceApplyPaymentParamsSchema>;
