// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: approve on Event
export const EventApproveParamsSchema = z.object({});

export type EventApproveParams = z.infer<typeof EventApproveParamsSchema>;
