// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: approve on Event
export const EventApproveParamsSchema = z.object({});

export type EventApproveParams = z.infer<typeof EventApproveParamsSchema>;
