// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.810Z

import { z } from 'zod';

// Command: archive on SavedReportDefinition
export const SavedReportDefinitionArchiveParamsSchema = z.object({});

export type SavedReportDefinitionArchiveParams = z.infer<typeof SavedReportDefinitionArchiveParamsSchema>;
