// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: archive on SavedReportDefinition
export const SavedReportDefinitionArchiveParamsSchema = z.object({});

export type SavedReportDefinitionArchiveParams = z.infer<typeof SavedReportDefinitionArchiveParamsSchema>;
