// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: assignOwner on Event
export const EventAssignOwnerParamsSchema = z.object({
  assignedToId: z.string().uuid().optional(),
});

export type EventAssignOwnerParams = z.infer<typeof EventAssignOwnerParamsSchema>;
