// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: assignTable on EventGuest
export const EventGuestAssignTableParamsSchema = z.object({
  tableAssignment: z.string(),
});

export type EventGuestAssignTableParams = z.infer<typeof EventGuestAssignTableParamsSchema>;
