// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: assign on EventAssignment
export const EventAssignmentAssignParamsSchema = z.object({
  eventId: z.string().uuid(),
  personId: z.string().uuid(),
  role: z.string(),
  startsAt: z.coerce.date().optional(),
  endsAt: z.coerce.date().optional(),
  notes: z.string().optional(),
});

export type EventAssignmentAssignParams = z.infer<typeof EventAssignmentAssignParamsSchema>;
