// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: assignRole on Person
export const PersonAssignRoleParamsSchema = z.object({
  role: z.enum(["staff", "kitchen_staff", "kitchen_lead", "sales_staff", "event_staff", "inventory_staff", "procurement_staff", "logistics_staff", "driver", "workforce_staff", "finance_staff", "manager", "kitchen_manager", "sales_manager", "event_manager", "inventory_manager", "logistics_manager", "workforce_manager", "finance_manager", "admin", "owner", "system"]),
});

export type PersonAssignRoleParams = z.infer<typeof PersonAssignRoleParamsSchema>;
