// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: assignTable on EventGuest
export const EventGuestAssignTableParamsSchema = z.object({
  tableAssignment: z.string(),
});

export type EventGuestAssignTableParams = z.infer<typeof EventGuestAssignTableParamsSchema>;
