// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: attachCreatedIngredient on RecipeImportLine
export const RecipeImportLineAttachCreatedIngredientParamsSchema = z.object({
  matchedIngredientId: z.string().uuid(),
});

export type RecipeImportLineAttachCreatedIngredientParams = z.infer<typeof RecipeImportLineAttachCreatedIngredientParamsSchema>;
