// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.553Z

import { z } from 'zod';

// Entity: AvailabilityWindow
export const AvailabilityWindowSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  personId: z.string().uuid(),
  startsAt: z.coerce.date().nullable().optional(),
  endsAt: z.coerce.date().nullable().optional(),
  notes: z.string().nullable().optional(),
  status: z.enum(["active", "withdrawn"]).default("active"),
  declaredAt: z.coerce.date().nullable().optional(),
  withdrawnAt: z.coerce.date().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type AvailabilityWindow = z.infer<typeof AvailabilityWindowSchema>;
