// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: beginFinalization on RecipeImport
export const RecipeImportBeginFinalizationParamsSchema = z.object({});

export type RecipeImportBeginFinalizationParams = z.infer<typeof RecipeImportBeginFinalizationParamsSchema>;
