// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: beginInvestigation on Incident
export const IncidentBeginInvestigationParamsSchema = z.object({});

export type IncidentBeginInvestigationParams = z.infer<typeof IncidentBeginInvestigationParamsSchema>;
