// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: beginProcessing on Payment
export const PaymentBeginProcessingParamsSchema = z.object({});

export type PaymentBeginProcessingParams = z.infer<typeof PaymentBeginProcessingParamsSchema>;
