// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.554Z

import { z } from 'zod';

// Command: beginProcessing on Payment
export const PaymentBeginProcessingParamsSchema = z.object({});

export type PaymentBeginProcessingParams = z.infer<typeof PaymentBeginProcessingParamsSchema>;
