// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: beginExecution on Event
export const EventBeginExecutionParamsSchema = z.object({});

export type EventBeginExecutionParams = z.infer<typeof EventBeginExecutionParamsSchema>;
