// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: beginInvestigation on Incident
export const IncidentBeginInvestigationParamsSchema = z.object({});

export type IncidentBeginInvestigationParams = z.infer<typeof IncidentBeginInvestigationParamsSchema>;
