// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: beginReview on RecipeImport
export const RecipeImportBeginReviewParamsSchema = z.object({});

export type RecipeImportBeginReviewParams = z.infer<typeof RecipeImportBeginReviewParamsSchema>;
