// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: calculate on IngredientDemand
export const IngredientDemandCalculateParamsSchema = z.object({
  eventId: z.string().uuid(),
  ingredientId: z.string().uuid(),
  requiredQuantity: z.number(),
  unit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]),
  servings: z.number().optional(),
  dishId: z.string().uuid().optional(),
  sourceRecipeLineQuantity: z.number().optional(),
  sourceBatchMultiplier: z.number().optional(),
  sourceYieldQuantity: z.number().optional(),
});

export type IngredientDemandCalculateParams = z.infer<typeof IngredientDemandCalculateParamsSchema>;
