// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.810Z

import { z } from 'zod';

// Command: cancelLine on VendorOrderLine
export const VendorOrderLineCancelLineParamsSchema = z.object({
  reason: z.string(),
});

export type VendorOrderLineCancelLineParams = z.infer<typeof VendorOrderLineCancelLineParamsSchema>;
