// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.810Z

import { z } from 'zod';

// Command: cancel on VendorOrder
export const VendorOrderCancelParamsSchema = z.object({
  reason: z.string(),
});

export type VendorOrderCancelParams = z.infer<typeof VendorOrderCancelParamsSchema>;
