// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: cancelLine on VendorOrderLine
export const VendorOrderLineCancelLineParamsSchema = z.object({
  reason: z.string(),
});

export type VendorOrderLineCancelLineParams = z.infer<typeof VendorOrderLineCancelLineParamsSchema>;
