// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.555Z

import { z } from 'zod';

// Command: cancel on VendorOrder
export const VendorOrderCancelParamsSchema = z.object({
  reason: z.string(),
});

export type VendorOrderCancelParams = z.infer<typeof VendorOrderCancelParamsSchema>;
