// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: capture on EventCloseout
export const EventCloseoutCaptureParamsSchema = z.object({
  eventId: z.string().uuid(),
  actualRevenue: z.number(),
  budgetedRevenue: z.number(),
  revenueVariance: z.number(),
  actualIngredientCost: z.number(),
  actualWasteCost: z.number(),
  actualLaborCost: z.number(),
  actualVendorCost: z.number(),
  budgetedCost: z.number(),
  totalActualCost: z.number(),
  costVariance: z.number(),
  grossProfit: z.number(),
  expectedHeadcount: z.number(),
  actualHeadcount: z.number(),
  unresolvedIssues: z.string().optional(),
  performanceNotes: z.string().optional(),
  notes: z.string().optional(),
});

export type EventCloseoutCaptureParams = z.infer<typeof EventCloseoutCaptureParamsSchema>;
