// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: changeContact on Client
export const ClientChangeContactParamsSchema = z.object({
  email: z.string().optional(),
  phone: z.string().optional(),
  website: z.string().optional(),
  addressLine1: z.string().optional(),
  addressLine2: z.string().optional(),
  city: z.string().optional(),
  region: z.string().optional(),
  postalCode: z.string().optional(),
  countryCode: z.string().optional(),
});

export type ClientChangeContactParams = z.infer<typeof ClientChangeContactParamsSchema>;
