// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: changeCapacity on Venue
export const VenueChangeCapacityParamsSchema = z.object({
  capacity: z.number(),
});

export type VenueChangeCapacityParams = z.infer<typeof VenueChangeCapacityParamsSchema>;
