// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: changeVenue on Event
export const EventChangeVenueParamsSchema = z.object({
  venueId: z.string().uuid().optional(),
  venueName: z.string().optional(),
  venueAddress: z.string().optional(),
});

export type EventChangeVenueParams = z.infer<typeof EventChangeVenueParamsSchema>;
