// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.554Z

import { z } from 'zod';

// Command: changeBillingProfile on Client
export const ClientChangeBillingProfileParamsSchema = z.object({
  paymentTermsDays: z.number(),
  taxExempt: z.boolean(),
  taxId: z.string().optional(),
});

export type ClientChangeBillingProfileParams = z.infer<typeof ClientChangeBillingProfileParamsSchema>;
