// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: changeSharing on SavedReportDefinition
export const SavedReportDefinitionChangeSharingParamsSchema = z.object({
  sharingScope: z.enum(["owner_only", "team", "tenant_wide"]),
});

export type SavedReportDefinitionChangeSharingParams = z.infer<typeof SavedReportDefinitionChangeSharingParamsSchema>;
