// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: changeCourse on EventDish
export const EventDishChangeCourseParamsSchema = z.object({
  course: z.string().optional(),
  serviceStyle: z.string().optional(),
});

export type EventDishChangeCourseParams = z.infer<typeof EventDishChangeCourseParamsSchema>;
