// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: changePricing on Event
export const EventChangePricingParamsSchema = z.object({
  budgetAmount: z.number(),
  quotedPrice: z.number(),
});

export type EventChangePricingParams = z.infer<typeof EventChangePricingParamsSchema>;
