// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: changeRequirements on Event
export const EventChangeRequirementsParamsSchema = z.object({
  accessibilityNeeds: z.array(z.string()).optional(),
  serviceRequirements: z.string().optional(),
  operationalRequirements: z.string().optional(),
});

export type EventChangeRequirementsParams = z.infer<typeof EventChangeRequirementsParamsSchema>;
