// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.555Z

import { z } from 'zod';

// Command: changeCapacity on Venue
export const VenueChangeCapacityParamsSchema = z.object({
  capacity: z.number(),
});

export type VenueChangeCapacityParams = z.infer<typeof VenueChangeCapacityParamsSchema>;
