// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: changeRecipe on Dish
export const DishChangeRecipeParamsSchema = z.object({
  recipeId: z.string().uuid(),
});

export type DishChangeRecipeParams = z.infer<typeof DishChangeRecipeParamsSchema>;
