// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: changeHeadcount on Event
export const EventChangeHeadcountParamsSchema = z.object({
  newHeadcount: z.number(),
});

export type EventChangeHeadcountParams = z.infer<typeof EventChangeHeadcountParamsSchema>;
