// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: changePrimaryContact on Event
export const EventChangePrimaryContactParamsSchema = z.object({
  primaryContactName: z.string(),
  primaryContactEmail: z.string().optional(),
  primaryContactPhone: z.string().optional(),
});

export type EventChangePrimaryContactParams = z.infer<typeof EventChangePrimaryContactParamsSchema>;
