// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: checkOut on EventAssignment
export const EventAssignmentCheckOutParamsSchema = z.object({});

export type EventAssignmentCheckOutParams = z.infer<typeof EventAssignmentCheckOutParamsSchema>;
