// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: checkIn on EventGuest
export const EventGuestCheckInParamsSchema = z.object({});

export type EventGuestCheckInParams = z.infer<typeof EventGuestCheckInParamsSchema>;
