// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: checkOut on EventAssignment
export const EventAssignmentCheckOutParamsSchema = z.object({});

export type EventAssignmentCheckOutParams = z.infer<typeof EventAssignmentCheckOutParamsSchema>;
