// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.554Z

import { z } from 'zod';

// Command: checkIn on EventGuest
export const EventGuestCheckInParamsSchema = z.object({});

export type EventGuestCheckInParams = z.infer<typeof EventGuestCheckInParamsSchema>;
