// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: claim on PrepTask
export const PrepTaskClaimParamsSchema = z.object({});

export type PrepTaskClaimParams = z.infer<typeof PrepTaskClaimParamsSchema>;
