// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: claim on PrepTask
export const PrepTaskClaimParamsSchema = z.object({});

export type PrepTaskClaimParams = z.infer<typeof PrepTaskClaimParamsSchema>;
