// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: classifyAllergens on Ingredient
export const IngredientClassifyAllergensParamsSchema = z.object({
  allergens: z.array(z.enum(["milk", "eggs", "fish", "crustacean_shellfish", "tree_nuts", "peanuts", "wheat", "soybeans", "sesame"])),
});

export type IngredientClassifyAllergensParams = z.infer<typeof IngredientClassifyAllergensParamsSchema>;
