// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: clearDefault on PaymentMethod
export const PaymentMethodClearDefaultParamsSchema = z.object({});

export type PaymentMethodClearDefaultParams = z.infer<typeof PaymentMethodClearDefaultParamsSchema>;
