// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: clearDefault on PaymentMethod
export const PaymentMethodClearDefaultParamsSchema = z.object({});

export type PaymentMethodClearDefaultParams = z.infer<typeof PaymentMethodClearDefaultParamsSchema>;
