// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.553Z

import { z } from 'zod';

// Entity: Client
export const ClientSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  clientType: z.enum(["company", "person"]).default("company"),
  companyName: z.string().nullable().optional(),
  givenName: z.string().nullable().optional(),
  familyName: z.string().nullable().optional(),
  email: z.string().nullable().optional(),
  phone: z.string().nullable().optional(),
  website: z.string().nullable().optional(),
  addressLine1: z.string().nullable().optional(),
  addressLine2: z.string().nullable().optional(),
  city: z.string().nullable().optional(),
  region: z.string().nullable().optional(),
  postalCode: z.string().nullable().optional(),
  countryCode: z.string().nullable().optional(),
  taxId: z.string().nullable().optional(),
  taxExempt: z.boolean().default(false),
  paymentTermsDays: z.number().int().default(30),
  notes: z.string().nullable().optional(),
  assignedToId: z.string().uuid().nullable().optional(),
  status: z.enum(["active", "archived"]).default("active"),
  registeredAt: z.coerce.date().nullable().optional(),
  archivedAt: z.coerce.date().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

// Computed: Client
export const ClientComputedSchema = ClientSchema.extend({
  displayName: z.string(),
  isArchived: z.boolean(),
});

export type Client = z.infer<typeof ClientSchema>;
export type ClientWithComputed = z.infer<typeof ClientComputedSchema>;
