// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.914Z

import { z } from 'zod';

// Entity: ClientContact
export const ClientContactSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  clientId: z.string().uuid(),
  givenName: z.string().nullable().optional(),
  familyName: z.string().nullable().optional(),
  title: z.string().nullable().optional(),
  email: z.string().nullable().optional(),
  phone: z.string().nullable().optional(),
  mobile: z.string().nullable().optional(),
  isPrimary: z.boolean().default(false),
  isBillingContact: z.boolean().default(false),
  notes: z.string().nullable().optional(),
  status: z.enum(["active", "removed"]).default("active"),
  addedAt: z.coerce.date().nullable().optional(),
  removedAt: z.coerce.date().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type ClientContact = z.infer<typeof ClientContactSchema>;
