// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: clockOut on TimeRecord
export const TimeRecordClockOutParamsSchema = z.object({
  breakMinutes: z.number().optional(),
  notes: z.string().optional(),
});

export type TimeRecordClockOutParams = z.infer<typeof TimeRecordClockOutParamsSchema>;
