// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: clockIn on TimeRecord
export const TimeRecordClockInParamsSchema = z.object({
  personId: z.string().uuid(),
  shiftId: z.string().uuid().optional(),
  eventId: z.string().uuid().optional(),
  notes: z.string().optional(),
});

export type TimeRecordClockInParams = z.infer<typeof TimeRecordClockInParamsSchema>;
