// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: closeOut on Event
export const EventCloseOutParamsSchema = z.object({});

export type EventCloseOutParams = z.infer<typeof EventCloseOutParamsSchema>;
