// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: complete on Shift
export const ShiftCompleteParamsSchema = z.object({});

export type ShiftCompleteParams = z.infer<typeof ShiftCompleteParamsSchema>;
