// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: complete on Shift
export const ShiftCompleteParamsSchema = z.object({});

export type ShiftCompleteParams = z.infer<typeof ShiftCompleteParamsSchema>;
