// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: confirmNew on RecipeImportLine
export const RecipeImportLineConfirmNewParamsSchema = z.object({});

export type RecipeImportLineConfirmNewParams = z.infer<typeof RecipeImportLineConfirmNewParamsSchema>;
