// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.810Z

import { z } from 'zod';

// Command: confirm on VendorOrder
export const VendorOrderConfirmParamsSchema = z.object({});

export type VendorOrderConfirmParams = z.infer<typeof VendorOrderConfirmParamsSchema>;
