// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: confirmDelivery on Delivery
export const DeliveryConfirmDeliveryParamsSchema = z.object({});

export type DeliveryConfirmDeliveryParams = z.infer<typeof DeliveryConfirmDeliveryParamsSchema>;
