// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: confirmDelivery on Delivery
export const DeliveryConfirmDeliveryParamsSchema = z.object({});

export type DeliveryConfirmDeliveryParams = z.infer<typeof DeliveryConfirmDeliveryParamsSchema>;
