// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: confirm on VendorOrder
export const VendorOrderConfirmParamsSchema = z.object({});

export type VendorOrderConfirmParams = z.infer<typeof VendorOrderConfirmParamsSchema>;
