// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: consume on InventoryReservation
export const InventoryReservationConsumeParamsSchema = z.object({});

export type InventoryReservationConsumeParams = z.infer<typeof InventoryReservationConsumeParamsSchema>;
