// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: consume on InventoryReservation
export const InventoryReservationConsumeParamsSchema = z.object({});

export type InventoryReservationConsumeParams = z.infer<typeof InventoryReservationConsumeParamsSchema>;
