// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.658Z

import { z } from 'zod';

// Entity: Contract
export const ContractSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  eventId: z.string().uuid(),
  clientId: z.string().uuid(),
  contractNumber: z.string().nullable().optional(),
  title: z.string().default(""),
  documentUrl: z.string().nullable().optional(),
  expiresAt: z.coerce.date().nullable().optional(),
  sentAt: z.coerce.date().nullable().optional(),
  viewedAt: z.coerce.date().nullable().optional(),
  signedAt: z.coerce.date().nullable().optional(),
  signedBy: z.string().nullable().optional(),
  voidedAt: z.coerce.date().nullable().optional(),
  voidReason: z.string().nullable().optional(),
  notes: z.string().nullable().optional(),
  status: z.enum(["draft", "sent", "viewed", "signed", "expired", "voided"]).default("draft"),
  draftedAt: z.coerce.date().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type Contract = z.infer<typeof ContractSchema>;
