// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: correctIdentity on Person
export const PersonCorrectIdentityParamsSchema = z.object({
  givenName: z.string(),
  familyName: z.string(),
  phone: z.string().optional(),
});

export type PersonCorrectIdentityParams = z.infer<typeof PersonCorrectIdentityParamsSchema>;
