// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: correct on TimeRecord
export const TimeRecordCorrectParamsSchema = z.object({
  clockInAt: z.coerce.date(),
  clockOutAt: z.coerce.date(),
  breakMinutes: z.number().optional(),
  notes: z.string().optional(),
});

export type TimeRecordCorrectParams = z.infer<typeof TimeRecordCorrectParamsSchema>;
