// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: createDefinition on SavedReportDefinition
export const SavedReportDefinitionCreateDefinitionParamsSchema = z.object({
  name: z.string(),
  subjectArea: z.enum(["events", "sales", "inventory", "production", "workforce", "logistics", "finance"]),
  chartType: z.string(),
  definition: z.unknown(),
  sharingScope: z.enum(["owner_only", "team", "tenant_wide"]).optional(),
});

export type SavedReportDefinitionCreateDefinitionParams = z.infer<typeof SavedReportDefinitionCreateDefinitionParamsSchema>;
