// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: create on PurchaseNeed
export const PurchaseNeedCreateParamsSchema = z.object({
  eventId: z.string().uuid(),
  ingredientDemandId: z.string().uuid(),
  ingredientId: z.string().uuid(),
  requiredQuantity: z.number(),
  unit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]),
});

export type PurchaseNeedCreateParams = z.infer<typeof PurchaseNeedCreateParamsSchema>;
