// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: deactivate on Venue
export const VenueDeactivateParamsSchema = z.object({
  reason: z.string(),
});

export type VenueDeactivateParams = z.infer<typeof VenueDeactivateParamsSchema>;
