// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.658Z

import { z } from 'zod';

// Command: declare on AvailabilityWindow
export const AvailabilityWindowDeclareParamsSchema = z.object({
  personId: z.string().uuid(),
  startsAt: z.coerce.date(),
  endsAt: z.coerce.date(),
  notes: z.string().optional(),
});

export type AvailabilityWindowDeclareParams = z.infer<typeof AvailabilityWindowDeclareParamsSchema>;
