// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: decline on Proposal
export const ProposalDeclineParamsSchema = z.object({});

export type ProposalDeclineParams = z.infer<typeof ProposalDeclineParamsSchema>;
