// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: decline on Proposal
export const ProposalDeclineParamsSchema = z.object({});

export type ProposalDeclineParams = z.infer<typeof ProposalDeclineParamsSchema>;
