// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.658Z

import { z } from 'zod';

// Entity: Delivery
export const DeliverySchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  packListId: z.string().uuid(),
  eventId: z.string().uuid(),
  driverId: z.string().uuid().nullable().optional(),
  destination: z.string().default(""),
  windowStartsAt: z.coerce.date().nullable().optional(),
  windowEndsAt: z.coerce.date().nullable().optional(),
  notes: z.string().nullable().optional(),
  status: z.enum(["scheduled", "in_transit", "delivered", "failed", "cancelled"]).default("scheduled"),
  scheduledAt: z.coerce.date().nullable().optional(),
  departedAt: z.coerce.date().nullable().optional(),
  deliveredAt: z.coerce.date().nullable().optional(),
  failedAt: z.coerce.date().nullable().optional(),
  failureReason: z.string().nullable().optional(),
  cancelledAt: z.coerce.date().nullable().optional(),
  cancellationReason: z.string().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type Delivery = z.infer<typeof DeliverySchema>;
