// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: discard on RecipeImportLine
export const RecipeImportLineDiscardParamsSchema = z.object({
  reason: z.string(),
});

export type RecipeImportLineDiscardParams = z.infer<typeof RecipeImportLineDiscardParamsSchema>;
