// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: discontinue on Ingredient
export const IngredientDiscontinueParamsSchema = z.object({
  reason: z.string(),
});

export type IngredientDiscontinueParams = z.infer<typeof IngredientDiscontinueParamsSchema>;
