// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.531Z

import { z } from 'zod';

// Entity: Dish
export const DishSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  recipeId: z.string().uuid(),
  name: z.string().default(""),
  description: z.string().nullable().optional(),
  category: z.string().nullable().optional(),
  course: z.string().nullable().optional(),
  serviceStyle: z.string().nullable().optional(),
  portionSize: z.number().default(1),
  portionUnit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]).default("portion"),
  dietaryTags: z.array(z.string()).optional().default([]),
  allergenSummary: z.array(z.enum(["milk", "eggs", "fish", "crustacean_shellfish", "tree_nuts", "peanuts", "wheat", "soybeans", "sesame"])).optional().default([]),
  status: z.enum(["active", "retired"]).default("active"),
  introducedAt: z.coerce.date().nullable().optional(),
  retiredAt: z.coerce.date().nullable().optional(),
  retirementReason: z.string().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

// Computed: Dish
export const DishComputedSchema = DishSchema.extend({
  isActive: z.boolean(),
  isRetired: z.boolean(),
});

export type Dish = z.infer<typeof DishSchema>;
export type DishWithComputed = z.infer<typeof DishComputedSchema>;
