// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: dismiss on Incident
export const IncidentDismissParamsSchema = z.object({
  reason: z.string(),
});

export type IncidentDismissParams = z.infer<typeof IncidentDismissParamsSchema>;
