// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: dispatch on PackList
export const PackListDispatchParamsSchema = z.object({});

export type PackListDispatchParams = z.infer<typeof PackListDispatchParamsSchema>;
