// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: dispatch on PackList
export const PackListDispatchParamsSchema = z.object({});

export type PackListDispatchParams = z.infer<typeof PackListDispatchParamsSchema>;
