// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.555Z

import { z } from 'zod';

// Command: draft on Recipe
export const RecipeDraftParamsSchema = z.object({
  name: z.string(),
  yieldQuantity: z.number(),
  yieldUnit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]),
  batchMultiplier: z.number().optional(),
  category: z.string().optional(),
  cuisine: z.string().optional(),
  description: z.string().optional(),
  instructions: z.string().optional(),
});

export type RecipeDraftParams = z.infer<typeof RecipeDraftParamsSchema>;
