// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.549Z

import { z } from 'zod';

// Entity: EventCloseout
export const EventCloseoutSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  eventId: z.string().uuid(),
  actualRevenue: z.number().default(0),
  budgetedRevenue: z.number().default(0),
  revenueVariance: z.number().default(0),
  actualIngredientCost: z.number().default(0),
  actualWasteCost: z.number().default(0),
  actualLaborCost: z.number().default(0),
  actualVendorCost: z.number().default(0),
  budgetedCost: z.number().default(0),
  totalActualCost: z.number().default(0),
  costVariance: z.number().default(0),
  grossProfit: z.number().default(0),
  expectedHeadcount: z.number().int().default(0),
  actualHeadcount: z.number().int().default(0),
  unresolvedIssues: z.string().nullable().optional(),
  performanceNotes: z.string().nullable().optional(),
  notes: z.string().nullable().optional(),
  status: z.enum(["draft", "finalized"]).default("draft"),
  capturedAt: z.coerce.date().nullable().optional(),
  finalizedAt: z.coerce.date().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type EventCloseout = z.infer<typeof EventCloseoutSchema>;
