// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.549Z

import { z } from 'zod';

// Entity: Event
export const EventSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  clientId: z.string().uuid(),
  venueId: z.string().uuid().nullable().optional(),
  assignedToId: z.string().uuid().nullable().optional(),
  title: z.string().default(""),
  eventType: z.string().default(""),
  startsAt: z.coerce.date().nullable().optional(),
  endsAt: z.coerce.date().nullable().optional(),
  venueName: z.string().nullable().optional(),
  venueAddress: z.string().nullable().optional(),
  expectedHeadcount: z.number().int().default(0),
  primaryContactName: z.string().nullable().optional(),
  primaryContactEmail: z.string().nullable().optional(),
  primaryContactPhone: z.string().nullable().optional(),
  accessibilityNeeds: z.array(z.string()).optional().default([]),
  serviceRequirements: z.string().nullable().optional(),
  operationalRequirements: z.string().nullable().optional(),
  budgetAmount: z.number().default(0),
  quotedPrice: z.number().default(0),
  stage: z.enum(["planning", "pending_approval", "approved", "executing", "completed", "cancelled", "closed_out"]).default("planning"),
  plannedAt: z.coerce.date().nullable().optional(),
  approvedAt: z.coerce.date().nullable().optional(),
  executionStartedAt: z.coerce.date().nullable().optional(),
  completedAt: z.coerce.date().nullable().optional(),
  cancelledAt: z.coerce.date().nullable().optional(),
  closedOutAt: z.coerce.date().nullable().optional(),
  cancellationReason: z.string().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

// Computed: Event
export const EventComputedSchema = EventSchema.extend({
  isTerminal: z.boolean(),
  isEditable: z.boolean(),
  isReadyForExecution: z.boolean(),
});

export type Event = z.infer<typeof EventSchema>;
export type EventWithComputed = z.infer<typeof EventComputedSchema>;
