// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.658Z

import { z } from 'zod';

// Entity: EventAssignment
export const EventAssignmentSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  eventId: z.string().uuid(),
  personId: z.string().uuid(),
  role: z.string().default(""),
  startsAt: z.coerce.date().nullable().optional(),
  endsAt: z.coerce.date().nullable().optional(),
  notes: z.string().nullable().optional(),
  status: z.enum(["assigned", "confirmed", "checked_in", "checked_out", "no_show", "unassigned"]).default("assigned"),
  assignedAt: z.coerce.date().nullable().optional(),
  confirmedAt: z.coerce.date().nullable().optional(),
  checkedInAt: z.coerce.date().nullable().optional(),
  checkedOutAt: z.coerce.date().nullable().optional(),
  noShowAt: z.coerce.date().nullable().optional(),
  unassignedAt: z.coerce.date().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type EventAssignment = z.infer<typeof EventAssignmentSchema>;
