// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.808Z

import { z } from 'zod';

// Entity: EventAllergenCheck
export const EventAllergenCheckSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  eventId: z.string().uuid(),
  eventDishId: z.string().uuid().nullable().optional(),
  dishId: z.string().uuid().nullable().optional(),
  result: z.enum(["pass", "flagged"]).nullable().optional(),
  flaggedAllergens: z.array(z.enum(["milk", "eggs", "fish", "crustacean_shellfish", "tree_nuts", "peanuts", "wheat", "soybeans", "sesame"])).optional().default([]),
  notes: z.string().nullable().optional(),
  checkedById: z.string().uuid().nullable().optional(),
  status: z.enum(["pending", "recorded"]).default("pending"),
  checkedAt: z.coerce.date().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type EventAllergenCheck = z.infer<typeof EventAllergenCheckSchema>;
