// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.531Z

import { z } from 'zod';

// Entity: EventDish
export const EventDishSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  eventId: z.string().uuid(),
  dishId: z.string().uuid(),
  quantityServings: z.number().int().default(1),
  course: z.string().nullable().optional(),
  serviceStyle: z.string().nullable().optional(),
  specialInstructions: z.string().nullable().optional(),
  selectedAt: z.coerce.date().nullable().optional(),
  removedAt: z.coerce.date().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type EventDish = z.infer<typeof EventDishSchema>;
