// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.808Z

import { z } from 'zod';

// Entity: EventGuest
export const EventGuestSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  eventId: z.string().uuid(),
  name: z.string().default(""),
  email: z.string().nullable().optional(),
  phone: z.string().nullable().optional(),
  dietaryRestrictions: z.array(z.string()).optional().default([]),
  allergenRestrictions: z.array(z.string()).optional().default([]),
  accessibilityNeeds: z.array(z.string()).optional().default([]),
  specialMealRequired: z.boolean().default(false),
  rsvpStatus: z.enum(["pending", "confirmed", "declined"]).default("pending"),
  invitedAt: z.coerce.date().nullable().optional(),
  respondedAt: z.coerce.date().nullable().optional(),
  declineReason: z.string().nullable().optional(),
  checkedInAt: z.coerce.date().nullable().optional(),
  tableAssignment: z.string().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

// Computed: EventGuest
export const EventGuestComputedSchema = EventGuestSchema.extend({
  isCheckedIn: z.boolean(),
});

export type EventGuest = z.infer<typeof EventGuestSchema>;
export type EventGuestWithComputed = z.infer<typeof EventGuestComputedSchema>;
