// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: expire on Qualification
export const QualificationExpireParamsSchema = z.object({});

export type QualificationExpireParams = z.infer<typeof QualificationExpireParamsSchema>;
