// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: fail on QualityCheck
export const QualityCheckFailParamsSchema = z.object({
  notes: z.string().optional(),
});

export type QualityCheckFailParams = z.infer<typeof QualityCheckFailParamsSchema>;
