// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.554Z

import { z } from 'zod';

// Command: finalize on PayrollInput
export const PayrollInputFinalizeParamsSchema = z.object({});

export type PayrollInputFinalizeParams = z.infer<typeof PayrollInputFinalizeParamsSchema>;
