// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: finalize on PayrollInput
export const PayrollInputFinalizeParamsSchema = z.object({});

export type PayrollInputFinalizeParams = z.infer<typeof PayrollInputFinalizeParamsSchema>;
