// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: fulfill on IngredientDemand
export const IngredientDemandFulfillParamsSchema = z.object({});

export type IngredientDemandFulfillParams = z.infer<typeof IngredientDemandFulfillParamsSchema>;
