// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: fulfill on IngredientDemand
export const IngredientDemandFulfillParamsSchema = z.object({});

export type IngredientDemandFulfillParams = z.infer<typeof IngredientDemandFulfillParamsSchema>;
