// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: grant on Qualification
export const QualificationGrantParamsSchema = z.object({
  personId: z.string().uuid(),
  name: z.string(),
  issuedAt: z.coerce.date(),
  certificationType: z.string().optional(),
  expiresAt: z.coerce.date().optional(),
  documentRef: z.string().optional(),
  notes: z.string().optional(),
});

export type QualificationGrantParams = z.infer<typeof QualificationGrantParamsSchema>;
