// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: hire on Person
export const PersonHireParamsSchema = z.object({
  givenName: z.string(),
  familyName: z.string(),
  email: z.string(),
  phone: z.string().optional(),
  role: z.enum(["staff", "kitchen_staff", "kitchen_lead", "sales_staff", "event_staff", "inventory_staff", "procurement_staff", "logistics_staff", "driver", "workforce_staff", "finance_staff", "manager", "kitchen_manager", "sales_manager", "event_manager", "inventory_manager", "logistics_manager", "workforce_manager", "finance_manager", "admin", "owner", "system"]).optional(),
  employmentType: z.enum(["full_time", "part_time", "contractor", "temporary"]).optional(),
  employeeNumber: z.string().optional(),
  authSubjectId: z.string().optional(),
});

export type PersonHireParams = z.infer<typeof PersonHireParamsSchema>;
