// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.553Z

import { z } from 'zod';

// Entity: Incident
export const IncidentSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  eventId: z.string().uuid(),
  prepTaskId: z.string().uuid().nullable().optional(),
  deliveryId: z.string().uuid().nullable().optional(),
  shiftId: z.string().uuid().nullable().optional(),
  severity: z.enum(["low", "medium", "high", "critical"]).default("medium"),
  category: z.enum(["food_safety", "injury", "equipment", "service", "other"]).default("other"),
  description: z.string().default(""),
  resolution: z.string().nullable().optional(),
  dismissalReason: z.string().nullable().optional(),
  reportedById: z.string().uuid().nullable().optional(),
  status: z.enum(["open", "investigating", "resolved", "dismissed"]).default("open"),
  reportedAt: z.coerce.date().nullable().optional(),
  investigatingAt: z.coerce.date().nullable().optional(),
  resolvedAt: z.coerce.date().nullable().optional(),
  dismissedAt: z.coerce.date().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type Incident = z.infer<typeof IncidentSchema>;
