// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.531Z

import { z } from 'zod';

// Entity: IngredientDemand
export const IngredientDemandSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  eventId: z.string().uuid(),
  ingredientId: z.string().uuid(),
  requiredQuantity: z.number().default(0),
  unit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]).default("each"),
  servings: z.number().nullable().optional(),
  dishId: z.string().uuid().nullable().optional(),
  sourceRecipeLineQuantity: z.number().nullable().optional(),
  sourceBatchMultiplier: z.number().nullable().optional(),
  sourceYieldQuantity: z.number().nullable().optional(),
  status: z.enum(["pending", "calculated", "confirmed", "fulfilled", "superseded"]).default("pending"),
  calculatedAt: z.coerce.date().nullable().optional(),
  confirmedAt: z.coerce.date().nullable().optional(),
  fulfilledAt: z.coerce.date().nullable().optional(),
  supersededAt: z.coerce.date().nullable().optional(),
  supersedeReason: z.string().nullable().optional(),
  lastRecalculationReason: z.string().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type IngredientDemand = z.infer<typeof IngredientDemandSchema>;
