// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.914Z

import { z } from 'zod';

// Entity: Ingredient
export const IngredientSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  name: z.string().default(""),
  unit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]).default("each"),
  allergens: z.array(z.enum(["milk", "eggs", "fish", "crustacean_shellfish", "tree_nuts", "peanuts", "wheat", "soybeans", "sesame"])).optional().default([]),
  costPerUnit: z.number().min(0).default(0),
  category: z.string().nullable().optional(),
  status: z.enum(["active", "discontinued"]).default("active"),
  introducedAt: z.coerce.date().nullable().optional(),
  discontinuedAt: z.coerce.date().nullable().optional(),
  discontinuationReason: z.string().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

// Computed: Ingredient
export const IngredientComputedSchema = IngredientSchema.extend({
  isActive: z.boolean(),
  isDiscontinued: z.boolean(),
});

export type Ingredient = z.infer<typeof IngredientSchema>;
export type IngredientWithComputed = z.infer<typeof IngredientComputedSchema>;
