// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: introduce on Ingredient
export const IngredientIntroduceParamsSchema = z.object({
  name: z.string(),
  unit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]),
  costPerUnit: z.number(),
  allergens: z.array(z.enum(["milk", "eggs", "fish", "crustacean_shellfish", "tree_nuts", "peanuts", "wheat", "soybeans", "sesame"])).optional(),
  category: z.string().optional(),
});

export type IngredientIntroduceParams = z.infer<typeof IngredientIntroduceParamsSchema>;
