// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: invalidate on PaymentMethod
export const PaymentMethodInvalidateParamsSchema = z.object({
  reason: z.string(),
});

export type PaymentMethodInvalidateParams = z.infer<typeof PaymentMethodInvalidateParamsSchema>;
