// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.914Z

import { z } from 'zod';

// Entity: InventoryItem
export const InventoryItemSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  ingredientId: z.string().uuid(),
  locationId: z.string().uuid(),
  quantityOnHand: z.number().default(0),
  unit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]).default("each"),
  parLevel: z.number().min(0).default(0),
  reorderThreshold: z.number().min(0).default(0),
  unitCost: z.number().min(0).default(0),
  stockedAt: z.coerce.date().nullable().optional(),
  removedAt: z.coerce.date().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

// Computed: InventoryItem
export const InventoryItemComputedSchema = InventoryItemSchema.extend({
  isBelowPar: z.boolean(),
  isBelowReorder: z.boolean(),
  inventoryValue: z.number(),
});

export type InventoryItem = z.infer<typeof InventoryItemSchema>;
export type InventoryItemWithComputed = z.infer<typeof InventoryItemComputedSchema>;
