// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.808Z

import { z } from 'zod';

// Entity: InventoryReservation
export const InventoryReservationSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  inventoryItemId: z.string().uuid(),
  eventId: z.string().uuid(),
  ingredientId: z.string().uuid(),
  quantity: z.number().default(0),
  status: z.enum(["pending", "active", "released", "consumed"]).default("pending"),
  reservedAt: z.coerce.date().nullable().optional(),
  releasedAt: z.coerce.date().nullable().optional(),
  consumedAt: z.coerce.date().nullable().optional(),
  releaseReason: z.string().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type InventoryReservation = z.infer<typeof InventoryReservationSchema>;
