// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: invite on EventGuest
export const EventGuestInviteParamsSchema = z.object({
  eventId: z.string().uuid(),
  name: z.string(),
  email: z.string().optional(),
  phone: z.string().optional(),
  dietaryRestrictions: z.array(z.string()).optional(),
  allergenRestrictions: z.array(z.string()).optional(),
  accessibilityNeeds: z.array(z.string()).optional(),
  specialMealRequired: z.boolean().optional(),
});

export type EventGuestInviteParams = z.infer<typeof EventGuestInviteParamsSchema>;
