// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.553Z

import { z } from 'zod';

// Entity: Invoice
export const InvoiceSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  clientId: z.string().uuid(),
  eventId: z.string().uuid().nullable().optional(),
  invoiceNumber: z.string().nullable().optional(),
  subtotal: z.number().default(0),
  taxAmount: z.number().default(0),
  discountAmount: z.number().default(0),
  total: z.number().default(0),
  amountPaid: z.number().default(0),
  amountDue: z.number().default(0),
  paymentTermsDays: z.number().int().default(30),
  dueDate: z.coerce.date().nullable().optional(),
  notes: z.string().nullable().optional(),
  status: z.enum(["draft", "sent", "viewed", "overdue", "partial", "paid", "voided", "written_off"]).default("draft"),
  issuedAt: z.coerce.date().nullable().optional(),
  sentAt: z.coerce.date().nullable().optional(),
  viewedAt: z.coerce.date().nullable().optional(),
  overdueSince: z.coerce.date().nullable().optional(),
  paidAt: z.coerce.date().nullable().optional(),
  voidedAt: z.coerce.date().nullable().optional(),
  voidReason: z.string().nullable().optional(),
  writtenOffAt: z.coerce.date().nullable().optional(),
  writeOffReason: z.string().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type Invoice = z.infer<typeof InvoiceSchema>;
