// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: issue on Invoice
export const InvoiceIssueParamsSchema = z.object({
  clientId: z.string().uuid(),
  invoiceNumber: z.string(),
  subtotal: z.number(),
  taxAmount: z.number(),
  discountAmount: z.number(),
  total: z.number(),
  eventId: z.string().uuid().optional(),
  paymentTermsDays: z.number().optional(),
  dueDate: z.coerce.date().optional(),
  notes: z.string().optional(),
});

export type InvoiceIssueParams = z.infer<typeof InvoiceIssueParamsSchema>;
