// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: makeDefault on PaymentMethod
export const PaymentMethodMakeDefaultParamsSchema = z.object({});

export type PaymentMethodMakeDefaultParams = z.infer<typeof PaymentMethodMakeDefaultParamsSchema>;
