// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: makeDefault on PaymentMethod
export const PaymentMethodMakeDefaultParamsSchema = z.object({});

export type PaymentMethodMakeDefaultParams = z.infer<typeof PaymentMethodMakeDefaultParamsSchema>;
