// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: markViewed on Proposal
export const ProposalMarkViewedParamsSchema = z.object({});

export type ProposalMarkViewedParams = z.infer<typeof ProposalMarkViewedParamsSchema>;
