// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: markFailed on RecipeImport
export const RecipeImportMarkFailedParamsSchema = z.object({
  failureDetail: z.string(),
  duringParsing: z.boolean().optional(),
});

export type RecipeImportMarkFailedParams = z.infer<typeof RecipeImportMarkFailedParamsSchema>;
