// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: markResolved on Incident
export const IncidentMarkResolvedParamsSchema = z.object({
  resolution: z.string(),
});

export type IncidentMarkResolvedParams = z.infer<typeof IncidentMarkResolvedParamsSchema>;
