// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.554Z

import { z } from 'zod';

// Command: markPublished on Menu
export const MenuMarkPublishedParamsSchema = z.object({});

export type MenuMarkPublishedParams = z.infer<typeof MenuMarkPublishedParamsSchema>;
