// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: markPartiallyReceived on VendorOrder
export const VendorOrderMarkPartiallyReceivedParamsSchema = z.object({});

export type VendorOrderMarkPartiallyReceivedParams = z.infer<typeof VendorOrderMarkPartiallyReceivedParamsSchema>;
