// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: markPublished on Menu
export const MenuMarkPublishedParamsSchema = z.object({});

export type MenuMarkPublishedParams = z.infer<typeof MenuMarkPublishedParamsSchema>;
