// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: markNoShow on Shift
export const ShiftMarkNoShowParamsSchema = z.object({});

export type ShiftMarkNoShowParams = z.infer<typeof ShiftMarkNoShowParamsSchema>;
