// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: markOverdue on Invoice
export const InvoiceMarkOverdueParamsSchema = z.object({});

export type InvoiceMarkOverdueParams = z.infer<typeof InvoiceMarkOverdueParamsSchema>;
