// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.810Z

import { z } from 'zod';

// Command: markReceived on VendorOrder
export const VendorOrderMarkReceivedParamsSchema = z.object({});

export type VendorOrderMarkReceivedParams = z.infer<typeof VendorOrderMarkReceivedParamsSchema>;
