// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.810Z

import { z } from 'zod';

// Command: markNoShow on Shift
export const ShiftMarkNoShowParamsSchema = z.object({});

export type ShiftMarkNoShowParams = z.infer<typeof ShiftMarkNoShowParamsSchema>;
