// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: markNew on RecipeImportLine
export const RecipeImportLineMarkNewParamsSchema = z.object({});

export type RecipeImportLineMarkNewParams = z.infer<typeof RecipeImportLineMarkNewParamsSchema>;
