// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: markFailed on Delivery
export const DeliveryMarkFailedParamsSchema = z.object({
  reason: z.string(),
});

export type DeliveryMarkFailedParams = z.infer<typeof DeliveryMarkFailedParamsSchema>;
