// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: markMissing on PackListItem
export const PackListItemMarkMissingParamsSchema = z.object({});

export type PackListItemMarkMissingParams = z.infer<typeof PackListItemMarkMissingParamsSchema>;
