// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: markLoaded on PackList
export const PackListMarkLoadedParamsSchema = z.object({});

export type PackListMarkLoadedParams = z.infer<typeof PackListMarkLoadedParamsSchema>;
