// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.555Z

import { z } from 'zod';

// Command: markOrdered on PurchaseNeed
export const PurchaseNeedMarkOrderedParamsSchema = z.object({
  vendorOrderId: z.string().uuid(),
  vendorOrderLineId: z.string().uuid(),
});

export type PurchaseNeedMarkOrderedParams = z.infer<typeof PurchaseNeedMarkOrderedParamsSchema>;
