// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.554Z

import { z } from 'zod';

// Command: markPacked on PackListItem
export const PackListItemMarkPackedParamsSchema = z.object({
  packedQuantity: z.number(),
});

export type PackListItemMarkPackedParams = z.infer<typeof PackListItemMarkPackedParamsSchema>;
