// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: markViewed on Proposal
export const ProposalMarkViewedParamsSchema = z.object({});

export type ProposalMarkViewedParams = z.infer<typeof ProposalMarkViewedParamsSchema>;
