// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: markFulfilled on PurchaseNeed
export const PurchaseNeedMarkFulfilledParamsSchema = z.object({});

export type PurchaseNeedMarkFulfilledParams = z.infer<typeof PurchaseNeedMarkFulfilledParamsSchema>;
