// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: markReceived on VendorOrder
export const VendorOrderMarkReceivedParamsSchema = z.object({});

export type VendorOrderMarkReceivedParams = z.infer<typeof VendorOrderMarkReceivedParamsSchema>;
