// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: markResolved on Incident
export const IncidentMarkResolvedParamsSchema = z.object({
  resolution: z.string(),
});

export type IncidentMarkResolvedParams = z.infer<typeof IncidentMarkResolvedParamsSchema>;
