// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.555Z

import { z } from 'zod';

// Command: markViewed on Proposal
export const ProposalMarkViewedParamsSchema = z.object({});

export type ProposalMarkViewedParams = z.infer<typeof ProposalMarkViewedParamsSchema>;
