// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: markVoided on PayrollInput
export const PayrollInputMarkVoidedParamsSchema = z.object({
  reason: z.string(),
});

export type PayrollInputMarkVoidedParams = z.infer<typeof PayrollInputMarkVoidedParamsSchema>;
