// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.531Z

import { z } from 'zod';

// Entity: Menu
export const MenuSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  name: z.string().default(""),
  description: z.string().nullable().optional(),
  category: z.string().nullable().optional(),
  isTemplate: z.boolean().default(false),
  basePrice: z.number().default(0),
  pricePerPerson: z.number().default(0),
  minGuests: z.number().int().default(0),
  maxGuests: z.number().int().default(0),
  status: z.enum(["draft", "published", "archived"]).default("draft"),
  draftedAt: z.coerce.date().nullable().optional(),
  publishedAt: z.coerce.date().nullable().optional(),
  archivedAt: z.coerce.date().nullable().optional(),
  archiveReason: z.string().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

// Computed: Menu
export const MenuComputedSchema = MenuSchema.extend({
  isPublished: z.boolean(),
  isEditable: z.boolean(),
});

export type Menu = z.infer<typeof MenuSchema>;
export type MenuWithComputed = z.infer<typeof MenuComputedSchema>;
