// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: onboard on Vendor
export const VendorOnboardParamsSchema = z.object({
  name: z.string(),
  email: z.string().optional(),
  phone: z.string().optional(),
  addressLine1: z.string().optional(),
  city: z.string().optional(),
  region: z.string().optional(),
  postalCode: z.string().optional(),
  countryCode: z.string().optional(),
  paymentTermsDays: z.number().optional(),
  notes: z.string().optional(),
});

export type VendorOnboardParams = z.infer<typeof VendorOnboardParamsSchema>;
