// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: open on VendorOrder
export const VendorOrderOpenParamsSchema = z.object({
  vendorId: z.string().uuid(),
  eventId: z.string().uuid().optional(),
  orderNumber: z.string().optional(),
  notes: z.string().optional(),
});

export type VendorOrderOpenParams = z.infer<typeof VendorOrderOpenParamsSchema>;
