// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.531Z

import { z } from 'zod';

// Entity: Organization
export const OrganizationSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  name: z.string(),
  status: z.enum(["active", "suspended", "deactivated"]).default("active"),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

// Computed: Organization
export const OrganizationComputedSchema = OrganizationSchema.extend({
  isOperable: z.boolean(),
});

export type Organization = z.infer<typeof OrganizationSchema>;
export type OrganizationWithComputed = z.infer<typeof OrganizationComputedSchema>;
