// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.549Z

import { z } from 'zod';

// Entity: PackList
export const PackListSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  eventId: z.string().uuid(),
  name: z.string().default(""),
  purpose: z.string().nullable().optional(),
  notes: z.string().nullable().optional(),
  status: z.enum(["draft", "packing", "packed", "loaded", "dispatched", "cancelled"]).default("draft"),
  openedAt: z.coerce.date().nullable().optional(),
  packingStartedAt: z.coerce.date().nullable().optional(),
  packedAt: z.coerce.date().nullable().optional(),
  loadedAt: z.coerce.date().nullable().optional(),
  dispatchedAt: z.coerce.date().nullable().optional(),
  cancelledAt: z.coerce.date().nullable().optional(),
  cancellationReason: z.string().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type PackList = z.infer<typeof PackListSchema>;
