// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.553Z

import { z } from 'zod';

// Entity: PackListItem
export const PackListItemSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  packListId: z.string().uuid(),
  description: z.string().default(""),
  dishId: z.string().uuid().nullable().optional(),
  productionBatchId: z.string().uuid().nullable().optional(),
  requiredQuantity: z.number().default(0),
  packedQuantity: z.number().min(0).default(0),
  unit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]).default("each"),
  status: z.enum(["pending", "listed", "packed", "missing"]).default("pending"),
  listedAt: z.coerce.date().nullable().optional(),
  packedAt: z.coerce.date().nullable().optional(),
  missingAt: z.coerce.date().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type PackListItem = z.infer<typeof PackListItemSchema>;
