// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: pass on QualityCheck
export const QualityCheckPassParamsSchema = z.object({
  notes: z.string().optional(),
});

export type QualityCheckPassParams = z.infer<typeof QualityCheckPassParamsSchema>;
