// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.553Z

import { z } from 'zod';

// Entity: PaymentMethod
export const PaymentMethodSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  clientId: z.string().uuid(),
  methodType: z.enum(["card", "check", "cash", "ach", "other"]).default("card"),
  provider: z.string().nullable().optional(),
  lastFour: z.string().nullable().optional(),
  isDefault: z.boolean().default(false),
  status: z.enum(["active", "expired", "invalid", "fraudulent", "removed"]).default("active"),
  registeredAt: z.coerce.date().nullable().optional(),
  expiredAt: z.coerce.date().nullable().optional(),
  invalidatedAt: z.coerce.date().nullable().optional(),
  removedAt: z.coerce.date().nullable().optional(),
  notes: z.string().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type PaymentMethod = z.infer<typeof PaymentMethodSchema>;
