// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.531Z

import { z } from 'zod';

// Entity: Payment
export const PaymentSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  invoiceId: z.string().uuid(),
  clientId: z.string().uuid(),
  eventId: z.string().uuid().nullable().optional(),
  amount: z.number().default(0),
  method: z.enum(["card", "check", "cash", "ach", "other"]).default("card"),
  status: z.enum(["pending", "processing", "completed", "failed", "refunded"]).default("pending"),
  paymentMethodId: z.string().uuid().nullable().optional(),
  notes: z.string().nullable().optional(),
  recordedAt: z.coerce.date().nullable().optional(),
  settledAt: z.coerce.date().nullable().optional(),
  failedAt: z.coerce.date().nullable().optional(),
  refundedAt: z.coerce.date().nullable().optional(),
  failureReason: z.string().nullable().optional(),
  refundReason: z.string().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type Payment = z.infer<typeof PaymentSchema>;
