// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.914Z

import { z } from 'zod';

// Entity: PayrollInput
export const PayrollInputSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  personId: z.string().uuid(),
  periodStart: z.coerce.date(),
  periodEnd: z.coerce.date(),
  eventId: z.string().uuid().nullable().optional(),
  shiftId: z.string().uuid().nullable().optional(),
  regularMinutes: z.number().int().default(0),
  overtimeMinutes: z.number().int().default(0),
  totalMinutes: z.number().int().default(0),
  hourlyRate: z.number().nullable().optional(),
  overtimeRate: z.number().nullable().optional(),
  grossAmount: z.number().nullable().optional(),
  notes: z.string().nullable().optional(),
  status: z.enum(["draft", "prepared", "finalized", "voided"]).default("draft"),
  preparedAt: z.coerce.date().nullable().optional(),
  finalizedAt: z.coerce.date().nullable().optional(),
  voidedAt: z.coerce.date().nullable().optional(),
  voidReason: z.string().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type PayrollInput = z.infer<typeof PayrollInputSchema>;
