// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.914Z

import { z } from 'zod';

// Entity: Person
export const PersonSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  givenName: z.string(),
  familyName: z.string(),
  email: z.string(),
  phone: z.string().nullable().optional(),
  role: z.enum(["staff", "kitchen_staff", "kitchen_lead", "sales_staff", "event_staff", "inventory_staff", "procurement_staff", "logistics_staff", "driver", "workforce_staff", "finance_staff", "manager", "kitchen_manager", "sales_manager", "event_manager", "inventory_manager", "logistics_manager", "workforce_manager", "finance_manager", "admin", "owner", "system"]).default("staff"),
  authSubjectId: z.string().nullable().optional(),
  employeeNumber: z.string().nullable().optional(),
  employmentType: z.enum(["full_time", "part_time", "contractor", "temporary"]).default("full_time"),
  status: z.enum(["active", "inactive", "terminated"]).default("active"),
  hireDate: z.coerce.date().nullable().optional(),
  terminationDate: z.coerce.date().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

// Computed: Person
export const PersonComputedSchema = PersonSchema.extend({
  displayName: z.string(),
  isAssignable: z.boolean(),
});

export type Person = z.infer<typeof PersonSchema>;
export type PersonWithComputed = z.infer<typeof PersonComputedSchema>;
