// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: plan on ProductionBatch
export const ProductionBatchPlanParamsSchema = z.object({
  recipeId: z.string().uuid(),
  plannedYield: z.number(),
  yieldUnit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]),
  eventId: z.string().uuid().optional(),
  notes: z.string().optional(),
});

export type ProductionBatchPlanParams = z.infer<typeof ProductionBatchPlanParamsSchema>;
