// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: planEngagement on Event
export const EventPlanEngagementParamsSchema = z.object({
  clientId: z.string().uuid(),
  title: z.string(),
  eventType: z.string(),
  startsAt: z.coerce.date(),
  endsAt: z.coerce.date(),
  expectedHeadcount: z.number(),
  primaryContactName: z.string(),
  budgetAmount: z.number(),
  quotedPrice: z.number(),
  venueId: z.string().uuid().optional(),
  venueName: z.string().optional(),
  venueAddress: z.string().optional(),
  primaryContactEmail: z.string().optional(),
  primaryContactPhone: z.string().optional(),
  accessibilityNeeds: z.array(z.string()).optional(),
  serviceRequirements: z.string().optional(),
  operationalRequirements: z.string().optional(),
  assignedToId: z.string().uuid().optional(),
});

export type EventPlanEngagementParams = z.infer<typeof EventPlanEngagementParamsSchema>;
