// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.914Z

import { z } from 'zod';

// Entity: PrepTask
export const PrepTaskSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  eventId: z.string().uuid(),
  ingredientId: z.string().uuid(),
  ingredientDemandId: z.string().uuid().nullable().optional(),
  dishId: z.string().uuid().nullable().optional(),
  recipeId: z.string().uuid().nullable().optional(),
  quantity: z.number().default(0),
  completedQuantity: z.number().nullable().optional(),
  unit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]).default("each"),
  station: z.string().nullable().optional(),
  dueAt: z.coerce.date().nullable().optional(),
  assignedToId: z.string().uuid().nullable().optional(),
  notes: z.string().nullable().optional(),
  status: z.enum(["pending", "claimed", "in_progress", "blocked", "completed", "cancelled"]).default("pending"),
  claimedAt: z.coerce.date().nullable().optional(),
  startedAt: z.coerce.date().nullable().optional(),
  completedAt: z.coerce.date().nullable().optional(),
  cancelledAt: z.coerce.date().nullable().optional(),
  cancellationReason: z.string().nullable().optional(),
  blockedAt: z.coerce.date().nullable().optional(),
  blockReason: z.string().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type PrepTask = z.infer<typeof PrepTaskSchema>;
