// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: prepare on PayrollInput
export const PayrollInputPrepareParamsSchema = z.object({
  personId: z.string().uuid(),
  periodStart: z.coerce.date(),
  periodEnd: z.coerce.date(),
  regularMinutes: z.number(),
  overtimeMinutes: z.number(),
  totalMinutes: z.number(),
  eventId: z.string().uuid().optional(),
  shiftId: z.string().uuid().optional(),
  hourlyRate: z.number().optional(),
  overtimeRate: z.number().optional(),
  grossAmount: z.number().optional(),
  notes: z.string().optional(),
});

export type PayrollInputPrepareParams = z.infer<typeof PayrollInputPrepareParamsSchema>;
