// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.549Z

import { z } from 'zod';

// Entity: Proposal
export const ProposalSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  clientId: z.string().uuid(),
  eventId: z.string().uuid().nullable().optional(),
  proposalNumber: z.string().nullable().optional(),
  title: z.string().default(""),
  eventDate: z.coerce.date().nullable().optional(),
  eventType: z.string().nullable().optional(),
  guestCount: z.number().int().default(0),
  venueName: z.string().nullable().optional(),
  venueAddress: z.string().nullable().optional(),
  subtotal: z.number().default(0),
  taxAmount: z.number().default(0),
  discountAmount: z.number().default(0),
  total: z.number().default(0),
  expiresAt: z.coerce.date().nullable().optional(),
  notes: z.string().nullable().optional(),
  terms: z.string().nullable().optional(),
  status: z.enum(["draft", "sent", "viewed", "accepted", "declined", "expired"]).default("draft"),
  draftedAt: z.coerce.date().nullable().optional(),
  sentAt: z.coerce.date().nullable().optional(),
  viewedAt: z.coerce.date().nullable().optional(),
  acceptedAt: z.coerce.date().nullable().optional(),
  declinedAt: z.coerce.date().nullable().optional(),
  expiredAt: z.coerce.date().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type Proposal = z.infer<typeof ProposalSchema>;
