// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: publishVersion on Recipe
export const RecipePublishVersionParamsSchema = z.object({});

export type RecipePublishVersionParams = z.infer<typeof RecipePublishVersionParamsSchema>;
