// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: publishVersion on Recipe
export const RecipePublishVersionParamsSchema = z.object({});

export type RecipePublishVersionParams = z.infer<typeof RecipePublishVersionParamsSchema>;
