// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.553Z

import { z } from 'zod';

// Entity: PurchaseNeed
export const PurchaseNeedSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  eventId: z.string().uuid(),
  ingredientDemandId: z.string().uuid(),
  ingredientId: z.string().uuid(),
  requiredQuantity: z.number().default(0),
  unit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]).default("each"),
  vendorOrderId: z.string().uuid().nullable().optional(),
  vendorOrderLineId: z.string().uuid().nullable().optional(),
  status: z.enum(["open", "ordered", "fulfilled", "cancelled"]).default("open"),
  openedAt: z.coerce.date().nullable().optional(),
  orderedAt: z.coerce.date().nullable().optional(),
  fulfilledAt: z.coerce.date().nullable().optional(),
  cancelledAt: z.coerce.date().nullable().optional(),
  cancellationReason: z.string().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type PurchaseNeed = z.infer<typeof PurchaseNeedSchema>;
