// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Entity: Qualification
export const QualificationSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  personId: z.string().uuid(),
  name: z.string().default(""),
  certificationType: z.string().nullable().optional(),
  issuedAt: z.coerce.date().nullable().optional(),
  expiresAt: z.coerce.date().nullable().optional(),
  documentRef: z.string().nullable().optional(),
  notes: z.string().nullable().optional(),
  status: z.enum(["active", "expired", "revoked"]).default("active"),
  grantedAt: z.coerce.date().nullable().optional(),
  revokedAt: z.coerce.date().nullable().optional(),
  expiredAt: z.coerce.date().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type Qualification = z.infer<typeof QualificationSchema>;
