// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.531Z

import { z } from 'zod';

// Entity: QualityCheck
export const QualityCheckSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  prepTaskId: z.string().uuid().nullable().optional(),
  productionBatchId: z.string().uuid().nullable().optional(),
  notes: z.string().nullable().optional(),
  result: z.enum(["pass", "fail"]).nullable().optional(),
  checkedById: z.string().uuid().nullable().optional(),
  status: z.enum(["pending", "passed", "failed"]).default("pending"),
  openedAt: z.coerce.date().nullable().optional(),
  completedAt: z.coerce.date().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type QualityCheck = z.infer<typeof QualityCheckSchema>;
