// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: reactivate on Person
export const PersonReactivateParamsSchema = z.object({});

export type PersonReactivateParams = z.infer<typeof PersonReactivateParamsSchema>;
