// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: recalculate on IngredientDemand
export const IngredientDemandRecalculateParamsSchema = z.object({
  newQuantity: z.number(),
  reason: z.string(),
});

export type IngredientDemandRecalculateParams = z.infer<typeof IngredientDemandRecalculateParamsSchema>;
