// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.554Z

import { z } from 'zod';

// Command: receiveStock on InventoryItem
export const InventoryItemReceiveStockParamsSchema = z.object({
  quantity: z.number(),
  unitCost: z.number().optional(),
});

export type InventoryItemReceiveStockParams = z.infer<typeof InventoryItemReceiveStockParamsSchema>;
