// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: receiveStock on InventoryItem
export const InventoryItemReceiveStockParamsSchema = z.object({
  quantity: z.number(),
  unitCost: z.number().optional(),
});

export type InventoryItemReceiveStockParams = z.infer<typeof InventoryItemReceiveStockParamsSchema>;
