// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Entity: Recipe
export const RecipeSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  name: z.string().default(""),
  category: z.string().nullable().optional(),
  cuisine: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  instructions: z.string().nullable().optional(),
  versionNumber: z.number().int().default(1),
  yieldQuantity: z.number().min(1).default(1),
  yieldUnit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]).default("portion"),
  batchMultiplier: z.number().min(1).default(1),
  status: z.enum(["draft", "published", "retired"]).default("draft"),
  draftedAt: z.coerce.date().nullable().optional(),
  publishedAt: z.coerce.date().nullable().optional(),
  retiredAt: z.coerce.date().nullable().optional(),
  retirementReason: z.string().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

// Computed: Recipe
export const RecipeComputedSchema = RecipeSchema.extend({
  isPublished: z.boolean(),
  isEditable: z.boolean(),
});

export type Recipe = z.infer<typeof RecipeSchema>;
export type RecipeWithComputed = z.infer<typeof RecipeComputedSchema>;
