// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Entity: RecipeIngredient
export const RecipeIngredientSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  recipeId: z.string().uuid(),
  ingredientId: z.string().uuid(),
  quantity: z.number().default(0),
  unit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]).default("each"),
  sortOrder: z.number().int().default(0),
  prepNotes: z.string().nullable().optional(),
  addedAt: z.coerce.date().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type RecipeIngredient = z.infer<typeof RecipeIngredientSchema>;
