// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Entity: RecipeImport
export const RecipeImportSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  sourceKind: z.enum(["pasted_text", "text_file", "csv_bundle"]).default("pasted_text"),
  sourceFilename: z.string().nullable().optional(),
  rawSourceText: z.string().default(""),
  sourceByteCount: z.number().int().default(0),
  sourceFingerprint: z.string().default(""),
  parsedName: z.string().nullable().optional(),
  parsedDescription: z.string().nullable().optional(),
  parsedCategory: z.string().nullable().optional(),
  parsedCuisine: z.string().nullable().optional(),
  parsedInstructions: z.string().nullable().optional(),
  parsedYieldQuantity: z.number().nullable().optional(),
  parsedYieldUnit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]).nullable().optional(),
  parsedBatchMultiplier: z.number().nullable().optional(),
  parsedLineCount: z.number().int().default(0),
  resolvedLineCount: z.number().int().default(0),
  status: z.enum(["uploaded", "parsed", "reviewing", "ready", "finalizing", "completed", "failed", "cancelled"]).default("uploaded"),
  parsingFailureDetail: z.string().nullable().optional(),
  finalizationFailureDetail: z.string().nullable().optional(),
  resultingRecipeId: z.string().uuid().nullable().optional(),
  uploadedAt: z.coerce.date().nullable().optional(),
  parsedAt: z.coerce.date().nullable().optional(),
  reviewStartedAt: z.coerce.date().nullable().optional(),
  readyAt: z.coerce.date().nullable().optional(),
  finalizationStartedAt: z.coerce.date().nullable().optional(),
  completedAt: z.coerce.date().nullable().optional(),
  failedAt: z.coerce.date().nullable().optional(),
  cancelledAt: z.coerce.date().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type RecipeImport = z.infer<typeof RecipeImportSchema>;
