// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Entity: RecipeImportLine
export const RecipeImportLineSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  importId: z.string().uuid(),
  sourceOrder: z.number().int().default(0),
  sourceLine: z.string().default(""),
  parsedQuantity: z.number().nullable().optional(),
  parsedUnit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]).nullable().optional(),
  parsedIngredientName: z.string().nullable().optional(),
  preparationNote: z.string().nullable().optional(),
  matchStatus: z.enum(["unresolved", "exact", "possible", "new", "confirmed_existing", "confirmed_new"]).default("unresolved"),
  matchedIngredientId: z.string().uuid().nullable().optional(),
  possibleMatchIngredientIds: z.array(z.string()).optional().default([]),
  resolvedAt: z.coerce.date().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type RecipeImportLine = z.infer<typeof RecipeImportLineSchema>;
