// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.554Z

import { z } from 'zod';

// Command: recordRefund on Invoice
export const InvoiceRecordRefundParamsSchema = z.object({
  refundAmount: z.number(),
  paymentId: z.string(),
});

export type InvoiceRecordRefundParams = z.infer<typeof InvoiceRecordRefundParamsSchema>;
