// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: recordResolutionProgress on RecipeImport
export const RecipeImportRecordResolutionProgressParamsSchema = z.object({
  resolvedLineCount: z.number().int(),
});

export type RecipeImportRecordResolutionProgressParams = z.infer<typeof RecipeImportRecordResolutionProgressParamsSchema>;
