// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: recordParse on RecipeImport
export const RecipeImportRecordParseParamsSchema = z.object({
  parsedName: z.string(),
  parsedLineCount: z.number().int(),
  parsedDescription: z.string().optional(),
  parsedCategory: z.string().optional(),
  parsedCuisine: z.string().optional(),
  parsedInstructions: z.string().optional(),
  parsedYieldQuantity: z.number().optional(),
  parsedYieldUnit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]).optional(),
  parsedBatchMultiplier: z.number().optional(),
});

export type RecipeImportRecordParseParams = z.infer<typeof RecipeImportRecordParseParamsSchema>;
