// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: recordReceipt on VendorOrderLine
export const VendorOrderLineRecordReceiptParamsSchema = z.object({
  quantity: z.number(),
  locationId: z.string().uuid(),
  discrepancyQuantity: z.number().optional(),
  discrepancyNotes: z.string().optional(),
});

export type VendorOrderLineRecordReceiptParams = z.infer<typeof VendorOrderLineRecordReceiptParamsSchema>;
