// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.916Z

import { z } from 'zod';

// Command: record on WasteRecord
export const WasteRecordRecordParamsSchema = z.object({
  ingredientId: z.string().uuid(),
  locationId: z.string().uuid(),
  quantity: z.number(),
  unit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]),
  reason: z.enum(["spoilage", "prep_error", "overproduction", "other"]),
  eventId: z.string().uuid().optional(),
  unitCost: z.number().optional(),
  notes: z.string().optional(),
});

export type WasteRecordRecordParams = z.infer<typeof WasteRecordRecordParamsSchema>;
