// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: recordRecipe on RecipeImport
export const RecipeImportRecordRecipeParamsSchema = z.object({
  resultingRecipeId: z.string().uuid(),
});

export type RecipeImportRecordRecipeParams = z.infer<typeof RecipeImportRecordRecipeParamsSchema>;
