// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: refund on Payment
export const PaymentRefundParamsSchema = z.object({
  reason: z.string(),
});

export type PaymentRefundParams = z.infer<typeof PaymentRefundParamsSchema>;
