// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.555Z

import { z } from 'zod';

// Command: register on Venue
export const VenueRegisterParamsSchema = z.object({
  name: z.string(),
  venueType: z.enum(["client_site", "banquet_hall", "outdoor", "office", "private_home", "other"]),
  capacity: z.number(),
  addressLine1: z.string().optional(),
  addressLine2: z.string().optional(),
  city: z.string().optional(),
  region: z.string().optional(),
  postalCode: z.string().optional(),
  countryCode: z.string().optional(),
  contactName: z.string().optional(),
  contactEmail: z.string().optional(),
  contactPhone: z.string().optional(),
  accessNotes: z.string().optional(),
  cateringNotes: z.string().optional(),
});

export type VenueRegisterParams = z.infer<typeof VenueRegisterParamsSchema>;
