// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: reinspect on QualityCheck
export const QualityCheckReinspectParamsSchema = z.object({});

export type QualityCheckReinspectParams = z.infer<typeof QualityCheckReinspectParamsSchema>;
