// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.555Z

import { z } from 'zod';

// Command: reinstate on Vendor
export const VendorReinstateParamsSchema = z.object({});

export type VendorReinstateParams = z.infer<typeof VendorReinstateParamsSchema>;
