// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: release on PrepTask
export const PrepTaskReleaseParamsSchema = z.object({});

export type PrepTaskReleaseParams = z.infer<typeof PrepTaskReleaseParamsSchema>;
