// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.554Z

import { z } from 'zod';

// Command: release on PrepTask
export const PrepTaskReleaseParamsSchema = z.object({});

export type PrepTaskReleaseParams = z.infer<typeof PrepTaskReleaseParamsSchema>;
