// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: remove on RecipeIngredient
export const RecipeIngredientRemoveParamsSchema = z.object({
  reason: z.string(),
});

export type RecipeIngredientRemoveParams = z.infer<typeof RecipeIngredientRemoveParamsSchema>;
