// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: rename on SavedReportDefinition
export const SavedReportDefinitionRenameParamsSchema = z.object({
  name: z.string(),
});

export type SavedReportDefinitionRenameParams = z.infer<typeof SavedReportDefinitionRenameParamsSchema>;
