// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: report on Incident
export const IncidentReportParamsSchema = z.object({
  eventId: z.string().uuid(),
  severity: z.enum(["low", "medium", "high", "critical"]),
  category: z.enum(["food_safety", "injury", "equipment", "service", "other"]),
  description: z.string(),
  prepTaskId: z.string().uuid().optional(),
  deliveryId: z.string().uuid().optional(),
  shiftId: z.string().uuid().optional(),
});

export type IncidentReportParams = z.infer<typeof IncidentReportParamsSchema>;
