// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: reschedule on Event
export const EventRescheduleParamsSchema = z.object({
  startsAt: z.coerce.date(),
  endsAt: z.coerce.date(),
});

export type EventRescheduleParams = z.infer<typeof EventRescheduleParamsSchema>;
