// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: resetResolution on RecipeImportLine
export const RecipeImportLineResetResolutionParamsSchema = z.object({});

export type RecipeImportLineResetResolutionParams = z.infer<typeof RecipeImportLineResetResolutionParamsSchema>;
