// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.554Z

import { z } from 'zod';

// Command: reserve on InventoryReservation
export const InventoryReservationReserveParamsSchema = z.object({
  inventoryItemId: z.string().uuid(),
  eventId: z.string().uuid(),
  ingredientId: z.string().uuid(),
  quantity: z.number(),
});

export type InventoryReservationReserveParams = z.infer<typeof InventoryReservationReserveParamsSchema>;
