// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: restore on SavedReportDefinition
export const SavedReportDefinitionRestoreParamsSchema = z.object({});

export type SavedReportDefinitionRestoreParams = z.infer<typeof SavedReportDefinitionRestoreParamsSchema>;
