// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: restore on SavedReportDefinition
export const SavedReportDefinitionRestoreParamsSchema = z.object({});

export type SavedReportDefinitionRestoreParams = z.infer<typeof SavedReportDefinitionRestoreParamsSchema>;
