// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: resumeReview on RecipeImport
export const RecipeImportResumeReviewParamsSchema = z.object({});

export type RecipeImportResumeReviewParams = z.infer<typeof RecipeImportResumeReviewParamsSchema>;
