// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: retire on Recipe
export const RecipeRetireParamsSchema = z.object({
  reason: z.string(),
});

export type RecipeRetireParams = z.infer<typeof RecipeRetireParamsSchema>;
