// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: retract on Recipe
export const RecipeRetractParamsSchema = z.object({});

export type RecipeRetractParams = z.infer<typeof RecipeRetractParamsSchema>;
