// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: retract on Recipe
export const RecipeRetractParamsSchema = z.object({});

export type RecipeRetractParams = z.infer<typeof RecipeRetractParamsSchema>;
