// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: returnToPlanning on Event
export const EventReturnToPlanningParamsSchema = z.object({
  reason: z.string(),
});

export type EventReturnToPlanningParams = z.infer<typeof EventReturnToPlanningParamsSchema>;
