// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: reviseDraft on Recipe
export const RecipeReviseDraftParamsSchema = z.object({
  name: z.string(),
  yieldQuantity: z.number(),
  yieldUnit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]),
  batchMultiplier: z.number(),
  category: z.string().optional(),
  cuisine: z.string().optional(),
  description: z.string().optional(),
  instructions: z.string().optional(),
});

export type RecipeReviseDraftParams = z.infer<typeof RecipeReviseDraftParamsSchema>;
