// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.810Z

import { z } from 'zod';

// Command: reviseDetails on StorageLocation
export const StorageLocationReviseDetailsParamsSchema = z.object({
  name: z.string(),
  locationType: z.string().optional(),
  temperatureZone: z.string().optional(),
  minTemperature: z.number().optional(),
  maxTemperature: z.number().optional(),
  temperatureUnit: z.string().optional(),
});

export type StorageLocationReviseDetailsParams = z.infer<typeof StorageLocationReviseDetailsParamsSchema>;
