// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: revoke on Qualification
export const QualificationRevokeParamsSchema = z.object({
  notes: z.string().optional(),
});

export type QualificationRevokeParams = z.infer<typeof QualificationRevokeParamsSchema>;
