// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: rsvpDecline on EventGuest
export const EventGuestRsvpDeclineParamsSchema = z.object({
  reason: z.string().optional(),
});

export type EventGuestRsvpDeclineParams = z.infer<typeof EventGuestRsvpDeclineParamsSchema>;
