// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.531Z

import { z } from 'zod';

// Entity: SavedReportDefinition
export const SavedReportDefinitionSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  ownerId: z.string().uuid().nullable().optional(),
  name: z.string().default(""),
  subjectArea: z.enum(["events", "sales", "inventory", "production", "workforce", "logistics", "finance"]).default("events"),
  chartType: z.string().default(""),
  definition: z.unknown().default({  }),
  sharingScope: z.enum(["owner_only", "team", "tenant_wide"]).default("owner_only"),
  status: z.enum(["active", "archived"]).default("active"),
  definedAt: z.coerce.date().nullable().optional(),
  archivedAt: z.coerce.date().nullable().optional(),
  restoredAt: z.coerce.date().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type SavedReportDefinition = z.infer<typeof SavedReportDefinitionSchema>;
