// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: schedule on Shift
export const ShiftScheduleParamsSchema = z.object({
  personId: z.string().uuid(),
  startsAt: z.coerce.date(),
  endsAt: z.coerce.date(),
  eventId: z.string().uuid().optional(),
  role: z.string().optional(),
  notes: z.string().optional(),
});

export type ShiftScheduleParams = z.infer<typeof ShiftScheduleParamsSchema>;
