// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: select on EventDish
export const EventDishSelectParamsSchema = z.object({
  eventId: z.string().uuid(),
  dishId: z.string().uuid(),
  quantityServings: z.number(),
  course: z.string().optional(),
  serviceStyle: z.string().optional(),
  specialInstructions: z.string().optional(),
});

export type EventDishSelectParams = z.infer<typeof EventDishSelectParamsSchema>;
