// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: send on Proposal
export const ProposalSendParamsSchema = z.object({});

export type ProposalSendParams = z.infer<typeof ProposalSendParamsSchema>;
