// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.555Z

import { z } from 'zod';

// Command: send on Proposal
export const ProposalSendParamsSchema = z.object({});

export type ProposalSendParams = z.infer<typeof ProposalSendParamsSchema>;
