// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: setPrimary on ClientContact
export const ClientContactSetPrimaryParamsSchema = z.object({});

export type ClientContactSetPrimaryParams = z.infer<typeof ClientContactSetPrimaryParamsSchema>;
