// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.554Z

import { z } from 'zod';

// Command: setPrimary on ClientContact
export const ClientContactSetPrimaryParamsSchema = z.object({});

export type ClientContactSetPrimaryParams = z.infer<typeof ClientContactSetPrimaryParamsSchema>;
