// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.658Z

import { z } from 'zod';

// Command: setPrimary on ClientContact
export const ClientContactSetPrimaryParamsSchema = z.object({});

export type ClientContactSetPrimaryParams = z.infer<typeof ClientContactSetPrimaryParamsSchema>;
