// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.554Z

import { z } from 'zod';

// Command: settle on Payment
export const PaymentSettleParamsSchema = z.object({});

export type PaymentSettleParams = z.infer<typeof PaymentSettleParamsSchema>;
