// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: settle on Payment
export const PaymentSettleParamsSchema = z.object({});

export type PaymentSettleParams = z.infer<typeof PaymentSettleParamsSchema>;
