// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: sign on Contract
export const ContractSignParamsSchema = z.object({
  signedBy: z.string(),
});

export type ContractSignParams = z.infer<typeof ContractSignParamsSchema>;
