// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: sign on Contract
export const ContractSignParamsSchema = z.object({
  signedBy: z.string(),
});

export type ContractSignParams = z.infer<typeof ContractSignParamsSchema>;
