// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Entity: SoftDeletable
export const SoftDeletableSchema = z.object({
  deletedAt: z.coerce.date().nullable().optional(),
});

export type SoftDeletable = z.infer<typeof SoftDeletableSchema>;
