// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: stage on RecipeImportLine
export const RecipeImportLineStageParamsSchema = z.object({
  importId: z.string().uuid(),
  sourceOrder: z.number().int(),
  sourceLine: z.string(),
  parsedQuantity: z.number().optional(),
  parsedUnit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]).optional(),
  parsedIngredientName: z.string().optional(),
  preparationNote: z.string().optional(),
});

export type RecipeImportLineStageParams = z.infer<typeof RecipeImportLineStageParamsSchema>;
