// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: startTransit on Delivery
export const DeliveryStartTransitParamsSchema = z.object({});

export type DeliveryStartTransitParams = z.infer<typeof DeliveryStartTransitParamsSchema>;
