// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.810Z

import { z } from 'zod';

// Command: start on Shift
export const ShiftStartParamsSchema = z.object({});

export type ShiftStartParams = z.infer<typeof ShiftStartParamsSchema>;
