// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: startTransit on Delivery
export const DeliveryStartTransitParamsSchema = z.object({});

export type DeliveryStartTransitParams = z.infer<typeof DeliveryStartTransitParamsSchema>;
