// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: start on Shift
export const ShiftStartParamsSchema = z.object({});

export type ShiftStartParams = z.infer<typeof ShiftStartParamsSchema>;
