// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.554Z

import { z } from 'zod';

// Command: startPacking on PackList
export const PackListStartPackingParamsSchema = z.object({});

export type PackListStartPackingParams = z.infer<typeof PackListStartPackingParamsSchema>;
