// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: startPacking on PackList
export const PackListStartPackingParamsSchema = z.object({});

export type PackListStartPackingParams = z.infer<typeof PackListStartPackingParamsSchema>;
