// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: start on Shift
export const ShiftStartParamsSchema = z.object({});

export type ShiftStartParams = z.infer<typeof ShiftStartParamsSchema>;
