// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Entity: StorageLocation
export const StorageLocationSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  name: z.string().default(""),
  locationType: z.string().nullable().optional(),
  temperatureZone: z.string().nullable().optional(),
  minTemperature: z.number().nullable().optional(),
  maxTemperature: z.number().nullable().optional(),
  temperatureUnit: z.string().nullable().optional(),
  status: z.enum(["active", "inactive"]).default("active"),
  registeredAt: z.coerce.date().nullable().optional(),
  deactivatedAt: z.coerce.date().nullable().optional(),
  deactivationReason: z.string().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

// Computed: StorageLocation
export const StorageLocationComputedSchema = StorageLocationSchema.extend({
  isActive: z.boolean(),
});

export type StorageLocation = z.infer<typeof StorageLocationSchema>;
export type StorageLocationWithComputed = z.infer<typeof StorageLocationComputedSchema>;
