// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: submitForApproval on Event
export const EventSubmitForApprovalParamsSchema = z.object({});

export type EventSubmitForApprovalParams = z.infer<typeof EventSubmitForApprovalParamsSchema>;
