// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: submit on VendorOrder
export const VendorOrderSubmitParamsSchema = z.object({});

export type VendorOrderSubmitParams = z.infer<typeof VendorOrderSubmitParamsSchema>;
