// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: suggestExactMatch on RecipeImportLine
export const RecipeImportLineSuggestExactMatchParamsSchema = z.object({
  matchedIngredientId: z.string().uuid(),
});

export type RecipeImportLineSuggestExactMatchParams = z.infer<typeof RecipeImportLineSuggestExactMatchParamsSchema>;
