// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: suggestPossibleMatches on RecipeImportLine
export const RecipeImportLineSuggestPossibleMatchesParamsSchema = z.object({
  possibleMatchIngredientIds: z.array(z.string()),
});

export type RecipeImportLineSuggestPossibleMatchesParams = z.infer<typeof RecipeImportLineSuggestPossibleMatchesParamsSchema>;
