// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: supersede on IngredientDemand
export const IngredientDemandSupersedeParamsSchema = z.object({
  reason: z.string(),
});

export type IngredientDemandSupersedeParams = z.infer<typeof IngredientDemandSupersedeParamsSchema>;
