// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: suspend on Vendor
export const VendorSuspendParamsSchema = z.object({
  reason: z.string(),
});

export type VendorSuspendParams = z.infer<typeof VendorSuspendParamsSchema>;
