// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.914Z

import { z } from 'zod';

// Entity: TenantScoped
export const TenantScopedSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
});

export type TenantScoped = z.infer<typeof TenantScopedSchema>;
