// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: terminate on Vendor
export const VendorTerminateParamsSchema = z.object({
  reason: z.string(),
});

export type VendorTerminateParams = z.infer<typeof VendorTerminateParamsSchema>;
