// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.531Z

import { z } from 'zod';

// Entity: TimeRecord
export const TimeRecordSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  personId: z.string().uuid(),
  shiftId: z.string().uuid().nullable().optional(),
  eventId: z.string().uuid().nullable().optional(),
  clockInAt: z.coerce.date().nullable().optional(),
  clockOutAt: z.coerce.date().nullable().optional(),
  breakMinutes: z.number().int().nullable().optional().default(0),
  notes: z.string().nullable().optional(),
  status: z.enum(["open", "closed", "corrected"]).default("open"),
  correctedAt: z.coerce.date().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

// Computed: TimeRecord
export const TimeRecordComputedSchema = TimeRecordSchema.extend({
  workedMinutes: z.number().nullable(),
});

export type TimeRecord = z.infer<typeof TimeRecordSchema>;
export type TimeRecordWithComputed = z.infer<typeof TimeRecordComputedSchema>;
