// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: transferOut on InventoryItem
export const InventoryItemTransferOutParamsSchema = z.object({
  quantity: z.number(),
  destinationLocationId: z.string().uuid(),
});

export type InventoryItemTransferOutParams = z.infer<typeof InventoryItemTransferOutParamsSchema>;
