// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: transferIn on InventoryItem
export const InventoryItemTransferInParamsSchema = z.object({
  quantity: z.number(),
  sourceLocationId: z.string().uuid(),
});

export type InventoryItemTransferInParams = z.infer<typeof InventoryItemTransferInParamsSchema>;
