// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.554Z

import { z } from 'zod';

// Command: unassign on EventAssignment
export const EventAssignmentUnassignParamsSchema = z.object({});

export type EventAssignmentUnassignParams = z.infer<typeof EventAssignmentUnassignParamsSchema>;
