// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: unassign on EventAssignment
export const EventAssignmentUnassignParamsSchema = z.object({});

export type EventAssignmentUnassignParams = z.infer<typeof EventAssignmentUnassignParamsSchema>;
