// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.554Z

import { z } from 'zod';

// Command: unblock on PrepTask
export const PrepTaskUnblockParamsSchema = z.object({});

export type PrepTaskUnblockParams = z.infer<typeof PrepTaskUnblockParamsSchema>;
