// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: unpublish on Menu
export const MenuUnpublishParamsSchema = z.object({
  reason: z.string(),
});

export type MenuUnpublishParams = z.infer<typeof MenuUnpublishParamsSchema>;
