// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: updateCosting on Ingredient
export const IngredientUpdateCostingParamsSchema = z.object({
  costPerUnit: z.number(),
});

export type IngredientUpdateCostingParams = z.infer<typeof IngredientUpdateCostingParamsSchema>;
