// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: updateInstructions on EventDish
export const EventDishUpdateInstructionsParamsSchema = z.object({
  specialInstructions: z.string().optional(),
});

export type EventDishUpdateInstructionsParams = z.infer<typeof EventDishUpdateInstructionsParamsSchema>;
