// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: updateCosting on Ingredient
export const IngredientUpdateCostingParamsSchema = z.object({
  costPerUnit: z.number(),
});

export type IngredientUpdateCostingParams = z.infer<typeof IngredientUpdateCostingParamsSchema>;
