// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T16:01:02.532Z

import { z } from 'zod';

// Command: updateLevels on InventoryItem
export const InventoryItemUpdateLevelsParamsSchema = z.object({
  parLevel: z.number(),
  reorderThreshold: z.number(),
  unitCost: z.number().optional(),
});

export type InventoryItemUpdateLevelsParams = z.infer<typeof InventoryItemUpdateLevelsParamsSchema>;
