// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: updateCosting on Ingredient
export const IngredientUpdateCostingParamsSchema = z.object({
  costPerUnit: z.number(),
});

export type IngredientUpdateCostingParams = z.infer<typeof IngredientUpdateCostingParamsSchema>;
