// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: updateDefinition on SavedReportDefinition
export const SavedReportDefinitionUpdateDefinitionParamsSchema = z.object({
  chartType: z.string().optional(),
  definition: z.unknown().optional(),
  subjectArea: z.enum(["events", "sales", "inventory", "production", "workforce", "logistics", "finance"]).optional(),
});

export type SavedReportDefinitionUpdateDefinitionParams = z.infer<typeof SavedReportDefinitionUpdateDefinitionParamsSchema>;
