// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: updatePortioning on Dish
export const DishUpdatePortioningParamsSchema = z.object({
  portionSize: z.number(),
  portionUnit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]),
});

export type DishUpdatePortioningParams = z.infer<typeof DishUpdatePortioningParamsSchema>;
