// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: updatePricing on Menu
export const MenuUpdatePricingParamsSchema = z.object({
  basePrice: z.number(),
  pricePerPerson: z.number(),
  minGuests: z.number(),
  maxGuests: z.number(),
});

export type MenuUpdatePricingParams = z.infer<typeof MenuUpdatePricingParamsSchema>;
