// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.915Z

import { z } from 'zod';

// Command: updateTotals on VendorOrder
export const VendorOrderUpdateTotalsParamsSchema = z.object({
  subtotal: z.number(),
  taxAmount: z.number(),
  shippingAmount: z.number(),
});

export type VendorOrderUpdateTotalsParams = z.infer<typeof VendorOrderUpdateTotalsParamsSchema>;
