// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.554Z

import { z } from 'zod';

// Command: updateInstructions on EventDish
export const EventDishUpdateInstructionsParamsSchema = z.object({
  specialInstructions: z.string().optional(),
});

export type EventDishUpdateInstructionsParams = z.infer<typeof EventDishUpdateInstructionsParamsSchema>;
