// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Command: upload on RecipeImport
export const RecipeImportUploadParamsSchema = z.object({
  sourceKind: z.enum(["pasted_text", "text_file", "csv_bundle"]),
  rawSourceText: z.string(),
  sourceByteCount: z.number().int(),
  sourceFingerprint: z.string(),
  sourceFilename: z.string().optional(),
});

export type RecipeImportUploadParams = z.infer<typeof RecipeImportUploadParamsSchema>;
