// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T10:11:16.914Z

import { z } from 'zod';

// Entity: VendorOrderLine
export const VendorOrderLineSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  vendorOrderId: z.string().uuid(),
  ingredientId: z.string().uuid(),
  ingredientDemandId: z.string().uuid().nullable().optional(),
  locationId: z.string().uuid().nullable().optional(),
  orderedQuantity: z.number().default(0),
  receivedQuantity: z.number().min(0).default(0),
  unit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]).default("each"),
  unitCost: z.number().min(0).default(0),
  discrepancyQuantity: z.number().nullable().optional(),
  discrepancyNotes: z.string().nullable().optional(),
  status: z.enum(["pending", "added", "receiving", "complete", "cancelled"]).default("pending"),
  addedAt: z.coerce.date().nullable().optional(),
  completedAt: z.coerce.date().nullable().optional(),
  cancelledAt: z.coerce.date().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

// Computed: VendorOrderLine
export const VendorOrderLineComputedSchema = VendorOrderLineSchema.extend({
  lineTotal: z.number(),
  remainingQuantity: z.number(),
});

export type VendorOrderLine = z.infer<typeof VendorOrderLineSchema>;
export type VendorOrderLineWithComputed = z.infer<typeof VendorOrderLineComputedSchema>;
