// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.554Z

import { z } from 'zod';

// Entity: VendorOrder
export const VendorOrderSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  vendorId: z.string().uuid(),
  eventId: z.string().uuid().nullable().optional(),
  orderNumber: z.string().nullable().optional(),
  subtotal: z.number().default(0),
  taxAmount: z.number().default(0),
  shippingAmount: z.number().default(0),
  totalAmount: z.number().default(0),
  notes: z.string().nullable().optional(),
  status: z.enum(["draft", "submitted", "confirmed", "partially_received", "received", "cancelled"]).default("draft"),
  openedAt: z.coerce.date().nullable().optional(),
  submittedAt: z.coerce.date().nullable().optional(),
  confirmedAt: z.coerce.date().nullable().optional(),
  receivedAt: z.coerce.date().nullable().optional(),
  cancelledAt: z.coerce.date().nullable().optional(),
  cancellationReason: z.string().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type VendorOrder = z.infer<typeof VendorOrderSchema>;
