// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:57:11.554Z

import { z } from 'zod';

// Entity: Vendor
export const VendorSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  name: z.string(),
  email: z.string().nullable().optional(),
  phone: z.string().nullable().optional(),
  addressLine1: z.string().nullable().optional(),
  city: z.string().nullable().optional(),
  region: z.string().nullable().optional(),
  postalCode: z.string().nullable().optional(),
  countryCode: z.string().nullable().optional(),
  paymentTermsDays: z.number().int().default(30),
  notes: z.string().nullable().optional(),
  status: z.enum(["active", "suspended", "terminated"]).default("active"),
  onboardedAt: z.coerce.date().nullable().optional(),
  suspendedAt: z.coerce.date().nullable().optional(),
  suspensionReason: z.string().nullable().optional(),
  terminatedAt: z.coerce.date().nullable().optional(),
  terminationReason: z.string().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export type Vendor = z.infer<typeof VendorSchema>;
