// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.658Z

import { z } from 'zod';

// Entity: Venue
export const VenueSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  name: z.string().default(""),
  venueType: z.enum(["client_site", "banquet_hall", "outdoor", "office", "private_home", "other"]).default("other"),
  addressLine1: z.string().nullable().optional(),
  addressLine2: z.string().nullable().optional(),
  city: z.string().nullable().optional(),
  region: z.string().nullable().optional(),
  postalCode: z.string().nullable().optional(),
  countryCode: z.string().nullable().optional(),
  contactName: z.string().nullable().optional(),
  contactEmail: z.string().nullable().optional(),
  contactPhone: z.string().nullable().optional(),
  accessNotes: z.string().nullable().optional(),
  cateringNotes: z.string().nullable().optional(),
  capacity: z.number().int().min(0).default(0),
  status: z.enum(["active", "inactive"]).default("active"),
  registeredAt: z.coerce.date().nullable().optional(),
  deactivatedAt: z.coerce.date().nullable().optional(),
  deactivationReason: z.string().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

// Computed: Venue
export const VenueComputedSchema = VenueSchema.extend({
  isActive: z.boolean(),
});

export type Venue = z.infer<typeof VenueSchema>;
export type VenueWithComputed = z.infer<typeof VenueComputedSchema>;
