// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.810Z

import { z } from 'zod';

// Command: voidRecord on WasteRecord
export const WasteRecordVoidRecordParamsSchema = z.object({
  reason: z.string(),
});

export type WasteRecordVoidRecordParams = z.infer<typeof WasteRecordVoidRecordParamsSchema>;
