// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T10:11:07.809Z

import { z } from 'zod';

// Entity: WasteRecord
export const WasteRecordSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string(),
  deletedAt: z.coerce.date().nullable().optional(),
  ingredientId: z.string().uuid(),
  locationId: z.string().uuid(),
  eventId: z.string().uuid().nullable().optional(),
  quantity: z.number().default(0),
  unit: z.enum(["each", "gram", "kilogram", "ounce", "pound", "milliliter", "liter", "teaspoon", "tablespoon", "cup", "pint", "quart", "gallon", "portion"]).default("each"),
  reason: z.enum(["spoilage", "prep_error", "overproduction", "other"]).default("other"),
  unitCost: z.number().min(0).default(0),
  status: z.enum(["pending", "recorded", "voided"]).default("pending"),
  notes: z.string().nullable().optional(),
  recordedAt: z.coerce.date().nullable().optional(),
  voidedAt: z.coerce.date().nullable().optional(),
  voidReason: z.string().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

// Computed: WasteRecord
export const WasteRecordComputedSchema = WasteRecordSchema.extend({
  costImpact: z.number(),
});

export type WasteRecord = z.infer<typeof WasteRecordSchema>;
export type WasteRecordWithComputed = z.infer<typeof WasteRecordComputedSchema>;
