// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-16T12:40:15.550Z

import { z } from 'zod';

// Command: withdraw on EventGuest
export const EventGuestWithdrawParamsSchema = z.object({
  reason: z.string(),
});

export type EventGuestWithdrawParams = z.infer<typeof EventGuestWithdrawParamsSchema>;
