// Auto-generated by Manifest Zod projection
// Generated at: 2026-07-17T09:51:22.659Z

import { z } from 'zod';

// Command: writeOff on Invoice
export const InvoiceWriteOffParamsSchema = z.object({
  reason: z.string(),
  writeOffAmount: z.number(),
});

export type InvoiceWriteOffParams = z.infer<typeof InvoiceWriteOffParamsSchema>;
